# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML wrapper for Hetmanski2021 rear retraction kinetic."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Hetmanski2021RearRetractionKineticModel(TelluriumSBMLBioModule):
    """Faithful Tellurium execution of the bundled SBML source model."""

    _SBML_ID = 'MODEL2103010001'
    _TITLE = 'Hetmanski2021 rear retraction kinetic'
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _HEADLINE_OUTPUTS = {'actinf': ('Actinf',
                'native SBML value',
                'Actinf. Maps to SBML symbol `Actinf` and is emitted in native SBML units.'),
     'p_mlca': ('pMLCa',
                'native SBML value',
                'P Mlca. Maps to SBML symbol `pMLCa` and is emitted in native SBML units.'),
     'cavi_src': ('Cavi_Src',
                  'native SBML value',
                  'Cavi Src. Maps to SBML symbol `Cavi_Src` and is emitted in native SBML units.')}
    _INITIAL_CONDITION_INPUTS = {'initial_rho_agdp': ('RhoAgdp',
                          0.0,
                          'native SBML value',
                          'Initial level of Rho Agdp. Maps to SBML symbol `RhoAgdp`; exposed as a '
                          'traceable initial-condition perturbation.')}
    _PARAMETER_INPUTS = {}
    _SPECIES_LABELS = {'RhoAgdp': 'Rho Agdp',
     'RhoAgtp': 'Rho Agtp',
     'Rock1i': 'Rock1i',
     'Rock1a': 'Rock1a',
     'RhoA_Rock1': 'Rho A Rock1',
     'DRFi': 'source-defined DRFI state',
     'DRFa': 'source-defined DRFA state',
     'PKN2i': 'Pkn2i',
     'RhoA_PKN2': 'Rho A PKN2',
     'PKN2a': 'Pkn2a',
     'LIMKi': 'Limki',
     'ROCK1_LIMK': 'ROCK1 LIMK',
     'LIMKa': 'Limka',
     'Cofilina': 'Cofilina',
     'LIMK_Cofilin': 'LIMK Cofilin',
     'Cofilini': 'Cofilini',
     'Actinag': 'Actinag',
     'DRF_Actin': 'DRF Actin',
     'Actinf': 'Actinf',
     'Cofilin_Actin': 'Cofilin Actin',
     'CPI_17i': 'CPI 17i',
     'PKN2_CPI17': 'PKN2 CPI17',
     'CPI_17a': 'CPI 17a',
     'ROCK1_CPI17': 'ROCK1 CPI17',
     'MLCPa': 'Mlcpa',
     'ROCK_MLCP': 'ROCK MLCP',
     'MLCPi': 'Mlcpi',
     'CPI17_MLCP': 'CPI17 MLCP',
     'RhoA_Drf': 'Rho A Drf',
     'ROCK1_DRF': 'ROCK1 DRF',
     'pMLCa': 'P Mlca',
     'pMLCi': 'P Mlci',
     'MLCP_PMLC': 'MLCP PMLC',
     'Rock1_pMLC_MLCP': 'Rock1 P MLC MLCP',
     'Cavi_Src': 'Cavi Src',
     'Cav1a': 'Cav1a',
     'Srca': 'source-defined SRCA state',
     'Cav1i': 'Cav1i',
     'Srci': 'source-defined SRCI state',
     'Cav_Gef': 'Cav Gef',
     'Gefi': 'source-defined GEFI state',
     'Gefa': 'source-defined GEFA state',
     'p190GAPi': 'P190gapi',
     'Src_p190': 'Src P190',
     'p190GAPa': 'P190gapa',
     'Actomyo_High': 'Actomyo High',
     'Polcont_High': 'Polcont High',
     'Polcont_Low': 'Polcont Low',
     'Polystiff_High': 'Polystiff High',
     'Recoil_Fast': 'Recoil Fast',
     'Tension_D': 'Tension D',
     'Tension_I': 'Tension I',
     'Actomyo_Low': 'Actomyo Low',
     'Recoil_Slow': 'Recoil Slow',
     'p190GAP_RhoA': 'P190gap Rho A',
     'Rho_Gef': 'Rho Gef',
     'Cava_Src': 'Cava Src',
     'Pkn2_Actin': 'Pkn2 Actin'}
    _STATE_OUTPUT_ALIASES = {'RhoAgdp': 'rho_agdp',
     'RhoAgtp': 'rho_agtp',
     'Rock1i': 'rock1i',
     'Rock1a': 'rock1a',
     'RhoA_Rock1': 'rho_a_rock1',
     'DRFi': 'source_defined_drfi_state',
     'DRFa': 'source_defined_drfa_state',
     'PKN2i': 'pkn2i',
     'RhoA_PKN2': 'rho_a_pkn2',
     'PKN2a': 'pkn2a',
     'LIMKi': 'limki',
     'ROCK1_LIMK': 'rock1_limk',
     'LIMKa': 'limka',
     'Cofilina': 'cofilina',
     'LIMK_Cofilin': 'limk_cofilin',
     'Cofilini': 'cofilini',
     'Actinag': 'actinag',
     'DRF_Actin': 'drf_actin',
     'Actinf': 'actinf',
     'Cofilin_Actin': 'cofilin_actin',
     'CPI_17i': 'cpi_17i',
     'PKN2_CPI17': 'pkn2_cpi17',
     'CPI_17a': 'cpi_17a',
     'ROCK1_CPI17': 'rock1_cpi17',
     'MLCPa': 'mlcpa',
     'ROCK_MLCP': 'rock_mlcp',
     'MLCPi': 'mlcpi',
     'CPI17_MLCP': 'cpi17_mlcp',
     'RhoA_Drf': 'rho_a_drf',
     'ROCK1_DRF': 'rock1_drf',
     'pMLCa': 'p_mlca',
     'pMLCi': 'p_mlci',
     'MLCP_PMLC': 'mlcp_pmlc',
     'Rock1_pMLC_MLCP': 'rock1_p_mlc_mlcp',
     'Cavi_Src': 'cavi_src',
     'Cav1a': 'cav1a',
     'Srca': 'source_defined_srca_state',
     'Cav1i': 'cav1i',
     'Srci': 'source_defined_srci_state',
     'Cav_Gef': 'cav_gef',
     'Gefi': 'source_defined_gefi_state',
     'Gefa': 'source_defined_gefa_state',
     'p190GAPi': 'p190gapi',
     'Src_p190': 'src_p190',
     'p190GAPa': 'p190gapa',
     'Actomyo_High': 'actomyo_high',
     'Polcont_High': 'polcont_high',
     'Polcont_Low': 'polcont_low',
     'Polystiff_High': 'polystiff_high',
     'Recoil_Fast': 'recoil_fast',
     'Tension_D': 'tension_d',
     'Tension_I': 'tension_i',
     'Actomyo_Low': 'actomyo_low',
     'Recoil_Slow': 'recoil_slow',
     'p190GAP_RhoA': 'p190gap_rho_a',
     'Rho_Gef': 'rho_gef',
     'Cava_Src': 'cava_src',
     'Pkn2_Actin': 'pkn2_actin'}

    def __init__(self, model_path: str = 'data/MODEL2103010001.xml', integration_step: float = 0.01) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


Hetmanski2021RearRetractionKineticModel2103010001Model = Hetmanski2021RearRetractionKineticModel
