# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML wrapper for Mosbacher2022 - Yeast HOG pathway."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Mosbacher2022YeastHogPathwayModel(TelluriumSBMLBioModule):
    """Faithful Tellurium execution of the bundled SBML source model."""

    _SBML_ID = 'MODEL2206230001'
    _TITLE = 'Mosbacher2022 - Yeast HOG pathway'
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _HEADLINE_OUTPUTS = {'sln1_phosphorylated': ('Sln1_phosphorylated',
                             'native SBML value',
                             'Sln1 Phosphorylated. Maps to SBML symbol `Sln1_phosphorylated` and is '
                             'emitted in native SBML units.'),
     'sln1p_phosphorylated': ('Sln1P_phosphorylated',
                              'native SBML value',
                              'Sln1p Phosphorylated. Maps to SBML symbol `Sln1P_phosphorylated` and is '
                              'emitted in native SBML units.'),
     'ssk1_phosphorylated': ('Ssk1_phosphorylated',
                             'native SBML value',
                             'Ssk1 Phosphorylated. Maps to SBML symbol `Ssk1_phosphorylated` and is '
                             'emitted in native SBML units.')}
    _INITIAL_CONDITION_INPUTS = {}
    _PARAMETER_INPUTS = {'initial_heximide_factor_level': ('heximide_factor',
                                       1.0,
                                       'native SBML value',
                                       'Heximide Factor source parameter. Maps to SBML symbol '
                                       '`heximide_factor` and preserves the bundled default.'),
     'initial_macia_factor_level': ('macia_factor',
                                    1.0,
                                    'native SBML value',
                                    'Macia Factor source parameter. Maps to SBML symbol `macia_factor` '
                                    'and preserves the bundled default.'),
     'initial_ptp2_factor_level': ('Ptp2_factor',
                                   1.0,
                                   'native SBML value',
                                   'Ptp2 Factor source parameter. Maps to SBML symbol `Ptp2_factor` '
                                   'and preserves the bundled default.')}
    _SPECIES_LABELS = {'V_os_cytosol': 'V Os Cytosol',
     'V_os_nucleus': 'V Os Nucleus',
     'V_os': 'source-defined V_OS state',
     'NaCl': 'source-defined NACL state',
     'V_os_pi_t_0': 'V Os Pi T 0',
     'PI_t_0': 'source-defined PI_T_0 state',
     'glycin': 'Glycin',
     'base_line': 'Base Line',
     'Pi_t_below_threshold': 'Pi T Below Threshold',
     'Sln1': 'source-defined SLN1 state',
     'Sln1P': 'Sln1p',
     'Ypd1': 'source-defined YPD1 state',
     'Ypd1P': 'Ypd1p',
     'Ssk1': 'source-defined SSK1 state',
     'Ssk1P': 'Ssk1p',
     'Ssk2': 'source-defined SSK2 state',
     'Ssk2P': 'Ssk2p',
     'Sln1_phosphorylated': 'Sln1 Phosphorylated',
     'Sln1P_phosphorylated': 'Sln1p Phosphorylated',
     'Ssk1_phosphorylated': 'Ssk1 Phosphorylated',
     'Ssk1P_phosphorylated': 'Ssk1p Phosphorylated',
     'Ssk2_phosphorylated': 'Ssk2 Phosphorylated',
     'Ssk2_phosphorylated_second': 'Ssk2 Phosphorylated Second',
     'Ssk2P_phosphorylated': 'Ssk2p Phosphorylated',
     'Ssk2P_phosphorylated_second': 'Ssk2p Phosphorylated Second',
     'Sho1': 'source-defined SHO1 state',
     'Sho1_active': 'Sho1 active',
     'Sho1_Pbs2': 'Sho1 Pbs2',
     'Sho1_active_Pbs2': 'Sho1 active Pbs2',
     'Sho1_active_Ste11_Pbs2_inactive': 'Sho1 active Ste11 Pbs2 Inactive',
     'Sho1_active_Ste11_Pbs2': 'Sho1 active Ste11 Pbs2',
     'Sho1_active_Ste11': 'Sho1 active Ste11',
     'Sho1_active_Ste11PP': 'Sho1 active Ste11pp',
     'Sho1_active_Ste11_Pbs2P': 'Sho1 active Ste11 Pbs2p',
     'Sho1_active_Ste11_Pbs2PP': 'Sho1 active Ste11 Pbs2pp',
     'Ste11': 'Ste11',
     'Ste11_Ste50': 'Ste11 Ste50',
     'Ste50': 'Ste50',
     'Ste11PP': 'Ste1pp',
     'Sho1_Pbs2_phosphorylated': 'Sho1 Pbs2 Phosphorylated',
     'Sho1_active_Pbs2_phosphorylated': 'Sho1 active Pbs2 Phosphorylated',
     'Sho1_active_Ste11_Pbs2_phosphorylated_inactive': 'Sho1 active Ste11 Pbs2 Phosphorylated Inactive',
     'Sho1_active_Ste11_Pbs2_phosphorylated': 'Sho1 active Ste11 Pbs2 Phosphorylated',
     'Sho1_active_Ste11_Pbs2P_phosphorylated': 'Sho1 active Ste11 Pbs2p Phosphorylated',
     'Sho1_active_Ste11_Pbs2PP_phosphorylated': 'Sho1 active Ste11 Pbs2pp Phosphorylated',
     'Sho1_active_Ste11_Pbs2_inactive_phosphorylated': 'Sho1 active Ste11 Pbs2 Inactive Phosphorylated',
     'Sho1_active_Ste11_phosphorylated': 'Sho1 active Ste11 Phosphorylated',
     'Sho1_active_Ste11PP_phosphorylated': 'Sho1 active Ste11pp Phosphorylated',
     'Ste20': 'Ste20',
     'Ste20_phosphorylated': 'Ste20 Phosphorylated',
     'Pbs2': 'source-defined PBS2 state',
     'Pbs2PP': 'Pbs2pp',
     'Pbs2P': 'Pbs2p',
     'Pbs2_phosphorylated': 'Pbs2 Phosphorylated',
     'Pbs2P_phosphorylated': 'Pbs2p Phosphorylated',
     'Pbs2PP_phosphorylated': 'Pbs2pp Phosphorylated',
     'Hog1c': 'Hog1c',
     'Hog1n': 'Hog1n',
     'Hog1P174c': 'Hog1p174c',
     'Hog1P176c': 'Hog1p176c',
     'Hog1P174n': 'Hog1p174n',
     'Hog1P176n': 'Hog1p176n',
     'Hog1PPc': 'Hog1ppc',
     'Hog1PPn': 'Hog1ppn',
     'Hog1c_Pbs2PP': 'Hog1c Pbs2pp',
     'Hog1P174c_Pbs2PP': 'Hog1p174c Pbs2pp',
     'Hog1P176c_Pbs2PP': 'Hog1p176c Pbs2pp',
     'Hog1PPc_Pbs2PP': 'Hog1ppc Pbs2pp',
     'Hog1c_Pbs2_phosphorylated': 'Hog1c Pbs2 Phosphorylated',
     'Hog1P176c_Pbs2_phosphorylated': 'Hog1p176c Pbs2 Phosphorylated',
     'Hog1P174c_Pbs2_phosphorylated': 'Hog1p174c Pbs2 Phosphorylated',
     'Hog1PPc_Pbs2_phosphorylated': 'Hog1ppc Pbs2 Phosphorylated',
     'Hog1c_Pbs2PP_phosphorylated': 'Hog1c Pbs2pp Phosphorylated',
     'Hog1P176c_Pbs2PP_phosphorylated': 'Hog1p176c Pbs2pp Phosphorylated',
     'Hog1P174c_Pbs2PP_phosphorylated': 'Hog1p174c Pbs2pp Phosphorylated',
     'Hog1PPc_Pbs2PP_phosphorylated': 'Hog1ppc Pbs2pp Phosphorylated',
     'Hog1c_Pbs2': 'Hog1c Pbs2',
     'Hog1P176c_Pbs2': 'Hog1p176c Pbs2',
     'Hog1P174c_Pbs2': 'Hog1p174c Pbs2',
     'Hog1PPc_Pbs2': 'Hog1ppc Pbs2',
     'Ptp3': 'source-defined PTP3 state',
     'Ptp3_active': 'Ptp3 active',
     'Ptc1': 'source-defined PTC1 state',
     'Ptc': 'source-defined PTC state',
     'Ptp2': 'source-defined PTP2 state',
     'Ptp2_active': 'Ptp2 active',
     'additional_phosphatase_cyto': 'Additional Phosphatase Cyto',
     'additional_phosphatase_nucleus': 'Additional Phosphatase Nucleus',
     'Gene_off_phosphatase': 'Gene Off Phosphatase',
     'Gene_on_phosphatase': 'Gene On Phosphatase',
     'Gene_off_phosphatase_Hog1PPn': 'Gene Off Phosphatase Hog1ppn',
     'Gene_on_phosphatase_Hog1PPn': 'Gene On Phosphatase Hog1ppn',
     'Gene_on_phosphatase_r': 'Gene On Phosphatase R',
     'Gene_on_phosphatase_r_Hog1PPn': 'Gene On Phosphatase R Hog1ppn',
     'mRNA': 'source-defined MRNA state',
     'mRNA_cytosol': 'M RNA Cytosol',
     'Gpd1': 'source-defined GPD1 state',
     'Gpd1_pre': 'Gpd1 Pre'}
    _STATE_OUTPUT_ALIASES = {'V_os_cytosol': 'v_os_cytosol',
     'V_os_nucleus': 'v_os_nucleus',
     'V_os': 'source_defined_v_os_state',
     'NaCl': 'source_defined_nacl_state',
     'V_os_pi_t_0': 'v_os_pi_t_0',
     'PI_t_0': 'source_defined_pi_t_0_state',
     'glycin': 'glycin',
     'base_line': 'base_line',
     'Pi_t_below_threshold': 'pi_t_below_threshold',
     'Sln1': 'source_defined_sln1_state',
     'Sln1P': 'sln1p',
     'Ypd1': 'source_defined_ypd1_state',
     'Ypd1P': 'ypd1p',
     'Ssk1': 'source_defined_ssk1_state',
     'Ssk1P': 'ssk1p',
     'Ssk2': 'source_defined_ssk2_state',
     'Ssk2P': 'ssk2p',
     'Sln1_phosphorylated': 'sln1_phosphorylated',
     'Sln1P_phosphorylated': 'sln1p_phosphorylated',
     'Ssk1_phosphorylated': 'ssk1_phosphorylated',
     'Ssk1P_phosphorylated': 'ssk1p_phosphorylated',
     'Ssk2_phosphorylated': 'ssk2_phosphorylated',
     'Ssk2_phosphorylated_second': 'ssk2_phosphorylated_second',
     'Ssk2P_phosphorylated': 'ssk2p_phosphorylated',
     'Ssk2P_phosphorylated_second': 'ssk2p_phosphorylated_second',
     'Sho1': 'source_defined_sho1_state',
     'Sho1_active': 'sho1_active',
     'Sho1_Pbs2': 'sho1_pbs2',
     'Sho1_active_Pbs2': 'sho1_active_pbs2',
     'Sho1_active_Ste11_Pbs2_inactive': 'sho1_active_ste11_pbs2_inactive',
     'Sho1_active_Ste11_Pbs2': 'sho1_active_ste11_pbs2',
     'Sho1_active_Ste11': 'sho1_active_ste11',
     'Sho1_active_Ste11PP': 'sho1_active_ste11pp',
     'Sho1_active_Ste11_Pbs2P': 'sho1_active_ste11_pbs2p',
     'Sho1_active_Ste11_Pbs2PP': 'sho1_active_ste11_pbs2pp',
     'Ste11': 'ste11',
     'Ste11_Ste50': 'ste11_ste50',
     'Ste50': 'ste50',
     'Ste11PP': 'ste1pp',
     'Sho1_Pbs2_phosphorylated': 'sho1_pbs2_phosphorylated',
     'Sho1_active_Pbs2_phosphorylated': 'sho1_active_pbs2_phosphorylated',
     'Sho1_active_Ste11_Pbs2_phosphorylated_inactive': 'sho1_active_ste11_pbs2_phosphorylated_inactive',
     'Sho1_active_Ste11_Pbs2_phosphorylated': 'sho1_active_ste11_pbs2_phosphorylated',
     'Sho1_active_Ste11_Pbs2P_phosphorylated': 'sho1_active_ste11_pbs2p_phosphorylated',
     'Sho1_active_Ste11_Pbs2PP_phosphorylated': 'sho1_active_ste11_pbs2pp_phosphorylated',
     'Sho1_active_Ste11_Pbs2_inactive_phosphorylated': 'sho1_active_ste11_pbs2_inactive_phosphorylated',
     'Sho1_active_Ste11_phosphorylated': 'sho1_active_ste11_phosphorylated',
     'Sho1_active_Ste11PP_phosphorylated': 'sho1_active_ste11pp_phosphorylated',
     'Ste20': 'ste20',
     'Ste20_phosphorylated': 'ste20_phosphorylated',
     'Pbs2': 'source_defined_pbs2_state',
     'Pbs2PP': 'pbs2pp',
     'Pbs2P': 'pbs2p',
     'Pbs2_phosphorylated': 'pbs2_phosphorylated',
     'Pbs2P_phosphorylated': 'pbs2p_phosphorylated',
     'Pbs2PP_phosphorylated': 'pbs2pp_phosphorylated',
     'Hog1c': 'hog1c',
     'Hog1n': 'hog1n',
     'Hog1P174c': 'hog1p174c',
     'Hog1P176c': 'hog1p176c',
     'Hog1P174n': 'hog1p174n',
     'Hog1P176n': 'hog1p176n',
     'Hog1PPc': 'hog1ppc',
     'Hog1PPn': 'hog1ppn',
     'Hog1c_Pbs2PP': 'hog1c_pbs2pp',
     'Hog1P174c_Pbs2PP': 'hog1p174c_pbs2pp',
     'Hog1P176c_Pbs2PP': 'hog1p176c_pbs2pp',
     'Hog1PPc_Pbs2PP': 'hog1ppc_pbs2pp',
     'Hog1c_Pbs2_phosphorylated': 'hog1c_pbs2_phosphorylated',
     'Hog1P176c_Pbs2_phosphorylated': 'hog1p176c_pbs2_phosphorylated',
     'Hog1P174c_Pbs2_phosphorylated': 'hog1p174c_pbs2_phosphorylated',
     'Hog1PPc_Pbs2_phosphorylated': 'hog1ppc_pbs2_phosphorylated',
     'Hog1c_Pbs2PP_phosphorylated': 'hog1c_pbs2pp_phosphorylated',
     'Hog1P176c_Pbs2PP_phosphorylated': 'hog1p176c_pbs2pp_phosphorylated',
     'Hog1P174c_Pbs2PP_phosphorylated': 'hog1p174c_pbs2pp_phosphorylated',
     'Hog1PPc_Pbs2PP_phosphorylated': 'hog1ppc_pbs2pp_phosphorylated',
     'Hog1c_Pbs2': 'hog1c_pbs2',
     'Hog1P176c_Pbs2': 'hog1p176c_pbs2',
     'Hog1P174c_Pbs2': 'hog1p174c_pbs2',
     'Hog1PPc_Pbs2': 'hog1ppc_pbs2',
     'Ptp3': 'source_defined_ptp3_state',
     'Ptp3_active': 'ptp3_active',
     'Ptc1': 'source_defined_ptc1_state',
     'Ptc': 'source_defined_ptc_state',
     'Ptp2': 'source_defined_ptp2_state',
     'Ptp2_active': 'ptp2_active',
     'additional_phosphatase_cyto': 'additional_phosphatase_cyto',
     'additional_phosphatase_nucleus': 'additional_phosphatase_nucleus',
     'Gene_off_phosphatase': 'gene_off_phosphatase',
     'Gene_on_phosphatase': 'gene_on_phosphatase',
     'Gene_off_phosphatase_Hog1PPn': 'gene_off_phosphatase_hog1ppn',
     'Gene_on_phosphatase_Hog1PPn': 'gene_on_phosphatase_hog1ppn',
     'Gene_on_phosphatase_r': 'gene_on_phosphatase_r',
     'Gene_on_phosphatase_r_Hog1PPn': 'gene_on_phosphatase_r_hog1ppn',
     'mRNA': 'source_defined_mrna_state',
     'mRNA_cytosol': 'm_rna_cytosol',
     'Gpd1': 'source_defined_gpd1_state',
     'Gpd1_pre': 'gpd1_pre'}

    def __init__(self, model_path: str = 'data/MODEL2206230001.xml', integration_step: float = 0.01) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


Mosbacher2022YeastHogPathwayModel2206230001Model = Mosbacher2022YeastHogPathwayModel
