# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML wrapper for Maeda2006_MyosinPhosphorylation."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Maeda2006MyosinphosphorylationModel(TelluriumSBMLBioModule):
    """Faithful Tellurium execution of the bundled SBML source model."""

    _SBML_ID = 'BIOMD0000000088'
    _TITLE = 'Maeda2006_MyosinPhosphorylation'
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _HEADLINE_OUTPUTS = {'thrombin_r_active': ('s57',
                           'native SBML value',
                           'Thrombin R active. Maps to SBML symbol `s57` and is emitted in native SBML '
                           'units.'),
     'rho_gef_active': ('s245',
                        'native SBML value',
                        'Rho GEF active. Maps to SBML symbol `s245` and is emitted in native SBML '
                        'units.'),
     'calcium_super_2_endsuper_calcium_m': ('s277',
                                            'native SBML value',
                                            'calcium Super 2 Endsuper calcium M. Maps to SBML symbol '
                                            '`s277` and is emitted in native SBML units.')}
    _INITIAL_CONDITION_INPUTS = {'initial_calcium_super_2_endsuper_ext': ('s267',
                                              4000.0,
                                              'native SBML value',
                                              'Initial level of calcium Super 2 Endsuper Ext. Maps to '
                                              'SBML symbol `s267`; exposed as a traceable '
                                              'initial-condition perturbation.'),
     'initial_gdp': ('s50',
                     5.0,
                     'native SBML value',
                     'Initial level of GDP. Maps to SBML symbol `s50`; exposed as a traceable '
                     'initial-condition perturbation.'),
     'initial_gtp': ('s48',
                     50.0,
                     'native SBML value',
                     'Initial level of GTP. Maps to SBML symbol `s48`; exposed as a traceable '
                     'initial-condition perturbation.')}
    _PARAMETER_INPUTS = {}
    _SPECIES_LABELS = {'s2': 'Thrombin',
     's174': 'Thrombin R',
     's130': 'Pro Thrombin R',
     's4': 'Thrombin Ligand',
     's57': 'Thrombin R active',
     's93': 'source-defined RGS state',
     's165': 'Inositol',
     's183': 'Sa40 Degraded',
     's55': 'Thrombin R',
     's184': 'source-defined RGS state',
     's48': 'GTP',
     's187': 'G Sub Q Endsub Alpha GTP',
     's50': 'GDP',
     's171': 'IP3R',
     's173': '3IP3 IP3R',
     's98': 'P115rho GEF',
     's124': 'Rho Kinase',
     's118': 'Rho GAP',
     's153': 'DAG',
     's152': 'IP3',
     's213': 'Rho GAP',
     's214': 'Rho GTP',
     's151': 'source-defined PIP2 state',
     's164': 'source-defined PC state',
     's231': 'Rho GDP',
     's233': 'Rho GEF',
     's245': 'Rho GEF active',
     's252': 'Rho GTP Rho Kinase',
     's277': 'calcium Super 2 Endsuper calcium M',
     's278': '2ca Super 2 Endsuper calcium M',
     's279': '3ca Super 2 Endsuper calcium M',
     's280': '4ca Super 2 Endsuper calcium M',
     's289': 'source-defined MLCK state',
     's292': 'MLCK calcium Super 2 Endsuper calcium M',
     's293': 'MLCK 2ca Super 2 Endsuper calcium M',
     's294': 'MLCK 3ca Super 2 Endsuper calcium M',
     's295': 'MLCK 4ca Super 2 Endsuper calcium M',
     's309': 'PKC',
     's310': 'PKC Active1',
     's311': 'PKC DAG',
     's314': 'PKC active 2',
     's324': 'PKC active 3',
     's329': 'Csa39 Degraded',
     's330': 'Csa36 Degraded',
     's331': 'Csa35 Degraded',
     's332': 'PKC active 1 CPI',
     's335': 'PKC active 2 CPI',
     's338': 'PKC active 3 CPI',
     's352': 'CPI 17 MYPT1 Ppase',
     's355': 'CPI 17 MYPT1 Ppase',
     's349': 'CPI 17',
     's360': 'source-defined MLC state',
     's358': 'source-defined MLC state',
     's361': 'Rho Kinase MLC',
     's362': 'Rho Kinase MLC',
     's350': 'CPI 17',
     's135': 'calcium Super 2 Endsuper',
     's276': 'calmodulin',
     's172': 'calcium Super 2 Endsuper Store',
     's410': 'G beta response parameter Gamma 1',
     's421': 'G beta response parameter Gamma 2',
     's424': 'PLC beta response parameter',
     's430': 'calcium Super 2 Endsuper Trunsp',
     's432': 'calcium Super 2 Endsuper Pump',
     's435': 'G Sub 12 Endsub Alpha beta response parameter Gamma Thrombin R active',
     's436': 'P115rho GEF GTP Alpha',
     's437': 'G Sub 12 Endsub Alpha beta response parameter Gamma',
     's438': 'G Sub 12 Endsub Alpha GDP',
     's439': 'G Sub 12 Endsub Alpha GTP',
     's440': 'G Sub Q Endsub Alpha GDP',
     's441': 'G Sub Q Endsub Alpha beta response parameter Gamma Thrombin R active',
     's442': 'G Sub Q Endsub Alpha beta response parameter Gamma',
     's443': 'PLC beta response parameter G Sub Q Endsub Alpha GTP',
     's444': '2ca Super 2 Endsuper calcium Super 2 Endsuper Trunsp',
     's446': 'calcium Super 2 Endsuper Pump calcium Super 2 Endsuper',
     's449': 'Rho GTP Rho Kinase MLC',
     's456': 'Rho GTP Rho Kinase MLC',
     's359': 'source-defined MLC state',
     's463': 'MYPT1 Rho Kinase',
     's467': 'MYPT1 MLC',
     's470': 'MYPT1 MLC',
     's477': 'MYPT1 MLC',
     's480': 'MYPT1 MLC',
     's491': 'MLCK MLC',
     's487': 'MLCK MLC',
     's496': 'MYPT1 Rho Kinase',
     's506': 'MLCK 4ca Super 2 Endsuper calcium M MLC',
     's512': 'MLCK 3ca Super 2 Endsuper calcium M MLC',
     's513': 'MLCK 4ca Super 2 Endsuper calcium M MLC',
     's520': 'MLCK 3ca Super 2 Endsuper calcium M MLC',
     's526': 'MLCK 2ca Super 2 Endsuper calcium M MLC',
     's539': 'MLCK 2ca Super 2 Endsuper calcium M MLC',
     's546': 'MLCK calcium Super 2 Endsuper calcium M MLC',
     's551': 'MLCK calcium Super 2 Endsuper calcium M MLC',
     's556': 'calcium Super 2 Endsuper Ext Leak',
     's267': 'calcium Super 2 Endsuper Ext',
     's557': 'calcium Super 2 Endsuper Int Leak',
     's564': 'PLC beta response parameter G Sub Q Endsub Alpha GTP calcium Super 2 Endsuper',
     's565': 'PKC calcium Super 2 Endsuper DAG',
     's566': 'PKC calcium Super 2 Endsuper',
     's567': 'PLC beta response parameter G Sub Q Endsub GTP calcium PIP2',
     's568': 'PLC beta response parameter calcium PIP2',
     's569': 'PLC beta response parameter calcium Super 2 Endsuper',
     's351': 'MYPT1 Ppase',
     's570': 'MYPT1 Ppase'}
    _STATE_OUTPUT_ALIASES = {'s2': 'thrombin',
     's174': 'thrombin_r',
     's130': 'pro_thrombin_r',
     's4': 'thrombin_ligand',
     's57': 'thrombin_r_active',
     's93': 'source_defined_rgs_state',
     's165': 'inositol',
     's183': 'sa40_degraded',
     's55': 'thrombin_r_2',
     's184': 'source_defined_rgs_state_2',
     's48': 'gtp',
     's187': 'g_sub_q_endsub_alpha_gtp',
     's50': 'gdp',
     's171': 'ip3r',
     's173': 'source_3ip3_ip3r',
     's98': 'p115rho_gef',
     's124': 'rho_kinase',
     's118': 'rho_gap',
     's153': 'dag',
     's152': 'ip3',
     's213': 'rho_gap_2',
     's214': 'rho_gtp',
     's151': 'source_defined_pip2_state',
     's164': 'source_defined_pc_state',
     's231': 'rho_gdp',
     's233': 'rho_gef',
     's245': 'rho_gef_active',
     's252': 'rho_gtp_rho_kinase',
     's277': 'calcium_super_2_endsuper_calcium_m',
     's278': 'source_2ca_super_2_endsuper_calcium_m',
     's279': 'source_3ca_super_2_endsuper_calcium_m',
     's280': 'source_4ca_super_2_endsuper_calcium_m',
     's289': 'source_defined_mlck_state',
     's292': 'mlck_calcium_super_2_endsuper_calcium_m',
     's293': 'mlck_2ca_super_2_endsuper_calcium_m',
     's294': 'mlck_3ca_super_2_endsuper_calcium_m',
     's295': 'mlck_4ca_super_2_endsuper_calcium_m',
     's309': 'pkc',
     's310': 'pkc_active1',
     's311': 'pkc_dag',
     's314': 'pkc_active_2',
     's324': 'pkc_active_3',
     's329': 'csa39_degraded',
     's330': 'csa36_degraded',
     's331': 'csa35_degraded',
     's332': 'pkc_active_1_cpi',
     's335': 'pkc_active_2_cpi',
     's338': 'pkc_active_3_cpi',
     's352': 'cpi_17_mypt1_ppase',
     's355': 'cpi_17_mypt1_ppase_2',
     's349': 'cpi_17',
     's360': 'source_defined_mlc_state',
     's358': 'source_defined_mlc_state_2',
     's361': 'rho_kinase_mlc',
     's362': 'rho_kinase_mlc_2',
     's350': 'cpi_17_2',
     's135': 'calcium_super_2_endsuper',
     's276': 'calmodulin',
     's172': 'calcium_super_2_endsuper_store',
     's410': 'g_beta_response_parameter_gamma_1',
     's421': 'g_beta_response_parameter_gamma_2',
     's424': 'plc_beta_response_parameter',
     's430': 'calcium_super_2_endsuper_trunsp',
     's432': 'calcium_super_2_endsuper_pump',
     's435': 'g_sub_12_endsub_alpha_beta_response_parameter_gamma_thrombin_r_active',
     's436': 'p115rho_gef_gtp_alpha',
     's437': 'g_sub_12_endsub_alpha_beta_response_parameter_gamma',
     's438': 'g_sub_12_endsub_alpha_gdp',
     's439': 'g_sub_12_endsub_alpha_gtp',
     's440': 'g_sub_q_endsub_alpha_gdp',
     's441': 'g_sub_q_endsub_alpha_beta_response_parameter_gamma_thrombin_r_active',
     's442': 'g_sub_q_endsub_alpha_beta_response_parameter_gamma',
     's443': 'plc_beta_response_parameter_g_sub_q_endsub_alpha_gtp',
     's444': 'source_2ca_super_2_endsuper_calcium_super_2_endsuper_trunsp',
     's446': 'calcium_super_2_endsuper_pump_calcium_super_2_endsuper',
     's449': 'rho_gtp_rho_kinase_mlc',
     's456': 'rho_gtp_rho_kinase_mlc_2',
     's359': 'source_defined_mlc_state_3',
     's463': 'mypt1_rho_kinase',
     's467': 'mypt1_mlc',
     's470': 'mypt1_mlc_2',
     's477': 'mypt1_mlc_3',
     's480': 'mypt1_mlc_4',
     's491': 'mlck_mlc',
     's487': 'mlck_mlc_2',
     's496': 'mypt1_rho_kinase_2',
     's506': 'mlck_4ca_super_2_endsuper_calcium_m_mlc',
     's512': 'mlck_3ca_super_2_endsuper_calcium_m_mlc',
     's513': 'mlck_4ca_super_2_endsuper_calcium_m_mlc_2',
     's520': 'mlck_3ca_super_2_endsuper_calcium_m_mlc_2',
     's526': 'mlck_2ca_super_2_endsuper_calcium_m_mlc',
     's539': 'mlck_2ca_super_2_endsuper_calcium_m_mlc_2',
     's546': 'mlck_calcium_super_2_endsuper_calcium_m_mlc',
     's551': 'mlck_calcium_super_2_endsuper_calcium_m_mlc_2',
     's556': 'calcium_super_2_endsuper_ext_leak',
     's267': 'calcium_super_2_endsuper_ext',
     's557': 'calcium_super_2_endsuper_int_leak',
     's564': 'plc_beta_response_parameter_g_sub_q_endsub_alpha_gtp_calcium_super_2_endsuper',
     's565': 'pkc_calcium_super_2_endsuper_dag',
     's566': 'pkc_calcium_super_2_endsuper',
     's567': 'plc_beta_response_parameter_g_sub_q_endsub_gtp_calcium_pip2',
     's568': 'plc_beta_response_parameter_calcium_pip2',
     's569': 'plc_beta_response_parameter_calcium_super_2_endsuper',
     's351': 'mypt1_ppase',
     's570': 'mypt1_ppase_2'}

    def __init__(self, model_path: str = 'data/BIOMD0000000088.xml', integration_step: float = 0.01) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


Maeda2006MyosinphosphorylationBiomd0000000088Model = Maeda2006MyosinphosphorylationModel
