# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML wrapper for Smith2013 - Regulation of Insulin Signalling by Oxidative Stress."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Smith2013RegulationOfInsulinSignallingByOxModel(TelluriumSBMLBioModule):
    """Faithful Tellurium execution of the bundled SBML source model."""

    _SBML_ID = 'BIOMD0000000474'
    _TITLE = 'Smith2013 - Regulation of Insulin Signalling by Oxidative Stress'
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _HEADLINE_OUTPUTS = {'in_r_active': ('InR_active',
                     'native SBML value',
                     'In R active. Maps to SBML symbol `InR_active` and is emitted in native SBML '
                     'units.'),
     'akt': ('Akt',
             'native SBML value',
             'AKT. Maps to SBML symbol `Akt` and is emitted in native SBML units.'),
     'source_defined_akt_p2_state': ('Akt_P2',
                                     'native SBML value',
                                     'source-defined AKT_P2 state. Maps to SBML symbol `Akt_P2` and is '
                                     'emitted in native SBML units.')}
    _INITIAL_CONDITION_INPUTS = {'initial_cytoplasm_foxo1_tot': ('cytoplasm_Foxo1_tot',
                                     1000.0,
                                     'native SBML value',
                                     'Initial level of Cytoplasm Foxo1 Tot. Maps to SBML symbol '
                                     '`cytoplasm_Foxo1_tot`; exposed as a traceable initial-condition '
                                     'perturbation.'),
     'initial_dnabound_foxo1_tot': ('dnabound_Foxo1_tot',
                                    0.0,
                                    'native SBML value',
                                    'Initial level of Dnabound Foxo1 Tot. Maps to SBML symbol '
                                    '`dnabound_Foxo1_tot`; exposed as a traceable initial-condition '
                                    'perturbation.'),
     'initial_dusp_dusp_ox': ('DUSP_plus_DUSP_ox',
                              100000.0,
                              'native SBML value',
                              'Initial level of DUSP DUSP Ox. Maps to SBML symbol `DUSP_plus_DUSP_ox`; '
                              'exposed as a traceable initial-condition perturbation.')}
    _PARAMETER_INPUTS = {}
    _SPECIES_LABELS = {'Ins': 'source-defined INS state',
     'InR': 'source-defined INR state',
     'Ins_InR': 'Ins In R',
     'Ins_InR_P': 'Ins In R P',
     'Ins_2_InR_P': 'Ins 2 In R P',
     'cytoplasm_InR': 'Cytoplasm In R',
     'cytoplasm_Ins_2_InR_P': 'Cytoplasm Ins 2 In R P',
     'cytoplasm_Ins_InR_P': 'Cytoplasm Ins In R P',
     'InR_tot': 'In R Tot',
     'InR_bound': 'In R bound',
     'InR_active': 'In R active',
     'PTP1B': 'PTP1B',
     'IRS1_TyrP_PI3K': 'IRS1 tyrosine site P PI3K',
     'PI345P3': 'PI345P3',
     'PIP2': 'source-defined PIP2 state',
     'PI345P3_mol': 'PI345P3 Mol',
     'PIP2_mol': 'PIP2 Mol',
     'Akt': 'AKT',
     'Akt_P2': 'source-defined AKT_P2 state',
     'PKC': 'PKC',
     'PKC_P': 'source-defined PKC_P state',
     'AS160': 'AS160',
     'AS160_P': 'AS160 P',
     'cytoplasm_GLUT4': 'Cytoplasm GLUT4',
     'cellsurface_GLUT4': 'Cellsurface GLUT4',
     'PTEN': 'source-defined PTEN state',
     'PP2A': 'PP2A',
     'extracellular_ROS': 'Extracellular ROS',
     'PTP1B_ox': 'PTP1B Ox',
     'PTP1B_plus_PTP1B_ox': 'PTP1B PTP1B Ox',
     'PTEN_ox': 'PTEN Ox',
     'PTEN_plus_PTEN_ox': 'PTEN PTEN Ox',
     'ROS': 'source-defined ROS state',
     'GSH': 'source-defined GSH state',
     'GSSG': 'source-defined GSSG state',
     'cytoplasm_SOD2': 'Cytoplasm SOD2',
     'NOX_inact': 'NOX Inact',
     'NOX': 'source-defined NOX state',
     'NOX_deact': 'NOX Deact',
     'NOX_total': 'NOX Total',
     'Mt': 'source-defined MT state',
     'IRS1': 'source-defined IRS1 state',
     'IRS1_TyrP': 'IRS1 tyrosine site P',
     'IRS1_PolySerP': 'IRS1 Poly Ser P',
     'IRS1_TyrP_PolySerP': 'IRS1 tyrosine site P Poly Ser P',
     'IRS_total': 'IRS Total',
     'PI3K': 'PI3K',
     'JNK_P': 'source-defined JNK_P state',
     'IKK_P': 'source-defined IKK_P state',
     'JNK': 'source-defined JNK state',
     'JNK_plus_JNK_P': 'JNK JNK P',
     'IKK': 'source-defined IKK state',
     'IKK_plus_IKK_P': 'IKK IKK P',
     'DUSP': 'source-defined DUSP state',
     'DUSP_ox': 'DUSP Ox',
     'DUSP_plus_DUSP_ox': 'DUSP DUSP Ox',
     'cytoplasm_Foxo1_Pa0_Pd0_Pe0_pUb0': 'Cytoplasm Foxo1 Pa0 Pd0 Pe0 P Ub0',
     'nucleus_Foxo1_Pa0_Pd0_Pe0_pUb0': 'Nucleus Foxo1 Pa0 Pd0 Pe0 P Ub0',
     'dnabound_Foxo1_Pa0_Pd0_Pe0_pUb0': 'Dnabound Foxo1 Pa0 Pd0 Pe0 P Ub0',
     'cytoplasm_Foxo1_Pa0_Pd0_Pe0_pUb1': 'Cytoplasm Foxo1 Pa0 Pd0 Pe0 P Ub1',
     'nucleus_Foxo1_Pa0_Pd0_Pe0_pUb1': 'Nucleus Foxo1 Pa0 Pd0 Pe0 P Ub1',
     'dnabound_Foxo1_Pa0_Pd0_Pe0_pUb1': 'Dnabound Foxo1 Pa0 Pd0 Pe0 P Ub1',
     'cytoplasm_Foxo1_Pa0_Pd0_Pe1_pUb0': 'Cytoplasm Foxo1 Pa0 Pd0 Pe1 P Ub0',
     'nucleus_Foxo1_Pa0_Pd0_Pe1_pUb0': 'Nucleus Foxo1 Pa0 Pd0 Pe1 P Ub0',
     'dnabound_Foxo1_Pa0_Pd0_Pe1_pUb0': 'Dnabound Foxo1 Pa0 Pd0 Pe1 P Ub0',
     'cytoplasm_Foxo1_Pa0_Pd0_Pe1_pUb1': 'Cytoplasm Foxo1 Pa0 Pd0 Pe1 P Ub1',
     'nucleus_Foxo1_Pa0_Pd0_Pe1_pUb1': 'Nucleus Foxo1 Pa0 Pd0 Pe1 P Ub1',
     'dnabound_Foxo1_Pa0_Pd0_Pe1_pUb1': 'Dnabound Foxo1 Pa0 Pd0 Pe1 P Ub1',
     'cytoplasm_Foxo1_Pa0_Pd1_Pe0_pUb0': 'Cytoplasm Foxo1 Pa0 Pd1 Pe0 P Ub0',
     'nucleus_Foxo1_Pa0_Pd1_Pe0_pUb0': 'Nucleus Foxo1 Pa0 Pd1 Pe0 P Ub0',
     'dnabound_Foxo1_Pa0_Pd1_Pe0_pUb0': 'Dnabound Foxo1 Pa0 Pd1 Pe0 P Ub0',
     'cytoplasm_Foxo1_Pa0_Pd1_Pe0_pUb1': 'Cytoplasm Foxo1 Pa0 Pd1 Pe0 P Ub1',
     'nucleus_Foxo1_Pa0_Pd1_Pe0_pUb1': 'Nucleus Foxo1 Pa0 Pd1 Pe0 P Ub1',
     'dnabound_Foxo1_Pa0_Pd1_Pe0_pUb1': 'Dnabound Foxo1 Pa0 Pd1 Pe0 P Ub1',
     'cytoplasm_Foxo1_Pa0_Pd1_Pe1_pUb0': 'Cytoplasm Foxo1 Pa0 Pd1 Pe1 P Ub0',
     'nucleus_Foxo1_Pa0_Pd1_Pe1_pUb0': 'Nucleus Foxo1 Pa0 Pd1 Pe1 P Ub0',
     'dnabound_Foxo1_Pa0_Pd1_Pe1_pUb0': 'Dnabound Foxo1 Pa0 Pd1 Pe1 P Ub0',
     'cytoplasm_Foxo1_Pa0_Pd1_Pe1_pUb1': 'Cytoplasm Foxo1 Pa0 Pd1 Pe1 P Ub1',
     'nucleus_Foxo1_Pa0_Pd1_Pe1_pUb1': 'Nucleus Foxo1 Pa0 Pd1 Pe1 P Ub1',
     'dnabound_Foxo1_Pa0_Pd1_Pe1_pUb1': 'Dnabound Foxo1 Pa0 Pd1 Pe1 P Ub1',
     'cytoplasm_Foxo1_Pa1_Pd0_Pe0_pUb0': 'Cytoplasm Foxo1 Pa1 Pd0 Pe0 P Ub0',
     'nucleus_Foxo1_Pa1_Pd0_Pe0_pUb0': 'Nucleus Foxo1 Pa1 Pd0 Pe0 P Ub0',
     'dnabound_Foxo1_Pa1_Pd0_Pe0_pUb0': 'Dnabound Foxo1 Pa1 Pd0 Pe0 P Ub0',
     'cytoplasm_Foxo1_Pa1_Pd0_Pe0_pUb1': 'Cytoplasm Foxo1 Pa1 Pd0 Pe0 P Ub1',
     'nucleus_Foxo1_Pa1_Pd0_Pe0_pUb1': 'Nucleus Foxo1 Pa1 Pd0 Pe0 P Ub1',
     'dnabound_Foxo1_Pa1_Pd0_Pe0_pUb1': 'Dnabound Foxo1 Pa1 Pd0 Pe0 P Ub1',
     'cytoplasm_Foxo1_Pa1_Pd0_Pe1_pUb0': 'Cytoplasm Foxo1 Pa1 Pd0 Pe1 P Ub0',
     'nucleus_Foxo1_Pa1_Pd0_Pe1_pUb0': 'Nucleus Foxo1 Pa1 Pd0 Pe1 P Ub0',
     'dnabound_Foxo1_Pa1_Pd0_Pe1_pUb0': 'Dnabound Foxo1 Pa1 Pd0 Pe1 P Ub0',
     'cytoplasm_Foxo1_Pa1_Pd0_Pe1_pUb1': 'Cytoplasm Foxo1 Pa1 Pd0 Pe1 P Ub1',
     'nucleus_Foxo1_Pa1_Pd0_Pe1_pUb1': 'Nucleus Foxo1 Pa1 Pd0 Pe1 P Ub1',
     'dnabound_Foxo1_Pa1_Pd0_Pe1_pUb1': 'Dnabound Foxo1 Pa1 Pd0 Pe1 P Ub1',
     'cytoplasm_Foxo1_Pa1_Pd1_Pe0_pUb0': 'Cytoplasm Foxo1 Pa1 Pd1 Pe0 P Ub0',
     'nucleus_Foxo1_Pa1_Pd1_Pe0_pUb0': 'Nucleus Foxo1 Pa1 Pd1 Pe0 P Ub0',
     'dnabound_Foxo1_Pa1_Pd1_Pe0_pUb0': 'Dnabound Foxo1 Pa1 Pd1 Pe0 P Ub0',
     'cytoplasm_Foxo1_Pa1_Pd1_Pe0_pUb1': 'Cytoplasm Foxo1 Pa1 Pd1 Pe0 P Ub1',
     'nucleus_Foxo1_Pa1_Pd1_Pe0_pUb1': 'Nucleus Foxo1 Pa1 Pd1 Pe0 P Ub1',
     'dnabound_Foxo1_Pa1_Pd1_Pe0_pUb1': 'Dnabound Foxo1 Pa1 Pd1 Pe0 P Ub1',
     'cytoplasm_Foxo1_Pa1_Pd1_Pe1_pUb0': 'Cytoplasm Foxo1 Pa1 Pd1 Pe1 P Ub0',
     'nucleus_Foxo1_Pa1_Pd1_Pe1_pUb0': 'Nucleus Foxo1 Pa1 Pd1 Pe1 P Ub0',
     'dnabound_Foxo1_Pa1_Pd1_Pe1_pUb0': 'Dnabound Foxo1 Pa1 Pd1 Pe1 P Ub0',
     'cytoplasm_Foxo1_Pa1_Pd1_Pe1_pUb1': 'Cytoplasm Foxo1 Pa1 Pd1 Pe1 P Ub1',
     'nucleus_Foxo1_Pa1_Pd1_Pe1_pUb1': 'Nucleus Foxo1 Pa1 Pd1 Pe1 P Ub1',
     'dnabound_Foxo1_Pa1_Pd1_Pe1_pUb1': 'Dnabound Foxo1 Pa1 Pd1 Pe1 P Ub1',
     'Foxo1_Pa0_tot': 'Foxo1 Pa0 Tot',
     'Foxo1_Pa1_tot': 'Foxo1 Pa1 Tot',
     'Foxo1_Pd0_tot': 'Foxo1 Pd0 Tot',
     'Foxo1_Pd1_tot': 'Foxo1 Pd1 Tot',
     'Foxo1_Pe0_tot': 'Foxo1 Pe0 Tot',
     'Foxo1_Pe1_tot': 'Foxo1 Pe1 Tot',
     'Foxo1_pUb0_tot': 'Foxo1 P Ub0 Tot',
     'Foxo1_pUb1_tot': 'Foxo1 P Ub1 Tot',
     'cytoplasm_Foxo1_tot': 'Cytoplasm Foxo1 Tot',
     'nucleus_Foxo1_tot': 'Nucleus Foxo1 Tot',
     'dnabound_Foxo1_tot': 'Dnabound Foxo1 Tot',
     'Foxo1_all': 'Foxo1 All',
     'nucleus_RNA_InR': 'Nucleus RNA In R',
     'cytoplasm_RNA_InR': 'Cytoplasm RNA In R',
     'nucleus_RNA_SOD2': 'Nucleus RNA SOD2',
     'cytoplasm_RNA_SOD2': 'Cytoplasm RNA SOD2',
     'E2F1': 'E2F1',
     'SGK': 'source-defined SGK state',
     'CDK2': 'source-defined CDK2 state',
     'AMPK': 'source-defined AMPK state',
     'CBPP300': 'CBPP300',
     'SIRT1': 'source-defined SIRT1 state',
     'E3': 'source-defined E3 state',
     'USP7': 'source-defined USP7 state',
     'SCF': 'source-defined SCF state',
     'Proteasome': 'Proteasome'}
    _STATE_OUTPUT_ALIASES = {'Ins': 'source_defined_ins_state',
     'InR': 'source_defined_inr_state',
     'Ins_InR': 'ins_in_r',
     'Ins_InR_P': 'ins_in_r_p',
     'Ins_2_InR_P': 'ins_2_in_r_p',
     'cytoplasm_InR': 'cytoplasm_in_r',
     'cytoplasm_Ins_2_InR_P': 'cytoplasm_ins_2_in_r_p',
     'cytoplasm_Ins_InR_P': 'cytoplasm_ins_in_r_p',
     'InR_tot': 'in_r_tot',
     'InR_bound': 'in_r_bound',
     'InR_active': 'in_r_active',
     'PTP1B': 'ptp1b',
     'IRS1_TyrP_PI3K': 'irs1_tyrosine_site_p_pi3k',
     'PI345P3': 'pi345p3',
     'PIP2': 'source_defined_pip2_state',
     'PI345P3_mol': 'pi345p3_mol',
     'PIP2_mol': 'pip2_mol',
     'Akt': 'akt',
     'Akt_P2': 'source_defined_akt_p2_state',
     'PKC': 'pkc',
     'PKC_P': 'source_defined_pkc_p_state',
     'AS160': 'as160',
     'AS160_P': 'as160_p',
     'cytoplasm_GLUT4': 'cytoplasm_glut4',
     'cellsurface_GLUT4': 'cellsurface_glut4',
     'PTEN': 'source_defined_pten_state',
     'PP2A': 'pp2a',
     'extracellular_ROS': 'extracellular_ros',
     'PTP1B_ox': 'ptp1b_ox',
     'PTP1B_plus_PTP1B_ox': 'ptp1b_ptp1b_ox',
     'PTEN_ox': 'pten_ox',
     'PTEN_plus_PTEN_ox': 'pten_pten_ox',
     'ROS': 'source_defined_ros_state',
     'GSH': 'source_defined_gsh_state',
     'GSSG': 'source_defined_gssg_state',
     'cytoplasm_SOD2': 'cytoplasm_sod2',
     'NOX_inact': 'nox_inact',
     'NOX': 'source_defined_nox_state',
     'NOX_deact': 'nox_deact',
     'NOX_total': 'nox_total',
     'Mt': 'source_defined_mt_state',
     'IRS1': 'source_defined_irs1_state',
     'IRS1_TyrP': 'irs1_tyrosine_site_p',
     'IRS1_PolySerP': 'irs1_poly_ser_p',
     'IRS1_TyrP_PolySerP': 'irs1_tyrosine_site_p_poly_ser_p',
     'IRS_total': 'irs_total',
     'PI3K': 'pi3k',
     'JNK_P': 'source_defined_jnk_p_state',
     'IKK_P': 'source_defined_ikk_p_state',
     'JNK': 'source_defined_jnk_state',
     'JNK_plus_JNK_P': 'jnk_jnk_p',
     'IKK': 'source_defined_ikk_state',
     'IKK_plus_IKK_P': 'ikk_ikk_p',
     'DUSP': 'source_defined_dusp_state',
     'DUSP_ox': 'dusp_ox',
     'DUSP_plus_DUSP_ox': 'dusp_dusp_ox',
     'cytoplasm_Foxo1_Pa0_Pd0_Pe0_pUb0': 'cytoplasm_foxo1_pa0_pd0_pe0_p_ub0',
     'nucleus_Foxo1_Pa0_Pd0_Pe0_pUb0': 'nucleus_foxo1_pa0_pd0_pe0_p_ub0',
     'dnabound_Foxo1_Pa0_Pd0_Pe0_pUb0': 'dnabound_foxo1_pa0_pd0_pe0_p_ub0',
     'cytoplasm_Foxo1_Pa0_Pd0_Pe0_pUb1': 'cytoplasm_foxo1_pa0_pd0_pe0_p_ub1',
     'nucleus_Foxo1_Pa0_Pd0_Pe0_pUb1': 'nucleus_foxo1_pa0_pd0_pe0_p_ub1',
     'dnabound_Foxo1_Pa0_Pd0_Pe0_pUb1': 'dnabound_foxo1_pa0_pd0_pe0_p_ub1',
     'cytoplasm_Foxo1_Pa0_Pd0_Pe1_pUb0': 'cytoplasm_foxo1_pa0_pd0_pe1_p_ub0',
     'nucleus_Foxo1_Pa0_Pd0_Pe1_pUb0': 'nucleus_foxo1_pa0_pd0_pe1_p_ub0',
     'dnabound_Foxo1_Pa0_Pd0_Pe1_pUb0': 'dnabound_foxo1_pa0_pd0_pe1_p_ub0',
     'cytoplasm_Foxo1_Pa0_Pd0_Pe1_pUb1': 'cytoplasm_foxo1_pa0_pd0_pe1_p_ub1',
     'nucleus_Foxo1_Pa0_Pd0_Pe1_pUb1': 'nucleus_foxo1_pa0_pd0_pe1_p_ub1',
     'dnabound_Foxo1_Pa0_Pd0_Pe1_pUb1': 'dnabound_foxo1_pa0_pd0_pe1_p_ub1',
     'cytoplasm_Foxo1_Pa0_Pd1_Pe0_pUb0': 'cytoplasm_foxo1_pa0_pd1_pe0_p_ub0',
     'nucleus_Foxo1_Pa0_Pd1_Pe0_pUb0': 'nucleus_foxo1_pa0_pd1_pe0_p_ub0',
     'dnabound_Foxo1_Pa0_Pd1_Pe0_pUb0': 'dnabound_foxo1_pa0_pd1_pe0_p_ub0',
     'cytoplasm_Foxo1_Pa0_Pd1_Pe0_pUb1': 'cytoplasm_foxo1_pa0_pd1_pe0_p_ub1',
     'nucleus_Foxo1_Pa0_Pd1_Pe0_pUb1': 'nucleus_foxo1_pa0_pd1_pe0_p_ub1',
     'dnabound_Foxo1_Pa0_Pd1_Pe0_pUb1': 'dnabound_foxo1_pa0_pd1_pe0_p_ub1',
     'cytoplasm_Foxo1_Pa0_Pd1_Pe1_pUb0': 'cytoplasm_foxo1_pa0_pd1_pe1_p_ub0',
     'nucleus_Foxo1_Pa0_Pd1_Pe1_pUb0': 'nucleus_foxo1_pa0_pd1_pe1_p_ub0',
     'dnabound_Foxo1_Pa0_Pd1_Pe1_pUb0': 'dnabound_foxo1_pa0_pd1_pe1_p_ub0',
     'cytoplasm_Foxo1_Pa0_Pd1_Pe1_pUb1': 'cytoplasm_foxo1_pa0_pd1_pe1_p_ub1',
     'nucleus_Foxo1_Pa0_Pd1_Pe1_pUb1': 'nucleus_foxo1_pa0_pd1_pe1_p_ub1',
     'dnabound_Foxo1_Pa0_Pd1_Pe1_pUb1': 'dnabound_foxo1_pa0_pd1_pe1_p_ub1',
     'cytoplasm_Foxo1_Pa1_Pd0_Pe0_pUb0': 'cytoplasm_foxo1_pa1_pd0_pe0_p_ub0',
     'nucleus_Foxo1_Pa1_Pd0_Pe0_pUb0': 'nucleus_foxo1_pa1_pd0_pe0_p_ub0',
     'dnabound_Foxo1_Pa1_Pd0_Pe0_pUb0': 'dnabound_foxo1_pa1_pd0_pe0_p_ub0',
     'cytoplasm_Foxo1_Pa1_Pd0_Pe0_pUb1': 'cytoplasm_foxo1_pa1_pd0_pe0_p_ub1',
     'nucleus_Foxo1_Pa1_Pd0_Pe0_pUb1': 'nucleus_foxo1_pa1_pd0_pe0_p_ub1',
     'dnabound_Foxo1_Pa1_Pd0_Pe0_pUb1': 'dnabound_foxo1_pa1_pd0_pe0_p_ub1',
     'cytoplasm_Foxo1_Pa1_Pd0_Pe1_pUb0': 'cytoplasm_foxo1_pa1_pd0_pe1_p_ub0',
     'nucleus_Foxo1_Pa1_Pd0_Pe1_pUb0': 'nucleus_foxo1_pa1_pd0_pe1_p_ub0',
     'dnabound_Foxo1_Pa1_Pd0_Pe1_pUb0': 'dnabound_foxo1_pa1_pd0_pe1_p_ub0',
     'cytoplasm_Foxo1_Pa1_Pd0_Pe1_pUb1': 'cytoplasm_foxo1_pa1_pd0_pe1_p_ub1',
     'nucleus_Foxo1_Pa1_Pd0_Pe1_pUb1': 'nucleus_foxo1_pa1_pd0_pe1_p_ub1',
     'dnabound_Foxo1_Pa1_Pd0_Pe1_pUb1': 'dnabound_foxo1_pa1_pd0_pe1_p_ub1',
     'cytoplasm_Foxo1_Pa1_Pd1_Pe0_pUb0': 'cytoplasm_foxo1_pa1_pd1_pe0_p_ub0',
     'nucleus_Foxo1_Pa1_Pd1_Pe0_pUb0': 'nucleus_foxo1_pa1_pd1_pe0_p_ub0',
     'dnabound_Foxo1_Pa1_Pd1_Pe0_pUb0': 'dnabound_foxo1_pa1_pd1_pe0_p_ub0',
     'cytoplasm_Foxo1_Pa1_Pd1_Pe0_pUb1': 'cytoplasm_foxo1_pa1_pd1_pe0_p_ub1',
     'nucleus_Foxo1_Pa1_Pd1_Pe0_pUb1': 'nucleus_foxo1_pa1_pd1_pe0_p_ub1',
     'dnabound_Foxo1_Pa1_Pd1_Pe0_pUb1': 'dnabound_foxo1_pa1_pd1_pe0_p_ub1',
     'cytoplasm_Foxo1_Pa1_Pd1_Pe1_pUb0': 'cytoplasm_foxo1_pa1_pd1_pe1_p_ub0',
     'nucleus_Foxo1_Pa1_Pd1_Pe1_pUb0': 'nucleus_foxo1_pa1_pd1_pe1_p_ub0',
     'dnabound_Foxo1_Pa1_Pd1_Pe1_pUb0': 'dnabound_foxo1_pa1_pd1_pe1_p_ub0',
     'cytoplasm_Foxo1_Pa1_Pd1_Pe1_pUb1': 'cytoplasm_foxo1_pa1_pd1_pe1_p_ub1',
     'nucleus_Foxo1_Pa1_Pd1_Pe1_pUb1': 'nucleus_foxo1_pa1_pd1_pe1_p_ub1',
     'dnabound_Foxo1_Pa1_Pd1_Pe1_pUb1': 'dnabound_foxo1_pa1_pd1_pe1_p_ub1',
     'Foxo1_Pa0_tot': 'foxo1_pa0_tot',
     'Foxo1_Pa1_tot': 'foxo1_pa1_tot',
     'Foxo1_Pd0_tot': 'foxo1_pd0_tot',
     'Foxo1_Pd1_tot': 'foxo1_pd1_tot',
     'Foxo1_Pe0_tot': 'foxo1_pe0_tot',
     'Foxo1_Pe1_tot': 'foxo1_pe1_tot',
     'Foxo1_pUb0_tot': 'foxo1_p_ub0_tot',
     'Foxo1_pUb1_tot': 'foxo1_p_ub1_tot',
     'cytoplasm_Foxo1_tot': 'cytoplasm_foxo1_tot',
     'nucleus_Foxo1_tot': 'nucleus_foxo1_tot',
     'dnabound_Foxo1_tot': 'dnabound_foxo1_tot',
     'Foxo1_all': 'foxo1_all',
     'nucleus_RNA_InR': 'nucleus_rna_in_r',
     'cytoplasm_RNA_InR': 'cytoplasm_rna_in_r',
     'nucleus_RNA_SOD2': 'nucleus_rna_sod2',
     'cytoplasm_RNA_SOD2': 'cytoplasm_rna_sod2',
     'E2F1': 'e2f1',
     'SGK': 'source_defined_sgk_state',
     'CDK2': 'source_defined_cdk2_state',
     'AMPK': 'source_defined_ampk_state',
     'CBPP300': 'cbpp300',
     'SIRT1': 'source_defined_sirt1_state',
     'E3': 'source_defined_e3_state',
     'USP7': 'source_defined_usp7_state',
     'SCF': 'source_defined_scf_state',
     'Proteasome': 'proteasome'}

    def __init__(self, model_path: str = 'data/BIOMD0000000474.xml', integration_step: float = 0.01) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


Smith2013RegulationOfInsulinSignallingByOxBiomd0000000474Model = Smith2013RegulationOfInsulinSignallingByOxModel
