# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML wrapper for Borisov2009_EGF_Insulin_Crosstalk."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Borisov2009EgfInsulinCrosstalkModel(TelluriumSBMLBioModule):
    """Faithful Tellurium execution of the bundled SBML source model."""

    _SBML_ID = 'BIOMD0000000223'
    _TITLE = 'Borisov2009_EGF_Insulin_Crosstalk'
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _HEADLINE_OUTPUTS = {'ras_gap': ('RasGAP',
                 'native SBML value',
                 'RAS GAP. Maps to SBML symbol `RasGAP` and is emitted in native SBML units.'),
     'rp_ras_gap': ('Rp_RasGAP',
                    'native SBML value',
                    'Rp RAS GAP. Maps to SBML symbol `Rp_RasGAP` and is emitted in native SBML units.'),
     'phosphorylated_insulin_receptor_ras_gap': ('IRp_RasGAP',
                                                 'native SBML value',
                                                 'Phosphorylated Insulin Receptor RAS GAP. Maps to '
                                                 'SBML symbol `IRp_RasGAP` and is emitted in native '
                                                 'SBML units.')}
    _INITIAL_CONDITION_INPUTS = {'initial_egf': ('EGF',
                     1.0,
                     'native SBML value',
                     'Initial level of EGF. Maps to SBML symbol `EGF`; exposed as a traceable '
                     'initial-condition perturbation.')}
    _PARAMETER_INPUTS = {}
    _SPECIES_LABELS = {'EGF': 'EGF',
     'I': 'Source Defined I State',
     'RE': 'Source Defined RE State',
     'Rd': 'Source Defined RD State',
     'Rp': 'Source Defined RP State',
     'GS': 'Source Defined GS State',
     'Rp_GS': 'Source Defined RP GS State',
     'Shc': 'Shc adapter protein Adapter Protein Adapter Protein Adapter Protein Adapter Protein '
            'Adapter Protein',
     'Rp_Shc': 'Rp Shc adapter protein Adapter Protein Adapter Protein Adapter Protein Adapter Protein '
               'Adapter Protein',
     'Rp_pShc': 'Rp Phospho Shc adapter protein Adapter Protein Adapter Protein Adapter Protein '
                'Adapter Protein Adapter Protein',
     'pShc': 'Phospho Shc adapter protein Adapter Protein Adapter Protein Adapter Protein Adapter '
             'Protein Adapter Protein',
     'Rp_pShc_GS': 'Rp Phospho Shc adapter protein Adapter Protein Adapter Protein Adapter Protein '
                   'Adapter Protein Adapter Protein GS',
     'PI3K': 'PI3K',
     'Rp_PI3K': 'Rp PI3K',
     'RasGAP': 'RAS GAP',
     'Rp_RasGAP': 'Rp RAS GAP',
     'IRL': 'Source Defined IRL State',
     'IRp': 'Phosphorylated Insulin Receptor',
     'IRp_PI3K': 'Phosphorylated Insulin Receptor PI3K',
     'IRp_RasGAP': 'Phosphorylated Insulin Receptor RAS GAP',
     'IRS': 'IRS',
     'IRp_IRS': 'Phosphorylated Insulin Receptor IRS',
     'IRp_IRSp': 'Phosphorylated Insulin Receptor Irsp',
     'IRSp': 'Source Defined IRSP State',
     'iSrc': 'Source Defined ISRC State',
     'mIRS': 'Source Defined MIRS State',
     'mIRSp': 'Mirsp',
     'mIRSp_GS': 'Mirsp GS',
     'mIRSp_PI3K': 'Mirsp PI3K',
     'SHP2': 'Source Defined SHP2 State',
     'mIRSp_SHP2': 'Mirsp SHP2',
     'GAB': 'Source Defined GAB State',
     'mGAB': 'Source Defined MGAB State',
     'mGABp': 'Mgabp',
     'mGABp_GS': 'Mgabp GS',
     'mGABp_PI3K': 'Mgabp PI3K',
     'mGABp_SHP2': 'Mgabp SHP2',
     'mGABp_pSHP2': 'Mgabp PSHP2',
     'PIP3': 'Source Defined Phosphorylated IP3 State',
     'dRas': 'Source Defined DRAS State',
     'Raf': 'RAF',
     'aRaf': 'Source Defined ARAF State',
     'Mek': 'MEK',
     'Erk': 'ERK',
     'pErk': 'Phospho ERK',
     'PDK1': 'Source Defined PDK1 State',
     'Akt': 'AKT',
     'pAkt': 'Phospho AKT',
     'mTOR': 'mTOR',
     'Null': 'Source Defined NULL State',
     'aaRaf': 'Aa RAF',
     'PKA': 'Source Defined PKA State',
     'pShc_GS': 'Phospho Shc adapter protein Adapter Protein Adapter Protein Adapter Protein Adapter '
                'Protein Adapter Protein GS',
     'ppMek': 'Pp MEK',
     'mGABp_pSHP2_GS': 'Mgabp PSHP2 GS',
     'R': 'Source Defined R State',
     'ppErk': 'Pp ERK',
     'IR': 'Insulin Receptor',
     'mPDK1': 'Source Defined MPDK1 State',
     'tRas': 'Source Defined TRAS State',
     'tRas_PI3K': 'Tras PI3K',
     'ppAkt': 'Pp AKT',
     'mGABp_RasGAP': 'Mgabp RAS GAP',
     'amTOR': 'Am TOR',
     'iGS': 'Source Defined IGS State',
     'imGAB': 'Im GAB',
     'imIRS': 'Im IRS',
     'aSrc': 'Source Defined ASRC State',
     'Ri': 'Source Defined RI State',
     'IRi': 'Internalized Insulin Receptor',
     'iPX': 'Source Defined IPX State',
     'aPX': 'Source Defined APX State',
     'aPX_GS': 'APX GS',
     'IRSp_PI3K': 'Irsp PI3K',
     'IRSp_GS': 'Irsp GS',
     'IRSp_SHP2': 'Irsp SHP2',
     'GABp': 'Source Defined GABP State',
     'GABp_PI3K': 'Gabp PI3K',
     'GABp_GS': 'Gabp GS',
     'GABp_RasGAP': 'Gabp RAS GAP',
     'GABp_SHP2': 'Gabp SHP2',
     'GABp_pSHP2': 'Gabp PSHP2',
     'GABp_pSHP2_GS': 'Gabp PSHP2 GS',
     'imGABp': 'Im Gabp',
     'bRasGAP': 'Bras GAP',
     'phosphorylated_Akt': 'Phosphorylated AKT'}
    _STATE_OUTPUT_ALIASES = {'EGF': 'egf',
     'I': 'source_defined_i_state',
     'RE': 'source_defined_re_state',
     'Rd': 'source_defined_rd_state',
     'Rp': 'source_defined_rp_state',
     'GS': 'source_defined_gs_state',
     'Rp_GS': 'source_defined_rp_gs_state',
     'Shc': 'shc_adapter_protein_adapter_protein_adapter_protein_adapter_protein_adapter_protein_adapter_protein',
     'Rp_Shc': 'rp_shc_adapter_protein_adapter_protein_adapter_protein_adapter_protein_adapter_protein_adapter_protein',
     'Rp_pShc': 'rp_phospho_shc_adapter_protein_adapter_protein_adapter_protein_adapter_protein_adapter_protein_adapter_protein',
     'pShc': 'phospho_shc_adapter_protein_adapter_protein_adapter_protein_adapter_protein_adapter_protein_adapter_protein',
     'Rp_pShc_GS': 'rp_phospho_shc_adapter_protein_adapter_protein_adapter_protein_adapter_protein_adapter_protein_adapter_protein_gs',
     'PI3K': 'pi3k',
     'Rp_PI3K': 'rp_pi3k',
     'RasGAP': 'ras_gap',
     'Rp_RasGAP': 'rp_ras_gap',
     'IRL': 'source_defined_irl_state',
     'IRp': 'phosphorylated_insulin_receptor',
     'IRp_PI3K': 'phosphorylated_insulin_receptor_pi3k',
     'IRp_RasGAP': 'phosphorylated_insulin_receptor_ras_gap',
     'IRS': 'irs',
     'IRp_IRS': 'phosphorylated_insulin_receptor_irs',
     'IRp_IRSp': 'phosphorylated_insulin_receptor_irsp',
     'IRSp': 'source_defined_irsp_state',
     'iSrc': 'source_defined_isrc_state',
     'mIRS': 'source_defined_mirs_state',
     'mIRSp': 'mirsp',
     'mIRSp_GS': 'mirsp_gs',
     'mIRSp_PI3K': 'mirsp_pi3k',
     'SHP2': 'source_defined_shp2_state',
     'mIRSp_SHP2': 'mirsp_shp2',
     'GAB': 'source_defined_gab_state',
     'mGAB': 'source_defined_mgab_state',
     'mGABp': 'mgabp',
     'mGABp_GS': 'mgabp_gs',
     'mGABp_PI3K': 'mgabp_pi3k',
     'mGABp_SHP2': 'mgabp_shp2',
     'mGABp_pSHP2': 'mgabp_pshp2',
     'PIP3': 'source_defined_phosphorylated_ip3_state',
     'dRas': 'source_defined_dras_state',
     'Raf': 'raf',
     'aRaf': 'source_defined_araf_state',
     'Mek': 'mek',
     'Erk': 'erk',
     'pErk': 'phospho_erk',
     'PDK1': 'source_defined_pdk1_state',
     'Akt': 'akt',
     'pAkt': 'phospho_akt',
     'mTOR': 'mtor',
     'Null': 'source_defined_null_state',
     'aaRaf': 'aa_raf',
     'PKA': 'source_defined_pka_state',
     'pShc_GS': 'phospho_shc_adapter_protein_adapter_protein_adapter_protein_adapter_protein_adapter_protein_adapter_protein_gs',
     'ppMek': 'pp_mek',
     'mGABp_pSHP2_GS': 'mgabp_pshp2_gs',
     'R': 'source_defined_r_state',
     'ppErk': 'pp_erk',
     'IR': 'insulin_receptor',
     'mPDK1': 'source_defined_mpdk1_state',
     'tRas': 'source_defined_tras_state',
     'tRas_PI3K': 'tras_pi3k',
     'ppAkt': 'pp_akt',
     'mGABp_RasGAP': 'mgabp_ras_gap',
     'amTOR': 'am_tor',
     'iGS': 'source_defined_igs_state',
     'imGAB': 'im_gab',
     'imIRS': 'im_irs',
     'aSrc': 'source_defined_asrc_state',
     'Ri': 'source_defined_ri_state',
     'IRi': 'internalized_insulin_receptor',
     'iPX': 'source_defined_ipx_state',
     'aPX': 'source_defined_apx_state',
     'aPX_GS': 'apx_gs',
     'IRSp_PI3K': 'irsp_pi3k',
     'IRSp_GS': 'irsp_gs',
     'IRSp_SHP2': 'irsp_shp2',
     'GABp': 'source_defined_gabp_state',
     'GABp_PI3K': 'gabp_pi3k',
     'GABp_GS': 'gabp_gs',
     'GABp_RasGAP': 'gabp_ras_gap',
     'GABp_SHP2': 'gabp_shp2',
     'GABp_pSHP2': 'gabp_pshp2',
     'GABp_pSHP2_GS': 'gabp_pshp2_gs',
     'imGABp': 'im_gabp',
     'bRasGAP': 'bras_gap',
     'phosphorylated_Akt': 'phosphorylated_akt'}

    def __init__(self, model_path: str = 'data/BIOMD0000000223.xml', integration_step: float = 0.01) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


Borisov2009EgfInsulinCrosstalkBiomd0000000223Model = Borisov2009EgfInsulinCrosstalkModel
