# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML wrapper for Chang2008 - ERK activation, hallucinogenic drugs mediated signalling through serotonin receptors."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Chang2008ErkActivationHallucinogenicDrugsMeModel(TelluriumSBMLBioModule):
    """Faithful Tellurium execution of the bundled SBML source model."""

    _SBML_ID = 'MODEL0975191032'
    _TITLE = 'Chang2008 - ERK activation, hallucinogenic drugs mediated signalling through serotonin receptors'
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _HEADLINE_OUTPUTS = {'cpx_erk_pp_mkp_pp': ('cpxERK_PP_MKP_PP',
                           'mole',
                           'Cpx ERK PP MKP PP. Maps to SBML symbol `cpxERK_PP_MKP_PP` and is emitted '
                           'in native SBML units.'),
     'cpx_erkp_mkp_pp': ('cpxERKP_MKP_PP',
                         'mole',
                         'Cpx ERKP MKP PP. Maps to SBML symbol `cpxERKP_MKP_PP` and is emitted in '
                         'native SBML units.'),
     'active_erk_mkp_phosphatase_complex': ('cpxERKP_MKP_PPstar',
                                            'mole',
                                            'active ERK-MKP phosphatase complex. Maps to SBML symbol '
                                            '`cpxERKP_MKP_PPstar` and is emitted in native SBML '
                                            'units.')}
    _INITIAL_CONDITION_INPUTS = {'initial_source_defined_pip2_state': ('PIP2',
                                           2.6578,
                                           'mole',
                                           'Initial level of source-defined PIP2 state. Maps to SBML '
                                           'symbol `PIP2`; exposed as a traceable initial-condition '
                                           'perturbation.')}
    _PARAMETER_INPUTS = {}
    _SPECIES_LABELS = {'TCB': 'source-defined TCB state',
     'cpxERK_PP_MKP_PP': 'Cpx ERK PP MKP PP',
     'cpxERKP_MKP_PP': 'Cpx ERKP MKP PP',
     'cpxERKP_MKP_PPstar': 'active ERK-MKP phosphatase complex',
     'Rafstarstar': 'Rafstarstar',
     'cpxMEKPP_PP2A': 'Cpx MEKPP PP2A',
     'cpxRafstarstar_PP2A': 'Cpx Rafstarstar PP2A',
     'cpxERKPP_Rafstar': 'Cpx ERKPP Rafstar',
     'cpxRafstar_PP2A': 'Cpx Rafstar PP2A',
     'ERK_PP': 'ERK PP',
     'cpxERKP_MEKPP': 'Cpx ERKP MEKPP',
     'cpxERK_MEK_PP': 'Cpx ERK MEK PP',
     'MEK_PP': 'MEK PP',
     'cpxERK_MKP_PP': 'Cpx ERK MKP PP',
     'MKP': 'source-defined MKP state',
     'PLA2star_Ca': 'Pla2star calcium',
     'PLA2_Ca': 'PLA2 calcium',
     'cpxERKPP_MKP': 'Cpx ERKPP MKP',
     'PLA2star': 'Pla2star',
     'cpxERKPP_PLA2star': 'Cpx ERKPP Pla2star',
     'Ca': 'calcium',
     'PLA2': 'source-defined PLA2 state',
     'MKP_PP': 'MKP PP',
     'ERK_P': 'source-defined ERK_P state',
     'ERK': 'ERK',
     'cpxMEKP_Rafstar': 'Cpx MEKP Rafstar',
     'cpxMEKP_PP2A': 'Cpx MEKP PP2A',
     'PP2A': 'PP2A',
     'MEK_P': 'source-defined MEK_P state',
     'cpxMEK_Rafstar': 'Cpx MEK Rafstar',
     'MEK': 'MEK',
     'Rafstar': 'Rafstar',
     'cpxRasGTP_Raf': 'Cpx RAS GTP RAF',
     'Raf': 'RAF',
     'RasGTP': 'RAS GTP',
     'RasGAP': 'RAS GAP',
     'RasGDP': 'RAS GDP',
     'PIP2': 'source-defined PIP2 state',
     'Pi': 'source-defined PI state',
     'RGS4': 'source-defined RGS4 state',
     'cpxRGS4_Gq_a_GTP': 'Cpx RGS4 Gq A GTP',
     'cpxA_2AR_Gq': 'Cpx A 2AR Gq',
     'cpx2AR_Gqtrimer': 'Cpx2ar Gqtrimer',
     'ht2AR': 'Ht2ar',
     'ht2AR_internal': 'Ht2ar Internal',
     'A_2AR_i_deg': 'A 2AR I Deg',
     'cpxA_2AR_internal': 'Cpx A 2AR Internal',
     'cpxA_2AR': 'Cpx A 2AR',
     'Gq_trimer': 'Gq Trimer',
     'Gq_a_GTP': 'Gq A GTP',
     'Gq_betagamma': 'Gq Betagamma',
     'Gq_a_GDP': 'Gq A GDP',
     'PLCb': 'source-defined PLCB state',
     'PLCb_Gq_a_GTP': 'Plcb Gq A GTP',
     'PLCb_Ca': 'Plcb calcium',
     'PLCb_Ca_Gq_a_GTP': 'Plcb calcium Gq A GTP',
     'IP3': 'IP3',
     'DAG': 'DAG',
     'PKC': 'PKC',
     'PKC_Ca': 'PKC calcium',
     'PKC_DAG': 'PKC DAG',
     'PKC_DAG_AA': 'PKC DAG AA',
     'APC': 'source-defined APC state',
     'AA': 'source-defined AA state',
     'PKC_Ca_AA': 'PKC calcium AA',
     'PKC_AA': 'PKC AA',
     'PIP2_PLA2_Ca': 'PIP2 PLA2 calcium',
     'RasGEF': 'RAS GEF',
     'RasGEF_star': 'RAS GEF Star',
     'RasGAP_star': 'RAS GAP Star',
     'PIP2_PLA2': 'PIP2 PLA2',
     'PKC_Ca_DAG': 'PKC calcium DAG',
     'PKC_Ca_DAGactive': 'PKC calcium Dagactive',
     'PKC_DAG_AAactive_1': 'PKC DAG Aaactive',
     'PA': 'source-defined PA state',
     'PI': 'source-defined PI state',
     'PIP': 'source-defined PIP state',
     'PI3K': 'PI3K',
     'Gi_br_PI3K': 'Gi Br PI3K',
     'PI3Kstar': 'Pi3kstar',
     'PIP2_PI3Kstar': 'PIP2 Pi3kstar',
     'PIP3': 'source-defined PIP3 state',
     'Src': 'source-defined SRC state',
     'cpxSrc_PIP3': 'Cpx Src phosphorylated IP3',
     'Src_star': 'Src Star',
     'Csk': 'source-defined CSK state',
     'cpxCsk_Srcstar': 'Cpx Csk Srcstar',
     'PTEN': 'source-defined PTEN state',
     'cpxPTEN_PIP3': 'Cpx PTEN phosphorylated IP3',
     'cpxA_HT1AR_internal': 'Cpx A HT1AR Internal',
     'A_HT1R_i_deg': 'A HT1R I Deg',
     'HT1AR_internal': 'HT1AR Internal',
     'HT1AR': 'HT1AR',
     'cpxA_HT1AR': 'Cpx A HT1AR',
     'Gitrimer': 'Gitrimer',
     'cpxHT1AR_Gitrimer': 'Cpx HT1AR Gitrimer',
     'cpxA_R1A_Gi': 'Cpx A R1A Gi',
     'Gi_betagamma': 'Gi Betagamma',
     'Gi_a_GTP': 'Gi A GTP',
     'Gi_a_GDP': 'Gi A GDP',
     'cpxRGS4_Gi_a_GTP_1': 'Cpx RGS4 Gi A GTP 1',
     'RGS4_1': 'RGS4 1',
     'Shc': 'Shc adapter protein',
     'serotonin': 'Serotonin',
     'Grb2': 'Grb2 adapter protein',
     'Sos': 'SOS guanine-nucleotide exchange factor',
     'Shc_star': 'Shc adapter protein Star',
     'Shcstar_Grb2': 'Shcstar Grb2 adapter protein',
     'Grb2_sos': 'Grb2 adapter protein SOS guanine-nucleotide exchange factor',
     'Shcstar_Grb2_Sos': 'Shcstar Grb2 adapter protein SOS guanine-nucleotide exchange factor',
     'cpxRasGDP_Shcstar_Grb2_Sos': 'Cpx RAS GDP Shcstar Grb2 adapter protein SOS guanine-nucleotide '
                                   'exchange factor',
     'Grb2_sos_P': 'Grb2 adapter protein SOS guanine-nucleotide exchange factor P',
     'Ketanserin': 'Ketanserin',
     'cpxKetanserin_2AR': 'Cpx Ketanserin 2AR',
     'cpxKetanserin_2ARGq': 'Cpx Ketanserin 2argq',
     'productX': 'Product X'}
    _STATE_OUTPUT_ALIASES = {'TCB': 'source_defined_tcb_state',
     'cpxERK_PP_MKP_PP': 'cpx_erk_pp_mkp_pp',
     'cpxERKP_MKP_PP': 'cpx_erkp_mkp_pp',
     'cpxERKP_MKP_PPstar': 'active_erk_mkp_phosphatase_complex',
     'Rafstarstar': 'rafstarstar',
     'cpxMEKPP_PP2A': 'cpx_mekpp_pp2a',
     'cpxRafstarstar_PP2A': 'cpx_rafstarstar_pp2a',
     'cpxERKPP_Rafstar': 'cpx_erkpp_rafstar',
     'cpxRafstar_PP2A': 'cpx_rafstar_pp2a',
     'ERK_PP': 'erk_pp',
     'cpxERKP_MEKPP': 'cpx_erkp_mekpp',
     'cpxERK_MEK_PP': 'cpx_erk_mek_pp',
     'MEK_PP': 'mek_pp',
     'cpxERK_MKP_PP': 'cpx_erk_mkp_pp',
     'MKP': 'source_defined_mkp_state',
     'PLA2star_Ca': 'pla2star_calcium',
     'PLA2_Ca': 'pla2_calcium',
     'cpxERKPP_MKP': 'cpx_erkpp_mkp',
     'PLA2star': 'pla2star',
     'cpxERKPP_PLA2star': 'cpx_erkpp_pla2star',
     'Ca': 'calcium',
     'PLA2': 'source_defined_pla2_state',
     'MKP_PP': 'mkp_pp',
     'ERK_P': 'source_defined_erk_p_state',
     'ERK': 'erk',
     'cpxMEKP_Rafstar': 'cpx_mekp_rafstar',
     'cpxMEKP_PP2A': 'cpx_mekp_pp2a',
     'PP2A': 'pp2a',
     'MEK_P': 'source_defined_mek_p_state',
     'cpxMEK_Rafstar': 'cpx_mek_rafstar',
     'MEK': 'mek',
     'Rafstar': 'rafstar',
     'cpxRasGTP_Raf': 'cpx_ras_gtp_raf',
     'Raf': 'raf',
     'RasGTP': 'ras_gtp',
     'RasGAP': 'ras_gap',
     'RasGDP': 'ras_gdp',
     'PIP2': 'source_defined_pip2_state',
     'Pi': 'source_defined_pi_state',
     'RGS4': 'source_defined_rgs4_state',
     'cpxRGS4_Gq_a_GTP': 'cpx_rgs4_gq_a_gtp',
     'cpxA_2AR_Gq': 'cpx_a_2ar_gq',
     'cpx2AR_Gqtrimer': 'cpx2ar_gqtrimer',
     'ht2AR': 'ht2ar',
     'ht2AR_internal': 'ht2ar_internal',
     'A_2AR_i_deg': 'a_2ar_i_deg',
     'cpxA_2AR_internal': 'cpx_a_2ar_internal',
     'cpxA_2AR': 'cpx_a_2ar',
     'Gq_trimer': 'gq_trimer',
     'Gq_a_GTP': 'gq_a_gtp',
     'Gq_betagamma': 'gq_betagamma',
     'Gq_a_GDP': 'gq_a_gdp',
     'PLCb': 'source_defined_plcb_state',
     'PLCb_Gq_a_GTP': 'plcb_gq_a_gtp',
     'PLCb_Ca': 'plcb_calcium',
     'PLCb_Ca_Gq_a_GTP': 'plcb_calcium_gq_a_gtp',
     'IP3': 'ip3',
     'DAG': 'dag',
     'PKC': 'pkc',
     'PKC_Ca': 'pkc_calcium',
     'PKC_DAG': 'pkc_dag',
     'PKC_DAG_AA': 'pkc_dag_aa',
     'APC': 'source_defined_apc_state',
     'AA': 'source_defined_aa_state',
     'PKC_Ca_AA': 'pkc_calcium_aa',
     'PKC_AA': 'pkc_aa',
     'PIP2_PLA2_Ca': 'pip2_pla2_calcium',
     'RasGEF': 'ras_gef',
     'RasGEF_star': 'ras_gef_star',
     'RasGAP_star': 'ras_gap_star',
     'PIP2_PLA2': 'pip2_pla2',
     'PKC_Ca_DAG': 'pkc_calcium_dag',
     'PKC_Ca_DAGactive': 'pkc_calcium_dagactive',
     'PKC_DAG_AAactive_1': 'pkc_dag_aaactive',
     'PA': 'source_defined_pa_state',
     'PI': 'source_defined_pi_state_2',
     'PIP': 'source_defined_pip_state',
     'PI3K': 'pi3k',
     'Gi_br_PI3K': 'gi_br_pi3k',
     'PI3Kstar': 'pi3kstar',
     'PIP2_PI3Kstar': 'pip2_pi3kstar',
     'PIP3': 'source_defined_pip3_state',
     'Src': 'source_defined_src_state',
     'cpxSrc_PIP3': 'cpx_src_phosphorylated_ip3',
     'Src_star': 'src_star',
     'Csk': 'source_defined_csk_state',
     'cpxCsk_Srcstar': 'cpx_csk_srcstar',
     'PTEN': 'source_defined_pten_state',
     'cpxPTEN_PIP3': 'cpx_pten_phosphorylated_ip3',
     'cpxA_HT1AR_internal': 'cpx_a_ht1ar_internal',
     'A_HT1R_i_deg': 'a_ht1r_i_deg',
     'HT1AR_internal': 'ht1ar_internal',
     'HT1AR': 'ht1ar',
     'cpxA_HT1AR': 'cpx_a_ht1ar',
     'Gitrimer': 'gitrimer',
     'cpxHT1AR_Gitrimer': 'cpx_ht1ar_gitrimer',
     'cpxA_R1A_Gi': 'cpx_a_r1a_gi',
     'Gi_betagamma': 'gi_betagamma',
     'Gi_a_GTP': 'gi_a_gtp',
     'Gi_a_GDP': 'gi_a_gdp',
     'cpxRGS4_Gi_a_GTP_1': 'cpx_rgs4_gi_a_gtp_1',
     'RGS4_1': 'rgs4_1',
     'Shc': 'shc_adapter_protein',
     'serotonin': 'serotonin',
     'Grb2': 'grb2_adapter_protein',
     'Sos': 'sos_guanine_nucleotide_exchange_factor',
     'Shc_star': 'shc_adapter_protein_star',
     'Shcstar_Grb2': 'shcstar_grb2_adapter_protein',
     'Grb2_sos': 'grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor',
     'Shcstar_Grb2_Sos': 'shcstar_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor',
     'cpxRasGDP_Shcstar_Grb2_Sos': 'cpx_ras_gdp_shcstar_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor',
     'Grb2_sos_P': 'grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_p',
     'Ketanserin': 'ketanserin',
     'cpxKetanserin_2AR': 'cpx_ketanserin_2ar',
     'cpxKetanserin_2ARGq': 'cpx_ketanserin_2argq',
     'productX': 'product_x'}

    def __init__(self, model_path: str = 'data/MODEL0975191032.xml', integration_step: float = 0.01) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


Chang2008ErkActivationHallucinogenicDrugsMeModel0975191032Model = Chang2008ErkActivationHallucinogenicDrugsMeModel
