# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML wrapper for Li2019 - Neurogranin stimulates Ca/calmodulin-dependent kinase II by inhibiting Calcineurin."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Li2019NeurograninStimulatesCaCalmodulinDepeModel(TelluriumSBMLBioModule):
    """Faithful Tellurium execution of the bundled SBML source model."""

    _SBML_ID = 'MODEL1903010001'
    _TITLE = 'Li2019 - Neurogranin stimulates Ca/calmodulin-dependent kinase II by inhibiting Calcineurin'
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _HEADLINE_OUTPUTS = {'calcium_m_rr_0_0': ('cam_RR_0_0',
                          'substance',
                          'calcium M RR 0 0. Maps to SBML symbol `cam_RR_0_0` and is emitted in native '
                          'SBML units.'),
     'calcium_m_rr_0_calcium_nca4': ('cam_RR_0_PP2BCa2',
                                     'substance',
                                     'calcium M RR 0 calcium Nca4. Maps to SBML symbol '
                                     '`cam_RR_0_PP2BCa2` and is emitted in native SBML units.'),
     'calcium_m_rr_0_calcium_mkii': ('cam_RR_0_CaMKII',
                                     'substance',
                                     'calcium M RR 0 calcium MKII. Maps to SBML symbol '
                                     '`cam_RR_0_CaMKII` and is emitted in native SBML units.')}
    _INITIAL_CONDITION_INPUTS = {}
    _PARAMETER_INPUTS = {'initial_kd_calcium_n_ca2_calcium_level': ('parameter_6',
                                                1.76e-08,
                                                'native SBML value',
                                                'Kd calcium N Ca2 calcium source parameter. Maps to '
                                                'SBML symbol `parameter_6` and preserves the bundled '
                                                'default.'),
     'initial_kd_calcium_n_rr_level': ('Kd_PP2BCa2_RR',
                                       3.26e-09,
                                       'native SBML value',
                                       'Kd calcium N RR source parameter. Maps to SBML symbol '
                                       '`Kd_PP2BCa2_RR` and preserves the bundled default.'),
     'initial_kon_calcium_n_rr_level': ('kon_PP2BCa2',
                                        23000000.0,
                                        'native SBML value',
                                        'Kon calcium N RR source parameter. Maps to SBML symbol '
                                        '`kon_PP2BCa2` and preserves the bundled default.')}
    _SPECIES_LABELS = {'cam_RR_0_0': 'calcium M RR 0 0',
     'cam_RR_0_PP2BCa2': 'calcium M RR 0 calcium Nca4',
     'cam_RR_0_CaMKII': 'calcium M RR 0 calcium MKII',
     'cam_RR_0_CaMKIIp': 'calcium M RR 0 calcium Mkiip',
     'cam_RR_A_0': 'calcium M RR A 0',
     'cam_RR_A_PP2BCa2': 'calcium M RR A calcium Nca4',
     'cam_RR_A_CaMKII': 'calcium M RR A calcium MKII',
     'cam_RR_A_CaMKIIp': 'calcium M RR A calcium Mkiip',
     'cam_RR_B_0': 'calcium M RR B 0',
     'cam_RR_B_PP2BCa2': 'calcium M RR B calcium Nca4',
     'cam_RR_B_CaMKII': 'calcium M RR B calcium MKII',
     'cam_RR_B_CaMKIIp': 'calcium M RR B calcium Mkiip',
     'cam_RR_C_0': 'calcium M RR C 0',
     'cam_RR_C_PP2BCa2': 'calcium M RR C calcium Nca4',
     'cam_RR_C_CaMKII': 'calcium M RR C calcium MKII',
     'cam_RR_C_CaMKIIp': 'calcium M RR C calcium Mkiip',
     'cam_RR_D_0': 'calcium M RR D 0',
     'cam_RR_D_PP2BCa2': 'calcium M RR D calcium Nca4',
     'cam_RR_D_CaMKII': 'calcium M RR D calcium MKII',
     'cam_RR_D_CaMKIIp': 'calcium M RR D calcium Mkiip',
     'cam_RR_AB_0': 'calcium M RR Ab 0',
     'cam_RR_AB_PP2BCa2': 'calcium M RR Ab calcium Nca4',
     'cam_RR_AB_CaMKII': 'calcium M RR Ab calcium MKII',
     'cam_RR_AB_CaMKIIp': 'calcium M RR Ab calcium Mkiip',
     'cam_RR_AC_0': 'calcium M RR Ac 0',
     'cam_RR_AC_PP2BCa2': 'calcium M RR Ac calcium Nca4',
     'cam_RR_AC_CaMKII': 'calcium M RR Ac calcium MKII',
     'cam_RR_AC_CaMKIIp': 'calcium M RR Ac calcium Mkiip',
     'cam_RR_AD_0': 'calcium M RR Ad 0',
     'cam_RR_AD_PP2BCa2': 'calcium M RR Ad calcium Nca4',
     'cam_RR_AD_CaMKII': 'calcium M RR Ad calcium MKII',
     'cam_RR_AD_CaMKIIp': 'calcium M RR Ad calcium Mkiip',
     'cam_RR_BC_0': 'calcium M RR Bc 0',
     'cam_RR_BC_PP2BCa2': 'calcium M RR Bc calcium Nca4',
     'cam_RR_BC_CaMKII': 'calcium M RR Bc calcium MKII',
     'cam_RR_BC_CaMKIIp': 'calcium M RR Bc calcium Mkiip',
     'cam_RR_BD_0': 'calcium M RR Bd 0',
     'cam_RR_BD_PP2BCa2': 'calcium M RR Bd calcium Nca4',
     'cam_RR_BD_CaMKII': 'calcium M RR Bd calcium MKII',
     'cam_RR_BD_CaMKIIp': 'calcium M RR Bd calcium Mkiip',
     'cam_RR_CD_0': 'calcium M RR Cd 0',
     'cam_RR_CD_PP2BCa2': 'calcium M RR Cd calcium Nca4',
     'cam_RR_CD_CaMKII': 'calcium M RR Cd calcium MKII',
     'cam_RR_CD_CaMKIIp': 'calcium M RR Cd calcium Mkiip',
     'cam_RR_ABC_0': 'calcium M RR Abc 0',
     'cam_RR_ABC_PP2BCa2': 'calcium M RR Abc calcium Nca4',
     'cam_RR_ABC_CaMKII': 'calcium M RR Abc calcium MKII',
     'cam_RR_ABC_CaMKIIp': 'calcium M RR Abc calcium Mkiip',
     'cam_RR_ABD_0': 'calcium M RR Abd 0',
     'cam_RR_ABD_PP2BCa2': 'calcium M RR Abd calcium Nca4',
     'cam_RR_ABD_CaMKII': 'calcium M RR Abd calcium MKII',
     'cam_RR_ABD_CaMKIIp': 'calcium M RR Abd calcium Mkiip',
     'cam_RR_ACD_0': 'calcium M RR Acd 0',
     'cam_RR_ACD_PP2BCa2': 'calcium M RR Acd calcium Nca4',
     'cam_RR_ACD_CaMKII': 'calcium M RR Acd calcium MKII',
     'cam_RR_ACD_CaMKIIp': 'calcium M RR Acd calcium Mkiip',
     'cam_RR_BCD_0': 'calcium M RR Bcd 0',
     'cam_RR_BCD_PP2BCa2': 'calcium M RR Bcd calcium Nca4',
     'cam_RR_BCD_CaMKII': 'calcium M RR Bcd calcium MKII',
     'cam_RR_BCD_CaMKIIp': 'calcium M RR Bcd calcium Mkiip',
     'cam_RR_ABCD_0': 'calcium M RR Abcd 0',
     'cam_RR_ABCD_PP2BCa2': 'calcium M RR Abcd calcium Nca4',
     'cam_RR_ABCD_CaMKII': 'calcium M RR Abcd calcium MKII',
     'cam_RR_ABCD_CaMKIIp': 'calcium M RR Abcd calcium Mkiip',
     'cam_RT_0_0': 'calcium M RT 0 0',
     'cam_RT_0_Ng': 'calcium M RT 0 Ng',
     'cam_RT_A_0': 'calcium M RT A 0',
     'cam_RT_A_Ng': 'calcium M RT A Ng',
     'cam_RT_B_0': 'calcium M RT B 0',
     'cam_RT_B_Ng': 'calcium M RT B Ng',
     'cam_RT_C_0': 'calcium M RT C 0',
     'cam_RT_C_Ng': 'calcium M RT C Ng',
     'cam_RT_D_0': 'calcium M RT D 0',
     'cam_RT_D_Ng': 'calcium M RT D Ng',
     'cam_RT_AB_0': 'calcium M RT Ab 0',
     'cam_RT_AB_Ng': 'calcium M RT Ab Ng',
     'cam_RT_AC_0': 'calcium M RT Ac 0',
     'cam_RT_AC_Ng': 'calcium M RT Ac Ng',
     'cam_RT_AD_0': 'calcium M RT Ad 0',
     'cam_RT_AD_Ng': 'calcium M RT Ad Ng',
     'cam_RT_BC_0': 'calcium M RT Bc 0',
     'cam_RT_BC_Ng': 'calcium M RT Bc Ng',
     'cam_RT_BD_0': 'calcium M RT Bd 0',
     'cam_RT_BD_Ng': 'calcium M RT Bd Ng',
     'cam_RT_CD_0': 'calcium M RT Cd 0',
     'cam_RT_CD_Ng': 'calcium M RT Cd Ng',
     'cam_RT_ABC_0': 'calcium M RT Abc 0',
     'cam_RT_ABC_Ng': 'calcium M RT Abc Ng',
     'cam_RT_ABD_0': 'calcium M RT Abd 0',
     'cam_RT_ABD_Ng': 'calcium M RT Abd Ng',
     'cam_RT_ACD_0': 'calcium M RT Acd 0',
     'cam_RT_ACD_Ng': 'calcium M RT Acd Ng',
     'cam_RT_BCD_0': 'calcium M RT Bcd 0',
     'cam_RT_BCD_Ng': 'calcium M RT Bcd Ng',
     'cam_RT_ABCD_0': 'calcium M RT Abcd 0',
     'cam_RT_ABCD_Ng': 'calcium M RT Abcd Ng',
     'cam_TR_0_0': 'calcium M TR 0 0',
     'cam_TR_A_0': 'calcium M TR A 0',
     'cam_TR_B_0': 'calcium M TR B 0',
     'cam_TR_C_0': 'calcium M TR C 0',
     'cam_TR_D_0': 'calcium M TR D 0',
     'cam_TR_AB_0': 'calcium M TR Ab 0',
     'cam_TR_AC_0': 'calcium M TR Ac 0',
     'cam_TR_AD_0': 'calcium M TR Ad 0',
     'cam_TR_BC_0': 'calcium M TR Bc 0',
     'cam_TR_BD_0': 'calcium M TR Bd 0',
     'cam_TR_CD_0': 'calcium M TR Cd 0',
     'cam_TR_ABC_0': 'calcium M TR Abc 0',
     'cam_TR_ABD_0': 'calcium M TR Abd 0',
     'cam_TR_ACD_0': 'calcium M TR Acd 0',
     'cam_TR_BCD_0': 'calcium M TR Bcd 0',
     'cam_TR_ABCD_0': 'calcium M TR Abcd 0',
     'cam_TT_0_0': 'calcium M TT 0 0',
     'cam_TT_0_Ng': 'calcium M TT 0 Ng',
     'cam_TT_A_0': 'calcium M TT A 0',
     'cam_TT_A_Ng': 'calcium M TT A Ng',
     'cam_TT_B_0': 'calcium M TT B 0',
     'cam_TT_B_Ng': 'calcium M TT B Ng',
     'cam_TT_C_0': 'calcium M TT C 0',
     'cam_TT_C_Ng': 'calcium M TT C Ng',
     'cam_TT_D_0': 'calcium M TT D 0',
     'cam_TT_D_Ng': 'calcium M TT D Ng',
     'cam_TT_AB_0': 'calcium M TT Ab 0',
     'cam_TT_AB_Ng': 'calcium M TT Ab Ng',
     'cam_TT_AC_0': 'calcium M TT Ac 0',
     'cam_TT_AC_Ng': 'calcium M TT Ac Ng',
     'cam_TT_AD_0': 'calcium M TT Ad 0',
     'cam_TT_AD_Ng': 'calcium M TT Ad Ng',
     'cam_TT_BC_0': 'calcium M TT Bc 0',
     'cam_TT_BC_Ng': 'calcium M TT Bc Ng',
     'cam_TT_BD_0': 'calcium M TT Bd 0',
     'cam_TT_BD_Ng': 'calcium M TT Bd Ng',
     'cam_TT_CD_0': 'calcium M TT Cd 0',
     'cam_TT_CD_Ng': 'calcium M TT Cd Ng',
     'cam_TT_ABC_0': 'calcium M TT Abc 0',
     'cam_TT_ABC_Ng': 'calcium M TT Abc Ng',
     'cam_TT_ABD_0': 'calcium M TT Abd 0',
     'cam_TT_ABD_Ng': 'calcium M TT Abd Ng',
     'cam_TT_ACD_0': 'calcium M TT Acd 0',
     'cam_TT_ACD_Ng': 'calcium M TT Acd Ng',
     'cam_TT_BCD_0': 'calcium M TT Bcd 0',
     'cam_TT_BCD_Ng': 'calcium M TT Bcd Ng',
     'cam_TT_ABCD_0': 'calcium M TT Abcd 0',
     'cam_TT_ABCD_Ng': 'calcium M TT Abcd Ng',
     'ca': 'calcium',
     'Ng': 'source-defined NG state',
     'PP2BCa2': 'calcium Nca4',
     'CaMKII': 'calcium MKII',
     'CaMKIIp': 'calcium Mkiip',
     'species_2': 'calcium Nca3',
     'PP2Bi': 'source-defined CAN state',
     'PP2BiCa1': 'calcium nuclear calcium',
     'PP2BiCa2': 'calcium Nca2'}
    _STATE_OUTPUT_ALIASES = {'cam_RR_0_0': 'calcium_m_rr_0_0',
     'cam_RR_0_PP2BCa2': 'calcium_m_rr_0_calcium_nca4',
     'cam_RR_0_CaMKII': 'calcium_m_rr_0_calcium_mkii',
     'cam_RR_0_CaMKIIp': 'calcium_m_rr_0_calcium_mkiip',
     'cam_RR_A_0': 'calcium_m_rr_a_0',
     'cam_RR_A_PP2BCa2': 'calcium_m_rr_a_calcium_nca4',
     'cam_RR_A_CaMKII': 'calcium_m_rr_a_calcium_mkii',
     'cam_RR_A_CaMKIIp': 'calcium_m_rr_a_calcium_mkiip',
     'cam_RR_B_0': 'calcium_m_rr_b_0',
     'cam_RR_B_PP2BCa2': 'calcium_m_rr_b_calcium_nca4',
     'cam_RR_B_CaMKII': 'calcium_m_rr_b_calcium_mkii',
     'cam_RR_B_CaMKIIp': 'calcium_m_rr_b_calcium_mkiip',
     'cam_RR_C_0': 'calcium_m_rr_c_0',
     'cam_RR_C_PP2BCa2': 'calcium_m_rr_c_calcium_nca4',
     'cam_RR_C_CaMKII': 'calcium_m_rr_c_calcium_mkii',
     'cam_RR_C_CaMKIIp': 'calcium_m_rr_c_calcium_mkiip',
     'cam_RR_D_0': 'calcium_m_rr_d_0',
     'cam_RR_D_PP2BCa2': 'calcium_m_rr_d_calcium_nca4',
     'cam_RR_D_CaMKII': 'calcium_m_rr_d_calcium_mkii',
     'cam_RR_D_CaMKIIp': 'calcium_m_rr_d_calcium_mkiip',
     'cam_RR_AB_0': 'calcium_m_rr_ab_0',
     'cam_RR_AB_PP2BCa2': 'calcium_m_rr_ab_calcium_nca4',
     'cam_RR_AB_CaMKII': 'calcium_m_rr_ab_calcium_mkii',
     'cam_RR_AB_CaMKIIp': 'calcium_m_rr_ab_calcium_mkiip',
     'cam_RR_AC_0': 'calcium_m_rr_ac_0',
     'cam_RR_AC_PP2BCa2': 'calcium_m_rr_ac_calcium_nca4',
     'cam_RR_AC_CaMKII': 'calcium_m_rr_ac_calcium_mkii',
     'cam_RR_AC_CaMKIIp': 'calcium_m_rr_ac_calcium_mkiip',
     'cam_RR_AD_0': 'calcium_m_rr_ad_0',
     'cam_RR_AD_PP2BCa2': 'calcium_m_rr_ad_calcium_nca4',
     'cam_RR_AD_CaMKII': 'calcium_m_rr_ad_calcium_mkii',
     'cam_RR_AD_CaMKIIp': 'calcium_m_rr_ad_calcium_mkiip',
     'cam_RR_BC_0': 'calcium_m_rr_bc_0',
     'cam_RR_BC_PP2BCa2': 'calcium_m_rr_bc_calcium_nca4',
     'cam_RR_BC_CaMKII': 'calcium_m_rr_bc_calcium_mkii',
     'cam_RR_BC_CaMKIIp': 'calcium_m_rr_bc_calcium_mkiip',
     'cam_RR_BD_0': 'calcium_m_rr_bd_0',
     'cam_RR_BD_PP2BCa2': 'calcium_m_rr_bd_calcium_nca4',
     'cam_RR_BD_CaMKII': 'calcium_m_rr_bd_calcium_mkii',
     'cam_RR_BD_CaMKIIp': 'calcium_m_rr_bd_calcium_mkiip',
     'cam_RR_CD_0': 'calcium_m_rr_cd_0',
     'cam_RR_CD_PP2BCa2': 'calcium_m_rr_cd_calcium_nca4',
     'cam_RR_CD_CaMKII': 'calcium_m_rr_cd_calcium_mkii',
     'cam_RR_CD_CaMKIIp': 'calcium_m_rr_cd_calcium_mkiip',
     'cam_RR_ABC_0': 'calcium_m_rr_abc_0',
     'cam_RR_ABC_PP2BCa2': 'calcium_m_rr_abc_calcium_nca4',
     'cam_RR_ABC_CaMKII': 'calcium_m_rr_abc_calcium_mkii',
     'cam_RR_ABC_CaMKIIp': 'calcium_m_rr_abc_calcium_mkiip',
     'cam_RR_ABD_0': 'calcium_m_rr_abd_0',
     'cam_RR_ABD_PP2BCa2': 'calcium_m_rr_abd_calcium_nca4',
     'cam_RR_ABD_CaMKII': 'calcium_m_rr_abd_calcium_mkii',
     'cam_RR_ABD_CaMKIIp': 'calcium_m_rr_abd_calcium_mkiip',
     'cam_RR_ACD_0': 'calcium_m_rr_acd_0',
     'cam_RR_ACD_PP2BCa2': 'calcium_m_rr_acd_calcium_nca4',
     'cam_RR_ACD_CaMKII': 'calcium_m_rr_acd_calcium_mkii',
     'cam_RR_ACD_CaMKIIp': 'calcium_m_rr_acd_calcium_mkiip',
     'cam_RR_BCD_0': 'calcium_m_rr_bcd_0',
     'cam_RR_BCD_PP2BCa2': 'calcium_m_rr_bcd_calcium_nca4',
     'cam_RR_BCD_CaMKII': 'calcium_m_rr_bcd_calcium_mkii',
     'cam_RR_BCD_CaMKIIp': 'calcium_m_rr_bcd_calcium_mkiip',
     'cam_RR_ABCD_0': 'calcium_m_rr_abcd_0',
     'cam_RR_ABCD_PP2BCa2': 'calcium_m_rr_abcd_calcium_nca4',
     'cam_RR_ABCD_CaMKII': 'calcium_m_rr_abcd_calcium_mkii',
     'cam_RR_ABCD_CaMKIIp': 'calcium_m_rr_abcd_calcium_mkiip',
     'cam_RT_0_0': 'calcium_m_rt_0_0',
     'cam_RT_0_Ng': 'calcium_m_rt_0_ng',
     'cam_RT_A_0': 'calcium_m_rt_a_0',
     'cam_RT_A_Ng': 'calcium_m_rt_a_ng',
     'cam_RT_B_0': 'calcium_m_rt_b_0',
     'cam_RT_B_Ng': 'calcium_m_rt_b_ng',
     'cam_RT_C_0': 'calcium_m_rt_c_0',
     'cam_RT_C_Ng': 'calcium_m_rt_c_ng',
     'cam_RT_D_0': 'calcium_m_rt_d_0',
     'cam_RT_D_Ng': 'calcium_m_rt_d_ng',
     'cam_RT_AB_0': 'calcium_m_rt_ab_0',
     'cam_RT_AB_Ng': 'calcium_m_rt_ab_ng',
     'cam_RT_AC_0': 'calcium_m_rt_ac_0',
     'cam_RT_AC_Ng': 'calcium_m_rt_ac_ng',
     'cam_RT_AD_0': 'calcium_m_rt_ad_0',
     'cam_RT_AD_Ng': 'calcium_m_rt_ad_ng',
     'cam_RT_BC_0': 'calcium_m_rt_bc_0',
     'cam_RT_BC_Ng': 'calcium_m_rt_bc_ng',
     'cam_RT_BD_0': 'calcium_m_rt_bd_0',
     'cam_RT_BD_Ng': 'calcium_m_rt_bd_ng',
     'cam_RT_CD_0': 'calcium_m_rt_cd_0',
     'cam_RT_CD_Ng': 'calcium_m_rt_cd_ng',
     'cam_RT_ABC_0': 'calcium_m_rt_abc_0',
     'cam_RT_ABC_Ng': 'calcium_m_rt_abc_ng',
     'cam_RT_ABD_0': 'calcium_m_rt_abd_0',
     'cam_RT_ABD_Ng': 'calcium_m_rt_abd_ng',
     'cam_RT_ACD_0': 'calcium_m_rt_acd_0',
     'cam_RT_ACD_Ng': 'calcium_m_rt_acd_ng',
     'cam_RT_BCD_0': 'calcium_m_rt_bcd_0',
     'cam_RT_BCD_Ng': 'calcium_m_rt_bcd_ng',
     'cam_RT_ABCD_0': 'calcium_m_rt_abcd_0',
     'cam_RT_ABCD_Ng': 'calcium_m_rt_abcd_ng',
     'cam_TR_0_0': 'calcium_m_tr_0_0',
     'cam_TR_A_0': 'calcium_m_tr_a_0',
     'cam_TR_B_0': 'calcium_m_tr_b_0',
     'cam_TR_C_0': 'calcium_m_tr_c_0',
     'cam_TR_D_0': 'calcium_m_tr_d_0',
     'cam_TR_AB_0': 'calcium_m_tr_ab_0',
     'cam_TR_AC_0': 'calcium_m_tr_ac_0',
     'cam_TR_AD_0': 'calcium_m_tr_ad_0',
     'cam_TR_BC_0': 'calcium_m_tr_bc_0',
     'cam_TR_BD_0': 'calcium_m_tr_bd_0',
     'cam_TR_CD_0': 'calcium_m_tr_cd_0',
     'cam_TR_ABC_0': 'calcium_m_tr_abc_0',
     'cam_TR_ABD_0': 'calcium_m_tr_abd_0',
     'cam_TR_ACD_0': 'calcium_m_tr_acd_0',
     'cam_TR_BCD_0': 'calcium_m_tr_bcd_0',
     'cam_TR_ABCD_0': 'calcium_m_tr_abcd_0',
     'cam_TT_0_0': 'calcium_m_tt_0_0',
     'cam_TT_0_Ng': 'calcium_m_tt_0_ng',
     'cam_TT_A_0': 'calcium_m_tt_a_0',
     'cam_TT_A_Ng': 'calcium_m_tt_a_ng',
     'cam_TT_B_0': 'calcium_m_tt_b_0',
     'cam_TT_B_Ng': 'calcium_m_tt_b_ng',
     'cam_TT_C_0': 'calcium_m_tt_c_0',
     'cam_TT_C_Ng': 'calcium_m_tt_c_ng',
     'cam_TT_D_0': 'calcium_m_tt_d_0',
     'cam_TT_D_Ng': 'calcium_m_tt_d_ng',
     'cam_TT_AB_0': 'calcium_m_tt_ab_0',
     'cam_TT_AB_Ng': 'calcium_m_tt_ab_ng',
     'cam_TT_AC_0': 'calcium_m_tt_ac_0',
     'cam_TT_AC_Ng': 'calcium_m_tt_ac_ng',
     'cam_TT_AD_0': 'calcium_m_tt_ad_0',
     'cam_TT_AD_Ng': 'calcium_m_tt_ad_ng',
     'cam_TT_BC_0': 'calcium_m_tt_bc_0',
     'cam_TT_BC_Ng': 'calcium_m_tt_bc_ng',
     'cam_TT_BD_0': 'calcium_m_tt_bd_0',
     'cam_TT_BD_Ng': 'calcium_m_tt_bd_ng',
     'cam_TT_CD_0': 'calcium_m_tt_cd_0',
     'cam_TT_CD_Ng': 'calcium_m_tt_cd_ng',
     'cam_TT_ABC_0': 'calcium_m_tt_abc_0',
     'cam_TT_ABC_Ng': 'calcium_m_tt_abc_ng',
     'cam_TT_ABD_0': 'calcium_m_tt_abd_0',
     'cam_TT_ABD_Ng': 'calcium_m_tt_abd_ng',
     'cam_TT_ACD_0': 'calcium_m_tt_acd_0',
     'cam_TT_ACD_Ng': 'calcium_m_tt_acd_ng',
     'cam_TT_BCD_0': 'calcium_m_tt_bcd_0',
     'cam_TT_BCD_Ng': 'calcium_m_tt_bcd_ng',
     'cam_TT_ABCD_0': 'calcium_m_tt_abcd_0',
     'cam_TT_ABCD_Ng': 'calcium_m_tt_abcd_ng',
     'ca': 'calcium',
     'Ng': 'source_defined_ng_state',
     'PP2BCa2': 'calcium_nca4',
     'CaMKII': 'calcium_mkii',
     'CaMKIIp': 'calcium_mkiip',
     'species_2': 'calcium_nca3',
     'PP2Bi': 'source_defined_can_state',
     'PP2BiCa1': 'calcium_nuclear_calcium',
     'PP2BiCa2': 'calcium_nca2'}

    def __init__(self, model_path: str = 'data/MODEL1903010001.xml', integration_step: float = 0.01) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


Li2019NeurograninStimulatesCaCalmodulinDepeModel1903010001Model = Li2019NeurograninStimulatesCaCalmodulinDepeModel
