# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML wrapper for Levchenko2000_MAPK_Scaffold."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Levchenko2000MapkScaffoldModel(TelluriumSBMLBioModule):
    """Faithful Tellurium execution of the bundled SBML source model."""

    _SBML_ID = 'BIOMD0000000014'
    _TITLE = 'Levchenko2000_MAPK_Scaffold'
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _HEADLINE_OUTPUTS = {'mapk_phosphatase': ('MAPKP',
                          'native SBML value',
                          'MAPK Phosphatase. Maps to SBML symbol `MAPKP` and is emitted in native SBML '
                          'units.'),
     'mek_phosphatase': ('MEKP',
                         'native SBML value',
                         'MEK Phosphatase. Maps to SBML symbol `MEKP` and is emitted in native SBML '
                         'units.'),
     'raf_phosphatase': ('RAFP',
                         'native SBML value',
                         'RAF Phosphatase. Maps to SBML symbol `RAFP` and is emitted in native SBML '
                         'units.')}
    _INITIAL_CONDITION_INPUTS = {'initial_mapk_phosphatase': ('MAPKP',
                                  0.0,
                                  'native SBML value',
                                  'Initial level of MAPK Phosphatase. Maps to SBML symbol `MAPKP`; '
                                  'exposed as a traceable initial-condition perturbation.')}
    _PARAMETER_INPUTS = {}
    _SPECIES_LABELS = {'MAPKP': 'MAPK Phosphatase',
     'MEKP': 'MEK Phosphatase',
     'RAFK': 'RAF Kinase',
     'RAFP': 'RAF Phosphatase',
     'K_1_0': 'MAPK',
     'K_1_1': 'MAPK P',
     'K_1_2': 'MAPK PP',
     'K_2_0': 'MEK',
     'K_2_1': 'source-defined MEK-P state',
     'K_2_2': 'MEK PP',
     'K_3_0': 'RAF',
     'K_3_1': 'source-defined RAF-P state',
     'K_K_1_0_2_2': 'MAPK MEK PP',
     'K_K_1_1_2_2': 'MAPK P MEK PP',
     'K_K_2_0_3_1': 'MEK RAF P',
     'K_K_2_1_3_1': 'MEK P RAF P',
     'K_MAPKP_1_1': 'MAPK P Mapkpase',
     'K_MAPKP_1_2': 'MAPK PP Mapkpase',
     'K_MEKP_2_1': 'MEK P Mekpase',
     'K_MEKP_2_2': 'MEK PP Mekpase',
     'K_RAFK_3_0': 'RAF RAFK',
     'K_RAFP_3_1': 'RAF P Rafpase',
     'S_m1_m1_m1': 'Scaffold',
     'S_m1_m1_0': 'Scaffold RAF',
     'S_m1_m1_1': 'Scaffold RAF P',
     'S_m1_0_m1': 'Scaffold MEK',
     'S_m1_0_0': 'Scaffold MEK RAF',
     'S_m1_0_1': 'Scaffold MEK RAF P',
     'S_m1_1_m1': 'Scaffold MEK P',
     'S_m1_1_0': 'Scaffold MEK P RAF',
     'S_m1_1_1': 'Scaffold MEK P RAF P',
     'S_m1_2_m1': 'Scaffold MEK PP',
     'S_m1_2_0': 'Scaffold MEK PP RAF',
     'S_m1_2_1': 'Scaffold MEK PP RAF P',
     'S_0_m1_m1': 'Scaffold MAPK',
     'S_0_m1_0': 'Scaffold MAPK RAF',
     'S_0_m1_1': 'Scaffold MAPK RAF P',
     'S_0_0_m1': 'Scaffold MAPK MEK',
     'S_0_0_0': 'Scaffold MAPK MEK RAF',
     'S_0_0_1': 'Scaffold MAPK MEK RAF P',
     'S_0_1_m1': 'Scaffold MAPK MEK P',
     'S_0_1_0': 'Scaffold MAPK MEK P RAF',
     'S_0_1_1': 'Scaffold MAPK MEK P RAF P',
     'S_0_2_m1': 'Scaffold MAPK MEK PP',
     'S_0_2_0': 'Scaffold MAPK MEK PP RAF',
     'S_0_2_1': 'Scaffold MAPK MEK PP RAF P',
     'S_1_m1_m1': 'Scaffold MAPK P',
     'S_1_m1_0': 'Scaffold MAPK P RAF',
     'S_1_m1_1': 'Scaffold MAPK P RAF P',
     'S_1_0_m1': 'Scaffold MAPK P MEK',
     'S_1_0_0': 'Scaffold MAPK P MEK RAF',
     'S_1_0_1': 'Scaffold MAPK P MEK RAF P',
     'S_1_1_m1': 'Scaffold MAPK P MEK P',
     'S_1_1_0': 'Scaffold MAPK P MEK P RAF',
     'S_1_1_1': 'Scaffold MAPK P MEK P RAF P',
     'S_1_2_m1': 'Scaffold MAPK P MEK PP',
     'S_1_2_0': 'Scaffold MAPK P MEK PP RAF',
     'S_1_2_1': 'Scaffold MAPK P MEK PP RAF P',
     'S_2_m1_m1': 'Scaffold MAPK PP',
     'S_2_m1_0': 'Scaffold MAPK PP RAF',
     'S_2_m1_1': 'Scaffold MAPK PP RAF P',
     'S_2_0_m1': 'Scaffold MAPK PP MEK',
     'S_2_0_0': 'Scaffold MAPK PP MEK RAF',
     'S_2_0_1': 'Scaffold MAPK PP MEK RAF P',
     'S_2_1_m1': 'Scaffold MAPK PP MEK P',
     'S_2_1_0': 'Scaffold MAPK PP MEK P RAF',
     'S_2_1_1': 'Scaffold MAPK PP MEK P RAF P',
     'S_2_2_m1': 'Scaffold MAPK PP MEK PP',
     'S_2_2_0': 'Scaffold MAPK PP MEK PP RAF',
     'S_2_2_1': 'Scaffold MAPK PP MEK PP RAF P',
     'S_RAFK_m1_m1_0': 'Scaffold RAF',
     'S_RAFK_m1_0_0': 'Scaffold MEK RAF',
     'S_RAFK_m1_1_0': 'Scaffold MEK P RAF',
     'S_RAFK_m1_2_0': 'Scaffold MEK PP RAF',
     'S_RAFK_0_m1_0': 'Scaffold MAPK RAF',
     'S_RAFK_0_0_0': 'Scaffold MAPK MEK RAF',
     'S_RAFK_0_1_0': 'Scaffold MAPK MEK P RAF',
     'S_RAFK_0_2_0': 'Scaffold MAPK MEK PP RAF',
     'S_RAFK_1_m1_0': 'Scaffold MAPK P RAF',
     'S_RAFK_1_0_0': 'Scaffold MAPK P MEK RAF',
     'S_RAFK_1_1_0': 'Scaffold MAPK P MEK P RAF',
     'S_RAFK_1_2_0': 'Scaffold MAPK P MEK PP RAF',
     'S_RAFK_2_m1_0': 'Scaffold MAPK PP RAF',
     'S_RAFK_2_0_0': 'Scaffold MAPK PP MEK RAF',
     'S_RAFK_2_1_0': 'Scaffold MAPK PP MEK P RAF',
     'S_RAFK_2_2_0': 'Scaffold MAPK PP MEK PP RAF'}
    _STATE_OUTPUT_ALIASES = {'MAPKP': 'mapk_phosphatase',
     'MEKP': 'mek_phosphatase',
     'RAFK': 'raf_kinase',
     'RAFP': 'raf_phosphatase',
     'K_1_0': 'mapk',
     'K_1_1': 'mapk_p',
     'K_1_2': 'mapk_pp',
     'K_2_0': 'mek',
     'K_2_1': 'source_defined_mek_p_state',
     'K_2_2': 'mek_pp',
     'K_3_0': 'raf',
     'K_3_1': 'source_defined_raf_p_state',
     'K_K_1_0_2_2': 'mapk_mek_pp',
     'K_K_1_1_2_2': 'mapk_p_mek_pp',
     'K_K_2_0_3_1': 'mek_raf_p',
     'K_K_2_1_3_1': 'mek_p_raf_p',
     'K_MAPKP_1_1': 'mapk_p_mapkpase',
     'K_MAPKP_1_2': 'mapk_pp_mapkpase',
     'K_MEKP_2_1': 'mek_p_mekpase',
     'K_MEKP_2_2': 'mek_pp_mekpase',
     'K_RAFK_3_0': 'raf_rafk',
     'K_RAFP_3_1': 'raf_p_rafpase',
     'S_m1_m1_m1': 'scaffold',
     'S_m1_m1_0': 'scaffold_raf',
     'S_m1_m1_1': 'scaffold_raf_p',
     'S_m1_0_m1': 'scaffold_mek',
     'S_m1_0_0': 'scaffold_mek_raf',
     'S_m1_0_1': 'scaffold_mek_raf_p',
     'S_m1_1_m1': 'scaffold_mek_p',
     'S_m1_1_0': 'scaffold_mek_p_raf',
     'S_m1_1_1': 'scaffold_mek_p_raf_p',
     'S_m1_2_m1': 'scaffold_mek_pp',
     'S_m1_2_0': 'scaffold_mek_pp_raf',
     'S_m1_2_1': 'scaffold_mek_pp_raf_p',
     'S_0_m1_m1': 'scaffold_mapk',
     'S_0_m1_0': 'scaffold_mapk_raf',
     'S_0_m1_1': 'scaffold_mapk_raf_p',
     'S_0_0_m1': 'scaffold_mapk_mek',
     'S_0_0_0': 'scaffold_mapk_mek_raf',
     'S_0_0_1': 'scaffold_mapk_mek_raf_p',
     'S_0_1_m1': 'scaffold_mapk_mek_p',
     'S_0_1_0': 'scaffold_mapk_mek_p_raf',
     'S_0_1_1': 'scaffold_mapk_mek_p_raf_p',
     'S_0_2_m1': 'scaffold_mapk_mek_pp',
     'S_0_2_0': 'scaffold_mapk_mek_pp_raf',
     'S_0_2_1': 'scaffold_mapk_mek_pp_raf_p',
     'S_1_m1_m1': 'scaffold_mapk_p',
     'S_1_m1_0': 'scaffold_mapk_p_raf',
     'S_1_m1_1': 'scaffold_mapk_p_raf_p',
     'S_1_0_m1': 'scaffold_mapk_p_mek',
     'S_1_0_0': 'scaffold_mapk_p_mek_raf',
     'S_1_0_1': 'scaffold_mapk_p_mek_raf_p',
     'S_1_1_m1': 'scaffold_mapk_p_mek_p',
     'S_1_1_0': 'scaffold_mapk_p_mek_p_raf',
     'S_1_1_1': 'scaffold_mapk_p_mek_p_raf_p',
     'S_1_2_m1': 'scaffold_mapk_p_mek_pp',
     'S_1_2_0': 'scaffold_mapk_p_mek_pp_raf',
     'S_1_2_1': 'scaffold_mapk_p_mek_pp_raf_p',
     'S_2_m1_m1': 'scaffold_mapk_pp',
     'S_2_m1_0': 'scaffold_mapk_pp_raf',
     'S_2_m1_1': 'scaffold_mapk_pp_raf_p',
     'S_2_0_m1': 'scaffold_mapk_pp_mek',
     'S_2_0_0': 'scaffold_mapk_pp_mek_raf',
     'S_2_0_1': 'scaffold_mapk_pp_mek_raf_p',
     'S_2_1_m1': 'scaffold_mapk_pp_mek_p',
     'S_2_1_0': 'scaffold_mapk_pp_mek_p_raf',
     'S_2_1_1': 'scaffold_mapk_pp_mek_p_raf_p',
     'S_2_2_m1': 'scaffold_mapk_pp_mek_pp',
     'S_2_2_0': 'scaffold_mapk_pp_mek_pp_raf',
     'S_2_2_1': 'scaffold_mapk_pp_mek_pp_raf_p',
     'S_RAFK_m1_m1_0': 'scaffold_raf_2',
     'S_RAFK_m1_0_0': 'scaffold_mek_raf_2',
     'S_RAFK_m1_1_0': 'scaffold_mek_p_raf_2',
     'S_RAFK_m1_2_0': 'scaffold_mek_pp_raf_2',
     'S_RAFK_0_m1_0': 'scaffold_mapk_raf_2',
     'S_RAFK_0_0_0': 'scaffold_mapk_mek_raf_2',
     'S_RAFK_0_1_0': 'scaffold_mapk_mek_p_raf_2',
     'S_RAFK_0_2_0': 'scaffold_mapk_mek_pp_raf_2',
     'S_RAFK_1_m1_0': 'scaffold_mapk_p_raf_2',
     'S_RAFK_1_0_0': 'scaffold_mapk_p_mek_raf_2',
     'S_RAFK_1_1_0': 'scaffold_mapk_p_mek_p_raf_2',
     'S_RAFK_1_2_0': 'scaffold_mapk_p_mek_pp_raf_2',
     'S_RAFK_2_m1_0': 'scaffold_mapk_pp_raf_2',
     'S_RAFK_2_0_0': 'scaffold_mapk_pp_mek_raf_2',
     'S_RAFK_2_1_0': 'scaffold_mapk_pp_mek_p_raf_2',
     'S_RAFK_2_2_0': 'scaffold_mapk_pp_mek_pp_raf_2'}

    def __init__(self, model_path: str = 'data/BIOMD0000000014.xml', integration_step: float = 0.01) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


Levchenko2000MapkScaffoldBiomd0000000014Model = Levchenko2000MapkScaffoldModel
