# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML wrapper for Oliveira2020 - Malonyl-CoA pathway for Acrylic Acid production from glycerol."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Oliveira2020MalonylCoaPathwayForAcrylicAciModel2010040007Model(TelluriumSBMLBioModule):
    """Faithful Tellurium execution of the bundled SBML source model."""

    _SBML_ID = 'MODEL2010040007'
    _TITLE = 'Oliveira2020 - Malonyl-CoA pathway for Acrylic Acid production from glycerol'
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _HEADLINE_OUTPUTS = {'camp': ('CAMP',
              'native SBML value',
              'cAMP. Maps to SBML symbol `CAMP` and is emitted in native SBML units.'),
     'accoa': ('ACCOA',
               'native SBML value',
               'ACCOA. Maps to SBML symbol `ACCOA` and is emitted in native SBML units.'),
     'source_defined_aco_state': ('ACO',
                                  'native SBML value',
                                  'source-defined ACO state. Maps to SBML symbol `ACO` and is emitted '
                                  'in native SBML units.')}
    _INITIAL_CONDITION_INPUTS = {'initial_coenzyme_a': ('COA',
                            0.5,
                            'native SBML value',
                            'Initial level of coenzyme A. Maps to SBML symbol `COA`; exposed as a '
                            'traceable initial-condition perturbation.'),
     'initial_cysteine': ('CYS',
                          0.085,
                          'native SBML value',
                          'Initial level of cysteine. Maps to SBML symbol `CYS`; exposed as a '
                          'traceable initial-condition perturbation.'),
     'initial_h2o': ('H2O',
                     1.0,
                     'native SBML value',
                     'Initial level of H2O. Maps to SBML symbol `H2O`; exposed as a traceable '
                     'initial-condition perturbation.')}
    _PARAMETER_INPUTS = {}
    _SPECIES_LABELS = {'ACCOA': 'ACCOA',
     'ACO': 'source-defined ACO state',
     'ACP': 'source-defined ACP state',
     'AKG': 'source-defined AKG state',
     'BPG': 'source-defined BPG state',
     'CIT': 'source-defined CIT state',
     'DAP': 'source-defined DAP state',
     'E4P': 'E4P',
     'F6P': 'F6P',
     'FDP': 'source-defined FDP state',
     'FUM': 'source-defined FUM state',
     'G6P': 'G6P',
     'GAP': 'source-defined GAP state',
     'GL6P': 'GL6P',
     'GLX': 'source-defined GLX state',
     'ICIT': 'source-defined ICIT state',
     'KDPG': 'source-defined KDPG state',
     'MAL': 'source-defined MAL state',
     'NAD': 'NAD',
     'NADH': 'source-defined NADH state',
     'NADP': 'source-defined NADP state',
     'NADPH': 'NADPH',
     'OAA': 'source-defined OAA state',
     'PEP': 'source-defined PEP state',
     'PGA2': 'source-defined PGA2 state',
     'PGA3': 'source-defined PGA3 state',
     'PGN': 'source-defined PGN state',
     'PYR': 'source-defined PYR state',
     'Q': 'source-defined Q state',
     'QH2': 'source-defined QH2 state',
     'R5P': 'R5P',
     'RU5P': 'RU5P',
     'S7P': 'S7P',
     'SUC': 'sucrose',
     'SUCCOA': 'SUCCOA',
     'X5P': 'X5P',
     'ei': 'source-defined EI state',
     'eiP': 'source-defined EIP state',
     'eiia': 'source-defined EIIA state',
     'eiiaP': 'Eiia P',
     'eiicb': 'Eiicb',
     'eiicbP': 'Eiicb P',
     'hpr': 'source-defined HPR state',
     'hprP': 'source-defined HPRP state',
     'icd': 'source-defined ICD state',
     'icdP': 'source-defined ICDP state',
     'tal': 'source-defined TAL state',
     'talC3': 'source-defined TALC3 state',
     'tkt': 'source-defined TKT state',
     'tktC2': 'source-defined TKTC2 state',
     'ADP': 'ADP',
     'AMP': 'AMP',
     'ATP': 'ATP',
     'CAMP': 'cAMP',
     'COA': 'coenzyme A',
     'HCO3': 'source-defined HCO3 state',
     'P': 'source-defined P state',
     'MG': 'source-defined MG state',
     'MgADP': 'Mg ADP',
     'MgATP': 'Mg ATP',
     'MgFDP': 'Mg FDP',
     'ASP': 'aspartate ligand',
     'CYS': 'cysteine',
     'MN': 'source-defined MN state',
     'Hin': 'source-defined HIN state',
     'H2O': 'H2O',
     'O2': 'source-defined O2 state',
     'FAD': 'source-defined FAD state',
     'FADH2': 'source-defined FADH2 state',
     'ACEx': 'acetate',
     'GLCx': 'source-defined GLCX state',
     'Px': 'source-defined PX state',
     'ACEx_0': 'source-defined ACEX state',
     'Hout': 'source-defined HOUT state',
     'GLCp': 'source-defined GLCP state',
     'Pp': 'source-defined PP state',
     'ACEp': 'source-defined ACEP state',
     'G3P': 'G3P',
     'GLY': 'source-defined GLY state',
     'MCOA': 'source-defined MCOA state',
     'LGLU': 'source-defined LGLU state',
     'BA': 'source-defined BA state',
     '_3HP': '3HP',
     'MSA': 'source-defined MSA state',
     '_3HPCOA': '3HPCOA',
     'AA': 'source-defined AA state',
     'AACOA': 'AACOA',
     'AAp': 'source-defined AAP state',
     'AAx': 'source-defined AAX state',
     'GLYp': 'source-defined GLYP state',
     'GLYx': 'source-defined GLYX state',
     'BAp': 'source-defined BAP state',
     'BAx': 'source-defined BAX state',
     'DHA': 'source-defined DHA state'}
    _STATE_OUTPUT_ALIASES = {'ACCOA': 'accoa',
     'ACO': 'source_defined_aco_state',
     'ACP': 'source_defined_acp_state',
     'AKG': 'source_defined_akg_state',
     'BPG': 'source_defined_bpg_state',
     'CIT': 'source_defined_cit_state',
     'DAP': 'source_defined_dap_state',
     'E4P': 'e4p',
     'F6P': 'f6p',
     'FDP': 'source_defined_fdp_state',
     'FUM': 'source_defined_fum_state',
     'G6P': 'g6p',
     'GAP': 'source_defined_gap_state',
     'GL6P': 'gl6p',
     'GLX': 'source_defined_glx_state',
     'ICIT': 'source_defined_icit_state',
     'KDPG': 'source_defined_kdpg_state',
     'MAL': 'source_defined_mal_state',
     'NAD': 'nad',
     'NADH': 'source_defined_nadh_state',
     'NADP': 'source_defined_nadp_state',
     'NADPH': 'nadph',
     'OAA': 'source_defined_oaa_state',
     'PEP': 'source_defined_pep_state',
     'PGA2': 'source_defined_pga2_state',
     'PGA3': 'source_defined_pga3_state',
     'PGN': 'source_defined_pgn_state',
     'PYR': 'source_defined_pyr_state',
     'Q': 'source_defined_q_state',
     'QH2': 'source_defined_qh2_state',
     'R5P': 'r5p',
     'RU5P': 'ru5p',
     'S7P': 's7p',
     'SUC': 'sucrose',
     'SUCCOA': 'succoa',
     'X5P': 'x5p',
     'ei': 'source_defined_ei_state',
     'eiP': 'source_defined_eip_state',
     'eiia': 'source_defined_eiia_state',
     'eiiaP': 'eiia_p',
     'eiicb': 'eiicb',
     'eiicbP': 'eiicb_p',
     'hpr': 'source_defined_hpr_state',
     'hprP': 'source_defined_hprp_state',
     'icd': 'source_defined_icd_state',
     'icdP': 'source_defined_icdp_state',
     'tal': 'source_defined_tal_state',
     'talC3': 'source_defined_talc3_state',
     'tkt': 'source_defined_tkt_state',
     'tktC2': 'source_defined_tktc2_state',
     'ADP': 'adp',
     'AMP': 'amp',
     'ATP': 'atp',
     'CAMP': 'camp',
     'COA': 'coenzyme_a',
     'HCO3': 'source_defined_hco3_state',
     'P': 'source_defined_p_state',
     'MG': 'source_defined_mg_state',
     'MgADP': 'mg_adp',
     'MgATP': 'mg_atp',
     'MgFDP': 'mg_fdp',
     'ASP': 'aspartate_ligand',
     'CYS': 'cysteine',
     'MN': 'source_defined_mn_state',
     'Hin': 'source_defined_hin_state',
     'H2O': 'h2o',
     'O2': 'source_defined_o2_state',
     'FAD': 'source_defined_fad_state',
     'FADH2': 'source_defined_fadh2_state',
     'ACEx': 'acetate',
     'GLCx': 'source_defined_glcx_state',
     'Px': 'source_defined_px_state',
     'ACEx_0': 'source_defined_acex_state',
     'Hout': 'source_defined_hout_state',
     'GLCp': 'source_defined_glcp_state',
     'Pp': 'source_defined_pp_state',
     'ACEp': 'source_defined_acep_state',
     'G3P': 'g3p',
     'GLY': 'source_defined_gly_state',
     'MCOA': 'source_defined_mcoa_state',
     'LGLU': 'source_defined_lglu_state',
     'BA': 'source_defined_ba_state',
     '_3HP': 'source_3hp',
     'MSA': 'source_defined_msa_state',
     '_3HPCOA': 'source_3hpcoa',
     'AA': 'source_defined_aa_state',
     'AACOA': 'aacoa',
     'AAp': 'source_defined_aap_state',
     'AAx': 'source_defined_aax_state',
     'GLYp': 'source_defined_glyp_state',
     'GLYx': 'source_defined_glyx_state',
     'BAp': 'source_defined_bap_state',
     'BAx': 'source_defined_bax_state',
     'DHA': 'source_defined_dha_state'}

    def __init__(self, model_path: str = 'data/MODEL2010040007.xml', integration_step: float = 0.01) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


Oliveira2020MalonylCoaPathwayForAcrylicAciModel2010040007Model = Oliveira2020MalonylCoaPathwayForAcrylicAciModel2010040007Model
