# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML wrapper for Yapo2017 - A2AR/cAMP/PKA signalling in D2 dopamine receptor expressing medium-spiny neurons."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Yapo2017A2arCampPkaSignallingInD2DopamineModel(TelluriumSBMLBioModule):
    """Faithful Tellurium execution of the bundled SBML source model."""

    _SBML_ID = 'MODEL1701170001'
    _TITLE = 'Yapo2017 - A2AR/cAMP/PKA signalling in D2 dopamine receptor expressing medium-spiny neurons'
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _HEADLINE_OUTPUTS = {'camp': ('cAMP',
              'native SBML value',
              'cAMP. Maps to SBML symbol `cAMP` and is emitted in native SBML units.'),
     'pde10_c_amp': ('PDE10_cAMP',
                     'native SBML value',
                     'PDE10 C AMP. Maps to SBML symbol `PDE10_cAMP` and is emitted in native SBML '
                     'units.'),
     'pkac_amp2': ('PKAcAMP2',
                   'native SBML value',
                   'Pkac AMP2. Maps to SBML symbol `PKAcAMP2` and is emitted in native SBML units.')}
    _INITIAL_CONDITION_INPUTS = {'initial_adenosine': ('Adn',
                           130.0,
                           'native SBML value',
                           'Initial level of adenosine. Maps to SBML symbol `Adn`; exposed as a '
                           'traceable initial-condition perturbation.'),
     'initial_amp': ('AMP',
                     0.0,
                     'native SBML value',
                     'Initial level of AMP. Maps to SBML symbol `AMP`; exposed as a traceable '
                     'initial-condition perturbation.'),
     'initial_atp': ('ATP',
                     5000000.0,
                     'native SBML value',
                     'Initial level of ATP. Maps to SBML symbol `ATP`; exposed as a traceable '
                     'initial-condition perturbation.')}
    _PARAMETER_INPUTS = {}
    _SPECIES_LABELS = {'mwbe974953_e869_4622_b4a8_745555c8d7fd': 'source-defined DA state',
     'D2R': 'D2R',
     'D2RDA': 'D2RDA',
     'D2RDAGi': 'D2rdagi',
     'Gi': 'source-defined GI state',
     'D2RGi': 'D2rgi',
     'GaiGTP': 'Gai GTP',
     'Gbgi': 'source-defined GBGI state',
     'A2AR': 'A2AR',
     'A2ARAdn': 'A2aradn',
     'Adn': 'adenosine',
     'A2ARAdnGolf': 'A2aradn Golf G protein',
     'Golf': 'Golf G protein',
     'A2ARGolf': 'A2argolf',
     'GaolfGTP': 'Gaolf GTP',
     'Gbgolf': 'Gbgolf',
     'GaolfGDP': 'Gaolf GDP',
     'GaiGDP': 'Gai GDP',
     'AC5': 'source-defined AC5 state',
     'AC5_ATP': 'AC5 ATP',
     'ATP': 'ATP',
     'cAMP': 'cAMP',
     'AC5GaolfGTP': 'Ac5gaolf GTP',
     'AC5GaolfGTP_ATP': 'Ac5gaolf GTP ATP',
     'AC5GaiGTP': 'Ac5gai GTP',
     'AC5GaiGTP_ATP': 'Ac5gai GTP ATP',
     'AC5GaolfGTPGaiGTP': 'Ac5gaolf Gtpgai GTP',
     'AC5GaolfGTPGaiGTP_ATP': 'Ac5gaolf Gtpgai GTP ATP',
     'PDE10': 'PDE10',
     'PDE10_cAMP': 'PDE10 C AMP',
     'AMP': 'AMP',
     'PKA': 'source-defined PKA state',
     'PKAcAMP2': 'Pkac AMP2',
     'PKAcAMP4': 'Pkac AMP4',
     'PKAc': 'source-defined PKAC state',
     'PKAreg': 'Pkareg',
     'Ca': 'calcium',
     'CaM': 'calmodulin',
     'CaMCa2': 'calcium Mca2',
     'CaMCa4': 'calcium Mca4',
     'PP2B': 'PP2B',
     'PP2BCaM': 'Pp2bca M',
     'PP2BCaMCa2': 'Pp2bca Mca2',
     'PP2Bc': 'Pp2bc',
     'DARPP32': 'DARPP32',
     'PKAc_D32': 'Pkac D32',
     'D32p34': 'D32p34',
     'B56PP2A': 'B56PP2A',
     'PKAc_B56PP2A': 'Pkac B56PP2A',
     'B56PP2Ap': 'B56pp2ap',
     'PP1': 'source-defined PP1 state',
     'PP1D32p34': 'Pp1d32p34',
     'CDK5': 'source-defined CDK5 state',
     'CDK5_D32': 'CDK5 D32',
     'D32p75': 'D32p75',
     'PKAcD32p75': 'Pkac D32p75',
     'B72PP2A': 'B72PP2A',
     'B72PPA2Ca': 'B72ppa2ca',
     'B56PP2Ap_D32p75': 'B56pp2ap D32p75',
     'B72PP2A_D32p75': 'B72PP2A D32p75',
     'B72PP2ACa_D32p75': 'B72pp2aca D32p75',
     'B56PP2A_D32p75': 'B56PP2A D32p75',
     'PP2Bc_D32p34': 'Pp2bc D32p34',
     'EPAC': 'source-defined EPAC state',
     'EPAC_cAMP': 'EPAC C AMP',
     'AKAR3': 'source-defined AKAR3 state',
     'PKAc_AKAR3': 'Pkac AKAR3',
     'AKAR3p': 'Akar3p',
     'PP1_AKAR3p': 'PP1 Akar3p',
     'totalActivePKA': 'Total active PKA',
     'totalAKAR3p': 'Total Akar3p'}
    _STATE_OUTPUT_ALIASES = {'mwbe974953_e869_4622_b4a8_745555c8d7fd': 'source_defined_da_state',
     'D2R': 'd2r',
     'D2RDA': 'd2rda',
     'D2RDAGi': 'd2rdagi',
     'Gi': 'source_defined_gi_state',
     'D2RGi': 'd2rgi',
     'GaiGTP': 'gai_gtp',
     'Gbgi': 'source_defined_gbgi_state',
     'A2AR': 'a2ar',
     'A2ARAdn': 'a2aradn',
     'Adn': 'adenosine',
     'A2ARAdnGolf': 'a2aradn_golf_g_protein',
     'Golf': 'golf_g_protein',
     'A2ARGolf': 'a2argolf',
     'GaolfGTP': 'gaolf_gtp',
     'Gbgolf': 'gbgolf',
     'GaolfGDP': 'gaolf_gdp',
     'GaiGDP': 'gai_gdp',
     'AC5': 'source_defined_ac5_state',
     'AC5_ATP': 'ac5_atp',
     'ATP': 'atp',
     'cAMP': 'camp',
     'AC5GaolfGTP': 'ac5gaolf_gtp',
     'AC5GaolfGTP_ATP': 'ac5gaolf_gtp_atp',
     'AC5GaiGTP': 'ac5gai_gtp',
     'AC5GaiGTP_ATP': 'ac5gai_gtp_atp',
     'AC5GaolfGTPGaiGTP': 'ac5gaolf_gtpgai_gtp',
     'AC5GaolfGTPGaiGTP_ATP': 'ac5gaolf_gtpgai_gtp_atp',
     'PDE10': 'pde10',
     'PDE10_cAMP': 'pde10_c_amp',
     'AMP': 'amp',
     'PKA': 'source_defined_pka_state',
     'PKAcAMP2': 'pkac_amp2',
     'PKAcAMP4': 'pkac_amp4',
     'PKAc': 'source_defined_pkac_state',
     'PKAreg': 'pkareg',
     'Ca': 'calcium',
     'CaM': 'calmodulin',
     'CaMCa2': 'calcium_mca2',
     'CaMCa4': 'calcium_mca4',
     'PP2B': 'pp2b',
     'PP2BCaM': 'pp2bca_m',
     'PP2BCaMCa2': 'pp2bca_mca2',
     'PP2Bc': 'pp2bc',
     'DARPP32': 'darpp32',
     'PKAc_D32': 'pkac_d32',
     'D32p34': 'd32p34',
     'B56PP2A': 'b56pp2a',
     'PKAc_B56PP2A': 'pkac_b56pp2a',
     'B56PP2Ap': 'b56pp2ap',
     'PP1': 'source_defined_pp1_state',
     'PP1D32p34': 'pp1d32p34',
     'CDK5': 'source_defined_cdk5_state',
     'CDK5_D32': 'cdk5_d32',
     'D32p75': 'd32p75',
     'PKAcD32p75': 'pkac_d32p75',
     'B72PP2A': 'b72pp2a',
     'B72PPA2Ca': 'b72ppa2ca',
     'B56PP2Ap_D32p75': 'b56pp2ap_d32p75',
     'B72PP2A_D32p75': 'b72pp2a_d32p75',
     'B72PP2ACa_D32p75': 'b72pp2aca_d32p75',
     'B56PP2A_D32p75': 'b56pp2a_d32p75',
     'PP2Bc_D32p34': 'pp2bc_d32p34',
     'EPAC': 'source_defined_epac_state',
     'EPAC_cAMP': 'epac_c_amp',
     'AKAR3': 'source_defined_akar3_state',
     'PKAc_AKAR3': 'pkac_akar3',
     'AKAR3p': 'akar3p',
     'PP1_AKAR3p': 'pp1_akar3p',
     'totalActivePKA': 'total_active_pka',
     'totalAKAR3p': 'total_akar3p'}

    def __init__(self, model_path: str = 'data/MODEL1701170001.xml', integration_step: float = 0.01) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


Yapo2017A2arCampPkaSignallingInD2DopamineModel1701170001Model = Yapo2017A2arCampPkaSignallingInD2DopamineModel
