# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML wrapper for Chen2009 - ErbB Signaling."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Chen2009ErbbSignalingModel(TelluriumSBMLBioModule):
    """Faithful Tellurium execution of the bundled SBML source model."""

    _SBML_ID = 'BIOMD0000000255'
    _TITLE = 'Chen2009 - ErbB Signaling'
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _HEADLINE_OUTPUTS = {'source_2_egf_erb_b1_atp_full_active': ('c116',
                                             'native SBML value',
                                             '2 EGF Erb B1 ATP Full active. Maps to SBML symbol `c116` '
                                             'and is emitted in native SBML units.'),
     'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp': ('c27',
                                                                                                       'native '
                                                                                                       'SBML '
                                                                                                       'value',
                                                                                                       '2 '
                                                                                                       'EGF '
                                                                                                       'Erb '
                                                                                                       'B1 '
                                                                                                       'P '
                                                                                                       'GAP '
                                                                                                       'Grb2 '
                                                                                                       'adapter '
                                                                                                       'protein '
                                                                                                       'SOS '
                                                                                                       'guanine-nucleotide '
                                                                                                       'exchange '
                                                                                                       'factor '
                                                                                                       'RAS '
                                                                                                       'GDP. '
                                                                                                       'Maps '
                                                                                                       'to '
                                                                                                       'SBML '
                                                                                                       'symbol '
                                                                                                       '`c27` '
                                                                                                       'and '
                                                                                                       'is '
                                                                                                       'emitted '
                                                                                                       'in '
                                                                                                       'native '
                                                                                                       'SBML '
                                                                                                       'units.'),
     'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_c_pp': ('c89',
                                                                                                            'native '
                                                                                                            'SBML '
                                                                                                            'value',
                                                                                                            '2 '
                                                                                                            'EGF '
                                                                                                            'Erb '
                                                                                                            'B1 '
                                                                                                            'P '
                                                                                                            'GAP '
                                                                                                            'Grb2 '
                                                                                                            'adapter '
                                                                                                            'protein '
                                                                                                            'SOS '
                                                                                                            'guanine-nucleotide '
                                                                                                            'exchange '
                                                                                                            'factor '
                                                                                                            'RAS '
                                                                                                            'GDP '
                                                                                                            'C '
                                                                                                            'PP. '
                                                                                                            'Maps '
                                                                                                            'to '
                                                                                                            'SBML '
                                                                                                            'symbol '
                                                                                                            '`c89` '
                                                                                                            'and '
                                                                                                            'is '
                                                                                                            'emitted '
                                                                                                            'in '
                                                                                                            'native '
                                                                                                            'SBML '
                                                                                                            'units.')}
    _INITIAL_CONDITION_INPUTS = {'initial_egf': ('c1',
                     1e-11,
                     'mole',
                     'Initial level of EGF. Maps to SBML symbol `c1`; exposed as a traceable '
                     'initial-condition perturbation.'),
     'initial_heregulin': ('c515',
                           0.0,
                           'native SBML value',
                           'Initial level of heregulin. Maps to SBML symbol `c515`; exposed as a '
                           'traceable initial-condition perturbation.'),
     'initial_heregulin_2': ('c514',
                             0.0,
                             'mole',
                             'Initial level of heregulin. Maps to SBML symbol `c514`; exposed as a '
                             'traceable initial-condition perturbation.')}
    _PARAMETER_INPUTS = {}
    _SPECIES_LABELS = {'c1': 'EGF',
     'c2': 'Erb B1 ATP',
     'c3': 'EGF Erb B1 ATP',
     'c288': 'Erb B2 Erb B3',
     'c335': 'Erb B3 Erb B2 P',
     'c117': 'Erb B2 Erb B4',
     'c336': 'Erb B4 Erb B2 P',
     'c286': 'Erb B1 Inh',
     'c499': 'EGF Erb B1 Inh',
     'c500': 'EGF Erb B1 ATP EGF Erb B1 Inh',
     'c501': '2 EGF Erb B1 Inh',
     'c4': '2 EGF Erb B1 ATP',
     'c10': 'EGF Erb B1 ATP',
     'c11': '2 EGF Erb B1 ATP',
     'c141': 'source-defined ERBB2 state',
     'c145': 'EGF Erb B1 Erb B2',
     'c140': 'source-defined ERBB3 state',
     'c146': 'EGF Erb B1 Erb B3',
     'c143': 'source-defined ERBB4 state',
     'c147': 'EGF Erb B1 Erb B4',
     'c155': 'source-defined ERBB2 state',
     'c159': 'EGF Erb B1 Erb B2',
     'c154': 'source-defined ERBB3 state',
     'c160': 'EGF Erb B1 Erb B3',
     'c156': 'source-defined ERBB4 state',
     'c161': 'EGF Erb B1 Erb B4',
     'c492': 'EGF Erb B1 Inh Er B2',
     'c493': 'EGF Erb B1 Inh Er B3',
     'c494': 'EGF Erb B1 Inh Er B4',
     'c502': 'Erb B2 Inh',
     'c504': 'EGF Erb B1 Erb B2 Inh',
     'c503': 'Erb B4 Inh',
     'c505': 'EGF Erb B1 Erb B3 P Inh',
     'c506': 'Erb B3 Inh',
     'c507': 'EGF Erb B1 Erb B3 P Inh',
     'c105': 'ATP 1 2e9',
     'c123': 'EGF Erb B1 Erb B2 ATP',
     'c124': 'EGF Erb B1 Erb B3 ATP',
     'c125': 'EGF Erb B1 Erb B4 ATP',
     'c126': '2 EGF Erb B1 ATP',
     'c116': '2 EGF Erb B1 ATP Full active',
     'c122': 'EGF Erb B1 Erb B2 ATP',
     'c127': 'EGF Erb B1 Erb B3 ATP',
     'c128': 'EGF Erb B1 Erb B4 ATP',
     'c284': 'Erb B2 Erb B2 P',
     'c129': 'Erb B2 Erb B2 P ATP',
     'c427': 'Erb B1 Erb B2 P GAP Grb2 adapter protein Gab1',
     'c130': 'Erb B1 Erb B2 P GAP Grb2 adapter protein Gab1 ATP',
     'c428': 'Erb B1 Erb B3 P GAP Grb2 adapter protein Gab1',
     'c131': 'Erb B1 Erb B3 P GAP Grb2 adapter protein Gab1 ATP',
     'c429': 'Erb B1 Erb B4 P GAP Grb2 adapter protein Gab1',
     'c132': 'Erb B1 Erb B4 P GAP Grb2 adapter protein Gab1 ATP',
     'c436': '2 Erb B2 P GAP Grb2 adapter protein Gab1',
     'c133': '2 Erb B2 P GAP Grb2 adapter protein Gab1 ATP',
     'c439': 'Erb B3 Erb B2 P GAP Grb2 adapter protein Gab1',
     'c134': 'Erb B3 Erb B2 P GAP Grb2 adapter protein Gab1 ATP',
     'c442': 'Erb B4 Erb B2 P GAP Grb2 adapter protein Gab1',
     'c135': 'Erb B4 Erb B2 P GAP Grb2 adapter protein Gab1 ATP',
     'c483': '2 EGF Erb B1 P GAP Grb2 adapter protein Gab1',
     'c136': '2 EGF Erb B1 P GAP Grb2 adapter protein Gab1 ATP',
     'c516': 'heregulin Erb B3 Erb B1',
     'c137': 'heregulin Erb B3 Erb B1 ATP',
     'c517': 'heregulin Erb B4 Erb B1',
     'c138': 'heregulin Erb B4 Erb B1 ATP',
     'c345': 'heregulin Erb B4 Erb B2',
     'c139': 'heregulin Erb B4 Erb B2 ATP',
     'c355': 'heregulin Erb B3 Erb B2',
     'c168': 'heregulin Erb B3 Erb B2 ATP',
     'c421': 'heregulin Erb B3 Erb B2',
     'c169': 'heregulin Erb B3 Erb B2 ATP',
     'c422': 'heregulin Erb B4 Erb B2',
     'c170': 'heregulin Erb B4 Erb B2 ATP',
     'c23': '2 EGF Erb B1 P GAP Grb2 adapter protein',
     'c12': 'source-defined CPP state',
     'c7': '2 EGF Erb B1 P GAP Grb2 adapter protein C PP',
     'c25': '2 EGF Erb B1 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor',
     'c88': '2 EGF Erb B1 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor C PP',
     'c27': '2 EGF Erb B1 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GDP',
     'c89': '2 EGF Erb B1 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GDP C '
            'PP',
     'c29': '2 EGF Erb B1 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GTP',
     'c90': '2 EGF Erb B1 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GTP C '
            'PP',
     'c34': '2 EGF Erb B1 P GAP Shc adapter protein P Grb2 adapter protein',
     'c91': '2 EGF Erb B1 P GAP Shc adapter protein P Grb2 adapter protein C PP',
     'c35': '2 EGF Erb B1 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
            'exchange factor',
     'c92': '2 EGF Erb B1 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
            'exchange factor C PP',
     'c36': '2 EGF Erb B1 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
            'exchange factor RAS GDP',
     'c93': '2 EGF Erb B1 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
            'exchange factor RAS GDP C PP',
     'c37': '2 EGF Erb B1 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
            'exchange factor RAS GTP',
     'c94': '2 EGF Erb B1 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
            'exchange factor RAS GTP C PP',
     'c189': 'Erb B1 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein',
     'c195': 'Erb B1 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein C PP',
     'c190': 'Erb B1 Erb B3 P GAP Shc adapter protein P Grb2 adapter protein',
     'c196': 'Erb B1 Erb B3 P GAP Shc adapter protein P Grb2 adapter protein C PP',
     'c191': 'Erb B1 Erb B4 P GAP Shc adapter protein P Grb2 adapter protein',
     'c197': 'Erb B1 Erb B4 P GAP Shc adapter protein P Grb2 adapter protein C PP',
     'c198': 'Erb B1 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor',
     'c204': 'Erb B1 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor C PP',
     'c199': 'Erb B1 Erb B3 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor',
     'c205': 'Erb B1 Erb B3 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor C PP',
     'c200': 'Erb B1 Erb B4 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor',
     'c206': 'Erb B1 Erb B4 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor C PP',
     'c207': 'Erb B1 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GDP',
     'c213': 'Erb B1 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GDP C PP',
     'c208': 'Erb B1 Erb B3 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GDP',
     'c214': 'Erb B1 Erb B3 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GDP C PP',
     'c209': 'Erb B1 Erb B4 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GDP',
     'c215': 'Erb B1 Erb B4 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GDP C PP',
     'c216': 'Erb B1 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GTP',
     'c222': 'Erb B1 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GTP C PP',
     'c217': 'Erb B1 Erb B3 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GTP',
     'c223': 'Erb B1 Erb B3 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GTP C PP',
     'c218': 'Erb B1 Erb B4 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GTP',
     'c224': 'Erb B1 Erb B4 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GTP C PP',
     'c225': 'Erb B1 Erb B2 P GAP Grb2 adapter protein',
     'c231': 'Erb B1 Erb B2 P GAP Grb2 adapter protein C PP',
     'c226': 'Erb B1 Erb B3 P GAP Grb2 adapter protein',
     'c232': 'Erb B1 Erb B3 P GAP Grb2 adapter protein C PP',
     'c227': 'Erb B1 Erb B4 P GAP Grb2 adapter protein',
     'c233': 'Erb B1 Erb B4 P GAP Grb2 adapter protein C PP',
     'c243': 'Erb B1 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GDP',
     'c249': 'Erb B1 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GDP '
             'C PP',
     'c244': 'Erb B1 Erb B3 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GDP',
     'c250': 'Erb B1 Erb B3 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GDP '
             'C PP',
     'c245': 'Erb B1 Erb B4 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GDP',
     'c251': 'Erb B1 Erb B4 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GDP '
             'C PP',
     'c252': 'Erb B1 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GTP',
     'c258': 'Erb B1 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GTP '
             'C PP',
     'c253': 'Erb B1 Erb B3 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GTP',
     'c259': 'Erb B1 Erb B3 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GTP '
             'C PP',
     'c254': 'Erb B1 Erb B4 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GTP',
     'c260': 'Erb B1 Erb B4 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GTP '
             'C PP',
     'c234': 'Erb B1 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor',
     'c240': 'Erb B1 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor C PP',
     'c235': 'Erb B1 Erb B3 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor',
     'c241': 'Erb B1 Erb B3 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor C PP',
     'c236': 'Erb B1 Erb B4 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor',
     'c242': 'Erb B1 Erb B4 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor C PP',
     'c300': '2 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein',
     'c301': '2 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein C PP',
     'c303': '2 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor',
     'c304': '2 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor C PP',
     'c306': '2 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GDP',
     'c307': '2 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GDP C PP',
     'c309': '2 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GTP',
     'c310': '2 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GTP C PP',
     'c312': '2 Erb B2 P GAP Grb2 adapter protein',
     'c313': '2 Erb B2 P GAP Grb2 adapter protein C PP',
     'c315': '2 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor',
     'c316': '2 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor C PP',
     'c318': '2 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GDP',
     'c319': '2 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GDP C PP',
     'c321': '2 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GTP',
     'c322': '2 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GTP C PP',
     'c357': 'Erb B3 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein',
     'c358': 'Erb B3 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein C PP',
     'c360': 'Erb B4 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein',
     'c361': 'Erb B4 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein C PP',
     'c366': 'Erb B4 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor',
     'c367': 'Erb B4 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor C PP',
     'c369': 'Erb B3 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GDP',
     'c370': 'Erb B3 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GDP C PP',
     'c372': 'Erb B4 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GDP',
     'c373': 'Erb B4 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GDP C PP',
     'c375': 'Erb B3 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GTP',
     'c376': 'Erb B3 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GTP C PP',
     'c378': 'Erb B4 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GTP',
     'c379': 'Erb B4 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GTP C PP',
     'c381': 'Erb B3 Erb B2 P GAP Grb2 adapter protein',
     'c382': 'Erb B3 Erb B2 P GAP Grb2 adapter protein C PP',
     'c363': 'Erb B3 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor',
     'c364': 'Erb B3 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor C PP',
     'c384': 'Erb B4 Erb B2 P GAP Grb2 adapter protein',
     'c385': 'Erb B4 Erb B2 P GAP Grb2 adapter protein C PP',
     'c387': 'Erb B3 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor',
     'c388': 'Erb B3 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor C PP',
     'c390': 'Erb B4 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor',
     'c391': 'Erb B4 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor C PP',
     'c393': 'Erb B3 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GDP',
     'c394': 'Erb B3 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GDP '
             'C PP',
     'c396': 'Erb B4 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GDP',
     'c397': 'Erb B4 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GDP '
             'C PP',
     'c399': 'Erb B3 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GTP',
     'c400': 'Erb B3 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GTP '
             'C PP',
     'c402': 'Erb B4 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GTP',
     'c403': 'Erb B4 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GTP '
             'C PP',
     'c9': 'source-defined CPP state',
     'c404': 'Erb B4 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GTP',
     'c401': 'Erb B3 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GTP',
     'c398': 'Erb B4 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GDP',
     'c395': 'Erb B3 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GDP',
     'c392': 'Erb B4 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor',
     'c389': 'Erb B3 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor',
     'c386': 'Erb B4 Erb B2 P GAP Grb2 adapter protein',
     'c365': 'Erb B3 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor',
     'c383': 'Erb B3 Erb B2 P GAP Grb2 adapter protein',
     'c380': 'Erb B4 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GTP',
     'c377': 'Erb B3 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GTP',
     'c374': 'Erb B4 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GDP',
     'c371': 'Erb B3 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GDP',
     'c368': 'Erb B4 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor',
     'c362': 'Erb B4 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein',
     'c359': 'Erb B3 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein',
     'c323': '2 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GTP',
     'c320': '2 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GDP',
     'c317': '2 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor',
     'c314': '2 Erb B2 P GAP Grb2 adapter protein',
     'c311': '2 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GTP',
     'c308': '2 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GDP',
     'c305': '2 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor',
     'c302': '2 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein',
     'c239': 'Erb B1 Erb B4 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor',
     'c238': 'Erb B1 Erb B3 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor',
     'c237': 'Erb B1 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor',
     'c257': 'Erb B1 Erb B4 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GTP',
     'c256': 'Erb B1 Erb B3 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GTP',
     'c255': 'Erb B1 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GTP',
     'c248': 'Erb B1 Erb B4 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GDP',
     'c247': 'Erb B1 Erb B3 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GDP',
     'c246': 'Erb B1 Erb B2 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GDP',
     'c230': 'Erb B1 Erb B4 P GAP Grb2 adapter protein',
     'c229': 'Erb B1 Erb B3 P GAP Grb2 adapter protein',
     'c228': 'Erb B1 Erb B2 P GAP Grb2 adapter protein',
     'c221': 'Erb B1 Erb B4 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GTP',
     'c220': 'Erb B1 Erb B3 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GTP',
     'c219': 'Erb B1 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GTP',
     'c212': 'Erb B1 Erb B4 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GDP',
     'c211': 'Erb B1 Erb B3 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GDP',
     'c210': 'Erb B1 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor RAS GDP',
     'c203': 'Erb B1 Erb B4 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor',
     'c202': 'Erb B1 Erb B3 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor',
     'c201': 'Erb B1 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor',
     'c194': 'Erb B1 Erb B4 P GAP Shc adapter protein P Grb2 adapter protein',
     'c193': 'Erb B1 Erb B3 P GAP Shc adapter protein P Grb2 adapter protein',
     'c192': 'Erb B1 Erb B2 P GAP Shc adapter protein P Grb2 adapter protein',
     'c68': '2 EGF Erb B1 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
            'exchange factor RAS GTP',
     'c67': '2 EGF Erb B1 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
            'exchange factor RAS GDP',
     'c66': '2 EGF Erb B1 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
            'exchange factor',
     'c65': '2 EGF Erb B1 P GAP Shc adapter protein P Grb2 adapter protein',
     'c21': '2 EGF Erb B1 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GTP',
     'c20': '2 EGF Erb B1 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor RAS GDP',
     'c18': '2 EGF Erb B1 P GAP Grb2 adapter protein',
     'c19': '2 EGF Erb B1 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor',
     'c6': 'Erb B1 ATP',
     'c5': '2 EGF Erb B1 P',
     'c8': '2 EGF Erb B1 P',
     'c15': '2 EGF Erb B1 P GAP',
     'c17': '2 EGF Erb B1 P GAP',
     'c32': '2 EGF Erb B1 P GAP Shc adapter protein',
     'c63': '2 EGF Erb B1 P GAP Shc adapter protein',
     'c33': '2 EGF Erb B1 P GAP Shc adapter protein P',
     'c64': '2 EGF Erb B1 P GAP Shc adapter protein P',
     'c347': 'Erb B3 Erb B2 P GAP Shc adapter protein',
     'c349': 'Erb B3 Erb B2 P GAP Shc adapter protein',
     'c348': 'Erb B4 Erb B2 P GAP Shc adapter protein',
     'c350': 'Erb B4 Erb B2 P GAP Shc adapter protein',
     'c351': 'Erb B3 Erb B2 P GAP Shc adapter protein P',
     'c353': 'Erb B3 Erb B2 P GAP Shc adapter protein P',
     'c508': 'Erb B2 Inh',
     'c512': 'Erb B4 Inh',
     'c354': 'Erb B4 Erb B2 P GAP Shc adapter protein P',
     'c356': 'Erb B4 Erb B2 P GAP Shc adapter protein P',
     'c148': 'Erb B1 Erb B2 P',
     'c162': 'Erb B1 Erb B2 P',
     'c149': 'Erb B1 Erb B3 P',
     'c163': 'Erb B1 Erb B3 P',
     'c150': 'Erb B1 Erb B4 P',
     'c164': 'Erb B1 Erb B4 P',
     'c289': '2 Erb B2 P',
     'c290': '2 Erb B2 P',
     'c337': 'Erb B3 Erb B2 P',
     'c338': 'Erb B4 Erb B2 P',
     'c291': '2 Erb B2 P GAP',
     'c293': '2 Erb B2 P GAP',
     'c294': '2 Erb B2 P GAP Shc adapter protein',
     'c296': '2 Erb B2 P GAP Shc adapter protein',
     'c297': '2 Erb B2 P GAP Shc adapter protein P',
     'c299': '2 Erb B2 P GAP Shc adapter protein P',
     'c14': 'source-defined GAP state',
     'c165': 'Erb B1 Erb B2 P GAP',
     'c166': 'Erb B1 Erb B3 P GAP',
     'c167': 'Erb B1 Erb B4 P GAP',
     'c151': 'Erb B1 Erb B2 P GAP',
     'c152': 'Erb B1 Erb B3 P GAP',
     'c153': 'Erb B1 Erb B4 P GAP',
     'c341': 'Erb B3 Erb B2 P GAP',
     'c344': 'Erb B4 Erb B2 P GAP',
     'c343': 'Erb B3 Erb B2 P GAP',
     'c346': 'Erb B4 Erb B2 P GAP',
     'c16': 'EGF',
     'c515': 'heregulin',
     'c157': 'heregulin Erb B3',
     'c22': 'Grb2 adapter protein',
     'c40': 'source-defined (SHC_P) state',
     'c39': 'Shc adapter protein P Grb2 adapter protein',
     'c180': 'Erb B1 Erb B2 P GAP Shc adapter protein P',
     'c181': 'Erb B1 Erb B3 P GAP Shc adapter protein P',
     'c182': 'Erb B1 Erb B4 P GAP Shc adapter protein P',
     'c183': 'Erb B1 Erb B2 P GAP Shc adapter protein P',
     'c184': 'Erb B1 Erb B3 P GAP Shc adapter protein P',
     'c185': 'Erb B1 Erb B4 P GAP Shc adapter protein P',
     'c24': 'SOS guanine-nucleotide exchange factor',
     'c26': 'RAS GDP',
     'c28': 'RAS GTP',
     'c69': 'RAS GTP I',
     'c43': 'RAS Activated GTP',
     'c71': 'RAS Activated GTP I',
     'c31': 'Shc adapter protein',
     'c171': 'Erb B1 Erb B2 P GAP Shc adapter protein',
     'c172': 'Erb B1 Erb B3 P GAP Shc adapter protein',
     'c173': 'Erb B1 Erb B4 P GAP Shc adapter protein',
     'c174': 'Erb B1 Erb B2 P GAP Shc adapter protein',
     'c175': 'Erb B1 Erb B3 P GAP Shc adapter protein',
     'c176': 'Erb B1 Erb B4 P GAP Shc adapter protein',
     'c41': 'RAF',
     'c42': 'RAF RAS GTP',
     'c70': 'RAF RAS GTP I',
     'c72': 'RAF P I',
     'c45': 'source-defined RAF_P state',
     'c38': 'Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide exchange factor',
     'c30': 'Grb2 adapter protein SOS guanine-nucleotide exchange factor',
     'c44': 'source-defined PASE1 state',
     'c73': 'RAF P Pase1 I',
     'c46': 'RAF P Pase1',
     'c75': 'MEK P I',
     'c76': 'MEK P RAF P I',
     'c47': 'MEK',
     'c74': 'MEK RAF P I',
     'c48': 'MEK RAF P',
     'c49': 'source-defined MEK_P state',
     'c50': 'MEK P RAF P',
     'c51': 'MEK PP',
     'c77': 'MEK PP I',
     'c53': 'source-defined PASE2 state',
     'c78': 'MEK PP Pase2 I',
     'c52': 'MEK PP Pase2',
     'c54': 'MEK P Pase2',
     'c79': 'MEK P Pase2 I',
     'c55': 'ERK',
     'c56': 'ERK MEK PP',
     'c57': 'source-defined ERK_P state',
     'c58': 'ERK P MEK PP',
     'c80': 'MEK PP ERK',
     'c81': 'ERK P I',
     'c82': 'MEK PP ERK P',
     'c59': 'ERK PP',
     'c83': 'ERK PP I',
     'c60': 'source-defined PASE3 state',
     'c61': 'ERK PP Pase3',
     'c84': 'ERK PP Pase3 I',
     'c62': 'ERK P Pase3',
     'c85': 'ERK P Pase3 I',
     'c86': 'R Degraded',
     'c425': '2 Erb B2',
     'c13': 'EGF Degraded',
     'c518': 'heregulin Erb B3 Erb B1',
     'c519': 'heregulin Erb B4 Erb B1',
     'c339': 'Erb B3 Erb B2',
     'c340': 'Erb B4 Erb B2',
     'c95': '2 EGF Erb B1 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor ERK PP',
     'c96': '2 EGF Erb B1 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor ERK PP',
     'c97': '2 EGF Erb B1 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
            'exchange factor ERK PP',
     'c98': '2 EGF Erb B1 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
            'exchange factor ERK PP',
     'c101': 'ERK PP SOS guanine-nucleotide exchange factor',
     'c102': 'ERK PP SOS guanine-nucleotide exchange factor I',
     'c99': '2 EGF Erb B1 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor P',
     'c419': '2 EGF Erb B1 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor P',
     'c103': 'source-defined SOS_P state',
     'c100': '2 EGF Erb B1 P GAP Grb2 adapter protein SOS guanine-nucleotide exchange factor P',
     'c420': '2 EGF Erb B1 P GAP Shc adapter protein P Grb2 adapter protein SOS guanine-nucleotide '
             'exchange factor P',
     'c287': 'PI3K',
     'c486': '2 EGF Erb B1 P GAP Grb2 adapter protein Gab1 P',
     'c104': '2 EGF Erb B1 P GAP Grb2 adapter protein Gab1 P PI3K',
     'c447': 'Erb B1 Erb B4 P GAP Grb2 adapter protein Gab1 P',
     'c263': 'Erb B1 Erb B4 P GAP Grb2 adapter protein Gab1 P PI3K',
     'c445': 'Erb B1 Erb B2 P GAP Grb2 adapter protein Gab1 P',
     'c261': 'Erb B1 Erb B2 P GAP Grb2 adapter protein Gab1 P PI3K',
     'c446': 'Erb B1 Erb B3 P GAP Grb2 adapter protein Gab1 P',
     'c262': 'Erb B1 Erb B3 P GAP Grb2 adapter protein Gab1 P PI3K',
     'c454': '2 Erb B2 P GAP Grb2 adapter protein Gab1 P',
     'c324': '2 Erb B2 P GAP Grb2 adapter protein Gab1 P PI3K',
     'c457': 'Erb B3 Erb B2 P GAP Grb2 adapter protein Gab1 P',
     'c405': 'Erb B3 Erb B2 P GAP Grb2 adapter protein Gab1 P PI3K',
     'c460': 'Erb B4 Erb B2 P GAP Grb2 adapter protein Gab1 P',
     'c408': 'Erb B4 Erb B2 P GAP Grb2 adapter protein Gab1 P PI3K',
     'c106': 'source-defined PIP3 state',
     'c453': 'Erb B3 Erb B2 P GAP Grb2 adapter protein Gab1 P PI3K PIP2',
     'c452': '2 Erb B2 P GAP Grb2 adapter protein Gab1 P PI3K PIP2',
     'c448': '2 EGF Erb B1 P GAP Grb2 adapter protein Gab1 P PI3K PIP2',
     'c449': 'Erb B1 Erb B2 P GAP Grb2 adapter protein Gab1 P PI3K PIP2',
     'c450': 'Erb B1 Erb B3 P GAP Grb2 adapter protein Gab1 P PI3K PIP2',
     'c451': 'Erb B1 Erb B4 P GAP Grb2 adapter protein Gab1 P PI3K PIP2',
     'c467': 'Erb B3 Erb B2 P GAP Grb2 adapter protein Gab1 P PI3K PIP2 2',
     'c468': 'Erb B3 Erb B2 P GAP Grb2 adapter protein Gab1 P PI3K PIP2 3',
     'c469': 'Erb B3 Erb B2 P GAP Grb2 adapter protein Gab1 P PI3K PIP2 4',
     'c470': 'Erb B3 Erb B2 P GAP Grb2 adapter protein Gab1 P PI3K PIP2 5',
     'c471': 'Erb B3 Erb B2 P GAP Grb2 adapter protein Gab1 P PI3K PIP2 6',
     'c107': 'AKT',
     'c108': 'phosphorylated IP3 AKT',
     'c112': 'phosphorylated AKT',
     'c495': 'phosphorylated IP3 AKT P',
     'c109': 'source-defined PDK1 state',
     'c496': 'phosphorylated IP3 AKT P PDK1',
     'c110': 'phosphorylated IP3 AKT PDK1',
     'c111': 'phosphorylated IP3 PDK1',
     'c497': 'AKT P P',
     'c113': 'source-defined PASE4 state',
     'c498': 'AKT P P Pase4',
     'c114': 'AKT P Pase4',
     'c280': 'RTK Pase',
     'c281': 'Erb B1 Erb B3 P RTK Pase',
     'c282': 'Erb B1 Erb B4 P RTK Pase',
     'c415': '2 EGF Erb B1 P RTK Pase',
     'c283': '2 Erb B2 P RTK Pase',
     'c417': 'Erb B2 Erb B3 P RTK Pase',
     'c418': 'Erb B2 Erb B4 P RTK Pase',
     'c416': 'Erb B1 Erb B2 P RTK Pase',
     'c87': 'Erb B2 P',
     'c531': 'source-defined ERBB1 state',
     'c285': 'source-defined INH state',
     'c330': 'EGF Erb B1 P',
     'c331': 'Erb B3 P',
     'c332': 'Erb B4 P',
     'c509': 'Erb B2 Erb B2 Inh',
     'c510': 'Erb B3 Erb B2 Inh',
     'c511': 'Erb B4 Erb B2 Inh',
     'c513': 'Erb B4 Inh Erb B2',
     'c461': 'source-defined SHP state',
     'c444': 'source-defined PIP2 state',
     'c462': 'phosphorylated IP3 Shp',
     'c279': 'source-defined PTEN state',
     'c482': 'phosphorylated IP3 PTEN',
     'c426': 'source-defined GAB1 state',
     'c455': 'PI3K',
     'c463': 'source-defined SHP2 state',
     'c464': 'Erb B1 Erb B2 P GAP Grb2 adapter protein Gab1 P Shp2',
     'c465': 'Erb B1 Erb B3 P GAP Grb2 adapter protein Gab1 P Shp2',
     'c466': 'Erb B1 Erb B4 P GAP Grb2 adapter protein Gab1 P Shp2',
     'c473': '2 Erb B2 P GAP Grb2 adapter protein Gab1 P Shp2',
     'c476': 'Erb B3 Erb B2 P GAP Grb2 adapter protein Gab1 P Shp2',
     'c479': 'Erb B4 Erb B2 P GAP Grb2 adapter protein Gab1 P Shp2',
     'c489': '2 EGF Erb B1 P GAP Grb2 adapter protein Gab1 P Shp2',
     'c431': '2 EGF Erb B1 P GAP Grb2 adapter protein Gab1 P ERK PP',
     'c432': '2 EGF Erb B1 P GAP Grb2 adapter protein Gab1 P ERK PP I',
     'c433': 'Erb B1 Erb B2 P GAP Grb2 adapter protein Gab1 P ERK PP',
     'c434': 'Erb B1 Erb B2 P GAP Grb2 adapter protein Gab1 P ERK PP I',
     'c435': 'Erb B1 Erb B3 P GAP Grb2 adapter protein Gab1 P ERK PP',
     'c437': 'Erb B1 Erb B3 P GAP Grb2 adapter protein Gab1 P ERK PP I',
     'c438': 'Erb B1 Erb B4 P GAP Grb2 adapter protein Gab1 P ERK PP',
     'c440': 'Erb B1 Erb B4 P GAP Grb2 adapter protein Gab1 P ERK PP I',
     'c474': '2 Erb B2 P GAP Grb2 adapter protein Gab1 P ERK PP',
     'c475': '2 Erb B2 P GAP Grb2 adapter protein Gab1 P ERK PP I',
     'c477': 'Erb B3 Erb B2 P GAP Grb2 adapter protein Gab1 P ERK PP',
     'c478': 'Erb B3 Erb B2 P GAP Grb2 adapter protein Gab1 P ERK PP I',
     'c480': 'Erb B4 Erb B2 P GAP Grb2 adapter protein Gab1 P ERK PP',
     'c481': 'Erb B4 Erb B2 P GAP Grb2 adapter protein Gab1 P ERK PP I',
     'c491': 'Erb B3 4 Erb B2 Gab1 P',
     'c490': '2 Erb B2 2 Gab1 P',
     'c410': 'Erb B1 Erb B4 P GAP Grb2 adapter protein Gab1 P',
     'c409': 'Erb B1 Erb B3 P GAP Grb2 adapter protein Gab1 P',
     'c430': 'Erb B1 Erb B Gab1 P',
     'c488': '2 EGF Erb B1 Gab1 P',
     'c487': 'Erb B4 Erb B2 P GAP Grb2 adapter protein Gab1 PP',
     'c264': '2 EGF Erb B1 P GAP Grb2 adapter protein Gab1 P PI3K RAS GDP',
     'c265': 'Erb B1 Erb B2 P GAP Grb2 adapter protein Gab1 P PI3K RAS GDP',
     'c266': 'Erb B1 Erb B3 P GAP Grb2 adapter protein Gab1 P PI3K RAS GDP',
     'c267': 'Erb B1 Erb B4 P GAP Grb2 adapter protein Gab1 P PI3K RAS GDP',
     'c268': '2 Erb B2 P GAP Grb2 adapter protein Gab1 P PI3K RAS GDP',
     'c269': 'Erb B3 Erb B2 P GAP Grb2 adapter protein Gab1 P PI3K RAS GDP',
     'c325': 'Erb B4 Erb B2 P GAP Grb2 adapter protein Gab1 P PI3K RAS GDP',
     'c472': 'AKT P P RAF P Ser',
     'c484': 'AKT P P RAF P Ser I',
     'c485': 'RAF P Ser',
     'c520': 'MKP Deg',
     'c521': 'Pase9t',
     'c522': '2 EGF Erb B1 Gab1 P Pase9t',
     'c523': '2 Erb B2 2 Gab1 P Pase9t',
     'c411': 'Erb B1 Erb B3 P GAP Grb2 adapter protein Gab1 P Pase9t',
     'c412': 'Erb B1 Erb B4 P GAP Grb2 adapter protein Gab1 P Pase9t',
     'c456': 'Erb B3 4 Erb B2 Gab1 P Pase9t',
     'c424': 'Erb B1 Erb B Gab1 P Pase9t',
     'c407': 'Erb B4 Erb B2 P GAP Grb2 adapter protein Gab1 PP Pase9t',
     'c514': 'heregulin',
     'c142': 'heregulin Erb B3',
     'c144': 'heregulin Erb B4',
     'c158': 'heregulin Erb B4',
     'c532': 'Erb B1 H',
     'c525': 'Erb B1 H Inh',
     'c526': 'EGF Erb B1 H Inh',
     'c527': 'EGF Erb B1 ATP EGF Erb B1 H Inh',
     'c528': '2 EGF Erb B1 H Inh',
     'c524': 'Erb B1 H ATP',
     'c529': 'EGF Erb B1 H ATP',
     'c530': 'Erb B1 H ATP',
     'c115': 'EGF Erb B1 ATP EGF Erb B1 Inh Half active',
     'c121': 'EGF Erb B1 ATP EGF Erb B1 H Inh Half active',
     'c550': 'EGF Erb B1 ATP EGF Erb B1 H ATP',
     'c551': 'EGF Erb B1 Inh EGF Erb B1 H ATP',
     'c552': '2 EGF Erb B1 H ATP Full active',
     'c553': 'EGF Erb B1 ATP EGF Erb B1 H Inh',
     'c554': 'EGF Erb B1 Inh EGF Erb B1 H Inh',
     'c555': 'EGF Erb B1 ATP EGF Erb B1 H ATP Full active',
     'c556': 'EGF Erb B1 Inh EGF Erb B1 H ATP Half active',
     'c557': '2 EGF Erb B1 H ATP Full active',
     'c558': 'EGF Erb B1 ATP EGF Erb B1 H Inh Half active'}
    _STATE_OUTPUT_ALIASES = {'c1': 'egf',
     'c2': 'erb_b1_atp',
     'c3': 'egf_erb_b1_atp',
     'c288': 'erb_b2_erb_b3',
     'c335': 'erb_b3_erb_b2_p',
     'c117': 'erb_b2_erb_b4',
     'c336': 'erb_b4_erb_b2_p',
     'c286': 'erb_b1_inh',
     'c499': 'egf_erb_b1_inh',
     'c500': 'egf_erb_b1_atp_egf_erb_b1_inh',
     'c501': 'source_2_egf_erb_b1_inh',
     'c4': 'source_2_egf_erb_b1_atp',
     'c10': 'egf_erb_b1_atp_2',
     'c11': 'source_2_egf_erb_b1_atp_2',
     'c141': 'source_defined_erbb2_state',
     'c145': 'egf_erb_b1_erb_b2',
     'c140': 'source_defined_erbb3_state',
     'c146': 'egf_erb_b1_erb_b3',
     'c143': 'source_defined_erbb4_state',
     'c147': 'egf_erb_b1_erb_b4',
     'c155': 'source_defined_erbb2_state_2',
     'c159': 'egf_erb_b1_erb_b2_2',
     'c154': 'source_defined_erbb3_state_2',
     'c160': 'egf_erb_b1_erb_b3_2',
     'c156': 'source_defined_erbb4_state_2',
     'c161': 'egf_erb_b1_erb_b4_2',
     'c492': 'egf_erb_b1_inh_er_b2',
     'c493': 'egf_erb_b1_inh_er_b3',
     'c494': 'egf_erb_b1_inh_er_b4',
     'c502': 'erb_b2_inh',
     'c504': 'egf_erb_b1_erb_b2_inh',
     'c503': 'erb_b4_inh',
     'c505': 'egf_erb_b1_erb_b3_p_inh',
     'c506': 'erb_b3_inh',
     'c507': 'egf_erb_b1_erb_b3_p_inh_2',
     'c105': 'atp_1_2e9',
     'c123': 'egf_erb_b1_erb_b2_atp',
     'c124': 'egf_erb_b1_erb_b3_atp',
     'c125': 'egf_erb_b1_erb_b4_atp',
     'c126': 'source_2_egf_erb_b1_atp_3',
     'c116': 'source_2_egf_erb_b1_atp_full_active',
     'c122': 'egf_erb_b1_erb_b2_atp_2',
     'c127': 'egf_erb_b1_erb_b3_atp_2',
     'c128': 'egf_erb_b1_erb_b4_atp_2',
     'c284': 'erb_b2_erb_b2_p',
     'c129': 'erb_b2_erb_b2_p_atp',
     'c427': 'erb_b1_erb_b2_p_gap_grb2_adapter_protein_gab1',
     'c130': 'erb_b1_erb_b2_p_gap_grb2_adapter_protein_gab1_atp',
     'c428': 'erb_b1_erb_b3_p_gap_grb2_adapter_protein_gab1',
     'c131': 'erb_b1_erb_b3_p_gap_grb2_adapter_protein_gab1_atp',
     'c429': 'erb_b1_erb_b4_p_gap_grb2_adapter_protein_gab1',
     'c132': 'erb_b1_erb_b4_p_gap_grb2_adapter_protein_gab1_atp',
     'c436': 'source_2_erb_b2_p_gap_grb2_adapter_protein_gab1',
     'c133': 'source_2_erb_b2_p_gap_grb2_adapter_protein_gab1_atp',
     'c439': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein_gab1',
     'c134': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein_gab1_atp',
     'c442': 'erb_b4_erb_b2_p_gap_grb2_adapter_protein_gab1',
     'c135': 'erb_b4_erb_b2_p_gap_grb2_adapter_protein_gab1_atp',
     'c483': 'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_gab1',
     'c136': 'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_gab1_atp',
     'c516': 'heregulin_erb_b3_erb_b1',
     'c137': 'heregulin_erb_b3_erb_b1_atp',
     'c517': 'heregulin_erb_b4_erb_b1',
     'c138': 'heregulin_erb_b4_erb_b1_atp',
     'c345': 'heregulin_erb_b4_erb_b2',
     'c139': 'heregulin_erb_b4_erb_b2_atp',
     'c355': 'heregulin_erb_b3_erb_b2',
     'c168': 'heregulin_erb_b3_erb_b2_atp',
     'c421': 'heregulin_erb_b3_erb_b2_2',
     'c169': 'heregulin_erb_b3_erb_b2_atp_2',
     'c422': 'heregulin_erb_b4_erb_b2_2',
     'c170': 'heregulin_erb_b4_erb_b2_atp_2',
     'c23': 'source_2_egf_erb_b1_p_gap_grb2_adapter_protein',
     'c12': 'source_defined_cpp_state',
     'c7': 'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_c_pp',
     'c25': 'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor',
     'c88': 'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_c_pp',
     'c27': 'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp',
     'c89': 'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_c_pp',
     'c29': 'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp',
     'c90': 'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_c_pp',
     'c34': 'source_2_egf_erb_b1_p_gap_shc_adapter_protein_p_grb2_adapter_protein',
     'c91': 'source_2_egf_erb_b1_p_gap_shc_adapter_protein_p_grb2_adapter_protein_c_pp',
     'c35': 'source_2_egf_erb_b1_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor',
     'c92': 'source_2_egf_erb_b1_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_c_pp',
     'c36': 'source_2_egf_erb_b1_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp',
     'c93': 'source_2_egf_erb_b1_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_c_pp',
     'c37': 'source_2_egf_erb_b1_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp',
     'c94': 'source_2_egf_erb_b1_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_c_pp',
     'c189': 'erb_b1_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein',
     'c195': 'erb_b1_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_c_pp',
     'c190': 'erb_b1_erb_b3_p_gap_shc_adapter_protein_p_grb2_adapter_protein',
     'c196': 'erb_b1_erb_b3_p_gap_shc_adapter_protein_p_grb2_adapter_protein_c_pp',
     'c191': 'erb_b1_erb_b4_p_gap_shc_adapter_protein_p_grb2_adapter_protein',
     'c197': 'erb_b1_erb_b4_p_gap_shc_adapter_protein_p_grb2_adapter_protein_c_pp',
     'c198': 'erb_b1_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor',
     'c204': 'erb_b1_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_c_pp',
     'c199': 'erb_b1_erb_b3_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor',
     'c205': 'erb_b1_erb_b3_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_c_pp',
     'c200': 'erb_b1_erb_b4_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor',
     'c206': 'erb_b1_erb_b4_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_c_pp',
     'c207': 'erb_b1_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp',
     'c213': 'erb_b1_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_c_pp',
     'c208': 'erb_b1_erb_b3_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp',
     'c214': 'erb_b1_erb_b3_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_c_pp',
     'c209': 'erb_b1_erb_b4_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp',
     'c215': 'erb_b1_erb_b4_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_c_pp',
     'c216': 'erb_b1_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp',
     'c222': 'erb_b1_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_c_pp',
     'c217': 'erb_b1_erb_b3_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp',
     'c223': 'erb_b1_erb_b3_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_c_pp',
     'c218': 'erb_b1_erb_b4_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp',
     'c224': 'erb_b1_erb_b4_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_c_pp',
     'c225': 'erb_b1_erb_b2_p_gap_grb2_adapter_protein',
     'c231': 'erb_b1_erb_b2_p_gap_grb2_adapter_protein_c_pp',
     'c226': 'erb_b1_erb_b3_p_gap_grb2_adapter_protein',
     'c232': 'erb_b1_erb_b3_p_gap_grb2_adapter_protein_c_pp',
     'c227': 'erb_b1_erb_b4_p_gap_grb2_adapter_protein',
     'c233': 'erb_b1_erb_b4_p_gap_grb2_adapter_protein_c_pp',
     'c243': 'erb_b1_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp',
     'c249': 'erb_b1_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_c_pp',
     'c244': 'erb_b1_erb_b3_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp',
     'c250': 'erb_b1_erb_b3_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_c_pp',
     'c245': 'erb_b1_erb_b4_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp',
     'c251': 'erb_b1_erb_b4_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_c_pp',
     'c252': 'erb_b1_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp',
     'c258': 'erb_b1_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_c_pp',
     'c253': 'erb_b1_erb_b3_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp',
     'c259': 'erb_b1_erb_b3_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_c_pp',
     'c254': 'erb_b1_erb_b4_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp',
     'c260': 'erb_b1_erb_b4_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_c_pp',
     'c234': 'erb_b1_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor',
     'c240': 'erb_b1_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_c_pp',
     'c235': 'erb_b1_erb_b3_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor',
     'c241': 'erb_b1_erb_b3_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_c_pp',
     'c236': 'erb_b1_erb_b4_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor',
     'c242': 'erb_b1_erb_b4_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_c_pp',
     'c300': 'source_2_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein',
     'c301': 'source_2_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_c_pp',
     'c303': 'source_2_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor',
     'c304': 'source_2_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_c_pp',
     'c306': 'source_2_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp',
     'c307': 'source_2_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_c_pp',
     'c309': 'source_2_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp',
     'c310': 'source_2_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_c_pp',
     'c312': 'source_2_erb_b2_p_gap_grb2_adapter_protein',
     'c313': 'source_2_erb_b2_p_gap_grb2_adapter_protein_c_pp',
     'c315': 'source_2_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor',
     'c316': 'source_2_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_c_pp',
     'c318': 'source_2_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp',
     'c319': 'source_2_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_c_pp',
     'c321': 'source_2_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp',
     'c322': 'source_2_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_c_pp',
     'c357': 'erb_b3_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein',
     'c358': 'erb_b3_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_c_pp',
     'c360': 'erb_b4_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein',
     'c361': 'erb_b4_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_c_pp',
     'c366': 'erb_b4_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor',
     'c367': 'erb_b4_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_c_pp',
     'c369': 'erb_b3_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp',
     'c370': 'erb_b3_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_c_pp',
     'c372': 'erb_b4_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp',
     'c373': 'erb_b4_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_c_pp',
     'c375': 'erb_b3_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp',
     'c376': 'erb_b3_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_c_pp',
     'c378': 'erb_b4_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp',
     'c379': 'erb_b4_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_c_pp',
     'c381': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein',
     'c382': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein_c_pp',
     'c363': 'erb_b3_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor',
     'c364': 'erb_b3_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_c_pp',
     'c384': 'erb_b4_erb_b2_p_gap_grb2_adapter_protein',
     'c385': 'erb_b4_erb_b2_p_gap_grb2_adapter_protein_c_pp',
     'c387': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor',
     'c388': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_c_pp',
     'c390': 'erb_b4_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor',
     'c391': 'erb_b4_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_c_pp',
     'c393': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp',
     'c394': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_c_pp',
     'c396': 'erb_b4_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp',
     'c397': 'erb_b4_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_c_pp',
     'c399': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp',
     'c400': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_c_pp',
     'c402': 'erb_b4_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp',
     'c403': 'erb_b4_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_c_pp',
     'c9': 'source_defined_cpp_state_2',
     'c404': 'erb_b4_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_2',
     'c401': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_2',
     'c398': 'erb_b4_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_2',
     'c395': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_2',
     'c392': 'erb_b4_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_2',
     'c389': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_2',
     'c386': 'erb_b4_erb_b2_p_gap_grb2_adapter_protein_2',
     'c365': 'erb_b3_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_2',
     'c383': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein_2',
     'c380': 'erb_b4_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_2',
     'c377': 'erb_b3_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_2',
     'c374': 'erb_b4_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_2',
     'c371': 'erb_b3_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_2',
     'c368': 'erb_b4_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_2',
     'c362': 'erb_b4_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_2',
     'c359': 'erb_b3_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_2',
     'c323': 'source_2_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_2',
     'c320': 'source_2_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_2',
     'c317': 'source_2_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_2',
     'c314': 'source_2_erb_b2_p_gap_grb2_adapter_protein_2',
     'c311': 'source_2_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_2',
     'c308': 'source_2_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_2',
     'c305': 'source_2_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_2',
     'c302': 'source_2_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_2',
     'c239': 'erb_b1_erb_b4_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_2',
     'c238': 'erb_b1_erb_b3_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_2',
     'c237': 'erb_b1_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_2',
     'c257': 'erb_b1_erb_b4_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_2',
     'c256': 'erb_b1_erb_b3_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_2',
     'c255': 'erb_b1_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_2',
     'c248': 'erb_b1_erb_b4_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_2',
     'c247': 'erb_b1_erb_b3_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_2',
     'c246': 'erb_b1_erb_b2_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_2',
     'c230': 'erb_b1_erb_b4_p_gap_grb2_adapter_protein_2',
     'c229': 'erb_b1_erb_b3_p_gap_grb2_adapter_protein_2',
     'c228': 'erb_b1_erb_b2_p_gap_grb2_adapter_protein_2',
     'c221': 'erb_b1_erb_b4_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_2',
     'c220': 'erb_b1_erb_b3_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_2',
     'c219': 'erb_b1_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_2',
     'c212': 'erb_b1_erb_b4_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_2',
     'c211': 'erb_b1_erb_b3_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_2',
     'c210': 'erb_b1_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_2',
     'c203': 'erb_b1_erb_b4_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_2',
     'c202': 'erb_b1_erb_b3_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_2',
     'c201': 'erb_b1_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_2',
     'c194': 'erb_b1_erb_b4_p_gap_shc_adapter_protein_p_grb2_adapter_protein_2',
     'c193': 'erb_b1_erb_b3_p_gap_shc_adapter_protein_p_grb2_adapter_protein_2',
     'c192': 'erb_b1_erb_b2_p_gap_shc_adapter_protein_p_grb2_adapter_protein_2',
     'c68': 'source_2_egf_erb_b1_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_2',
     'c67': 'source_2_egf_erb_b1_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_2',
     'c66': 'source_2_egf_erb_b1_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_2',
     'c65': 'source_2_egf_erb_b1_p_gap_shc_adapter_protein_p_grb2_adapter_protein_2',
     'c21': 'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gtp_2',
     'c20': 'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp_2',
     'c18': 'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_2',
     'c19': 'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_2',
     'c6': 'erb_b1_atp_2',
     'c5': 'source_2_egf_erb_b1_p',
     'c8': 'source_2_egf_erb_b1_p_2',
     'c15': 'source_2_egf_erb_b1_p_gap',
     'c17': 'source_2_egf_erb_b1_p_gap_2',
     'c32': 'source_2_egf_erb_b1_p_gap_shc_adapter_protein',
     'c63': 'source_2_egf_erb_b1_p_gap_shc_adapter_protein_2',
     'c33': 'source_2_egf_erb_b1_p_gap_shc_adapter_protein_p',
     'c64': 'source_2_egf_erb_b1_p_gap_shc_adapter_protein_p_2',
     'c347': 'erb_b3_erb_b2_p_gap_shc_adapter_protein',
     'c349': 'erb_b3_erb_b2_p_gap_shc_adapter_protein_2',
     'c348': 'erb_b4_erb_b2_p_gap_shc_adapter_protein',
     'c350': 'erb_b4_erb_b2_p_gap_shc_adapter_protein_2',
     'c351': 'erb_b3_erb_b2_p_gap_shc_adapter_protein_p',
     'c353': 'erb_b3_erb_b2_p_gap_shc_adapter_protein_p_2',
     'c508': 'erb_b2_inh_2',
     'c512': 'erb_b4_inh_2',
     'c354': 'erb_b4_erb_b2_p_gap_shc_adapter_protein_p',
     'c356': 'erb_b4_erb_b2_p_gap_shc_adapter_protein_p_2',
     'c148': 'erb_b1_erb_b2_p',
     'c162': 'erb_b1_erb_b2_p_2',
     'c149': 'erb_b1_erb_b3_p',
     'c163': 'erb_b1_erb_b3_p_2',
     'c150': 'erb_b1_erb_b4_p',
     'c164': 'erb_b1_erb_b4_p_2',
     'c289': 'source_2_erb_b2_p',
     'c290': 'source_2_erb_b2_p_2',
     'c337': 'erb_b3_erb_b2_p_2',
     'c338': 'erb_b4_erb_b2_p_2',
     'c291': 'source_2_erb_b2_p_gap',
     'c293': 'source_2_erb_b2_p_gap_2',
     'c294': 'source_2_erb_b2_p_gap_shc_adapter_protein',
     'c296': 'source_2_erb_b2_p_gap_shc_adapter_protein_2',
     'c297': 'source_2_erb_b2_p_gap_shc_adapter_protein_p',
     'c299': 'source_2_erb_b2_p_gap_shc_adapter_protein_p_2',
     'c14': 'source_defined_gap_state',
     'c165': 'erb_b1_erb_b2_p_gap',
     'c166': 'erb_b1_erb_b3_p_gap',
     'c167': 'erb_b1_erb_b4_p_gap',
     'c151': 'erb_b1_erb_b2_p_gap_2',
     'c152': 'erb_b1_erb_b3_p_gap_2',
     'c153': 'erb_b1_erb_b4_p_gap_2',
     'c341': 'erb_b3_erb_b2_p_gap',
     'c344': 'erb_b4_erb_b2_p_gap',
     'c343': 'erb_b3_erb_b2_p_gap_2',
     'c346': 'erb_b4_erb_b2_p_gap_2',
     'c16': 'egf_2',
     'c515': 'heregulin',
     'c157': 'heregulin_erb_b3',
     'c22': 'grb2_adapter_protein',
     'c40': 'source_defined_shc_p_state',
     'c39': 'shc_adapter_protein_p_grb2_adapter_protein',
     'c180': 'erb_b1_erb_b2_p_gap_shc_adapter_protein_p',
     'c181': 'erb_b1_erb_b3_p_gap_shc_adapter_protein_p',
     'c182': 'erb_b1_erb_b4_p_gap_shc_adapter_protein_p',
     'c183': 'erb_b1_erb_b2_p_gap_shc_adapter_protein_p_2',
     'c184': 'erb_b1_erb_b3_p_gap_shc_adapter_protein_p_2',
     'c185': 'erb_b1_erb_b4_p_gap_shc_adapter_protein_p_2',
     'c24': 'sos_guanine_nucleotide_exchange_factor',
     'c26': 'ras_gdp',
     'c28': 'ras_gtp',
     'c69': 'ras_gtp_i',
     'c43': 'ras_activated_gtp',
     'c71': 'ras_activated_gtp_i',
     'c31': 'shc_adapter_protein',
     'c171': 'erb_b1_erb_b2_p_gap_shc_adapter_protein',
     'c172': 'erb_b1_erb_b3_p_gap_shc_adapter_protein',
     'c173': 'erb_b1_erb_b4_p_gap_shc_adapter_protein',
     'c174': 'erb_b1_erb_b2_p_gap_shc_adapter_protein_2',
     'c175': 'erb_b1_erb_b3_p_gap_shc_adapter_protein_2',
     'c176': 'erb_b1_erb_b4_p_gap_shc_adapter_protein_2',
     'c41': 'raf',
     'c42': 'raf_ras_gtp',
     'c70': 'raf_ras_gtp_i',
     'c72': 'raf_p_i',
     'c45': 'source_defined_raf_p_state',
     'c38': 'shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor',
     'c30': 'grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor',
     'c44': 'source_defined_pase1_state',
     'c73': 'raf_p_pase1_i',
     'c46': 'raf_p_pase1',
     'c75': 'mek_p_i',
     'c76': 'mek_p_raf_p_i',
     'c47': 'mek',
     'c74': 'mek_raf_p_i',
     'c48': 'mek_raf_p',
     'c49': 'source_defined_mek_p_state',
     'c50': 'mek_p_raf_p',
     'c51': 'mek_pp',
     'c77': 'mek_pp_i',
     'c53': 'source_defined_pase2_state',
     'c78': 'mek_pp_pase2_i',
     'c52': 'mek_pp_pase2',
     'c54': 'mek_p_pase2',
     'c79': 'mek_p_pase2_i',
     'c55': 'erk',
     'c56': 'erk_mek_pp',
     'c57': 'source_defined_erk_p_state',
     'c58': 'erk_p_mek_pp',
     'c80': 'mek_pp_erk',
     'c81': 'erk_p_i',
     'c82': 'mek_pp_erk_p',
     'c59': 'erk_pp',
     'c83': 'erk_pp_i',
     'c60': 'source_defined_pase3_state',
     'c61': 'erk_pp_pase3',
     'c84': 'erk_pp_pase3_i',
     'c62': 'erk_p_pase3',
     'c85': 'erk_p_pase3_i',
     'c86': 'r_degraded',
     'c425': 'source_2_erb_b2',
     'c13': 'egf_degraded',
     'c518': 'heregulin_erb_b3_erb_b1_2',
     'c519': 'heregulin_erb_b4_erb_b1_2',
     'c339': 'erb_b3_erb_b2',
     'c340': 'erb_b4_erb_b2',
     'c95': 'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_erk_pp',
     'c96': 'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_erk_pp_2',
     'c97': 'source_2_egf_erb_b1_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_erk_pp',
     'c98': 'source_2_egf_erb_b1_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_erk_pp_2',
     'c101': 'erk_pp_sos_guanine_nucleotide_exchange_factor',
     'c102': 'erk_pp_sos_guanine_nucleotide_exchange_factor_i',
     'c99': 'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_p',
     'c419': 'source_2_egf_erb_b1_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_p',
     'c103': 'source_defined_sos_p_state',
     'c100': 'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_p_2',
     'c420': 'source_2_egf_erb_b1_p_gap_shc_adapter_protein_p_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_p_2',
     'c287': 'pi3k',
     'c486': 'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_gab1_p',
     'c104': 'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_gab1_p_pi3k',
     'c447': 'erb_b1_erb_b4_p_gap_grb2_adapter_protein_gab1_p',
     'c263': 'erb_b1_erb_b4_p_gap_grb2_adapter_protein_gab1_p_pi3k',
     'c445': 'erb_b1_erb_b2_p_gap_grb2_adapter_protein_gab1_p',
     'c261': 'erb_b1_erb_b2_p_gap_grb2_adapter_protein_gab1_p_pi3k',
     'c446': 'erb_b1_erb_b3_p_gap_grb2_adapter_protein_gab1_p',
     'c262': 'erb_b1_erb_b3_p_gap_grb2_adapter_protein_gab1_p_pi3k',
     'c454': 'source_2_erb_b2_p_gap_grb2_adapter_protein_gab1_p',
     'c324': 'source_2_erb_b2_p_gap_grb2_adapter_protein_gab1_p_pi3k',
     'c457': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein_gab1_p',
     'c405': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein_gab1_p_pi3k',
     'c460': 'erb_b4_erb_b2_p_gap_grb2_adapter_protein_gab1_p',
     'c408': 'erb_b4_erb_b2_p_gap_grb2_adapter_protein_gab1_p_pi3k',
     'c106': 'source_defined_pip3_state',
     'c453': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein_gab1_p_pi3k_pip2',
     'c452': 'source_2_erb_b2_p_gap_grb2_adapter_protein_gab1_p_pi3k_pip2',
     'c448': 'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_gab1_p_pi3k_pip2',
     'c449': 'erb_b1_erb_b2_p_gap_grb2_adapter_protein_gab1_p_pi3k_pip2',
     'c450': 'erb_b1_erb_b3_p_gap_grb2_adapter_protein_gab1_p_pi3k_pip2',
     'c451': 'erb_b1_erb_b4_p_gap_grb2_adapter_protein_gab1_p_pi3k_pip2',
     'c467': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein_gab1_p_pi3k_pip2_2',
     'c468': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein_gab1_p_pi3k_pip2_3',
     'c469': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein_gab1_p_pi3k_pip2_4',
     'c470': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein_gab1_p_pi3k_pip2_5',
     'c471': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein_gab1_p_pi3k_pip2_6',
     'c107': 'akt',
     'c108': 'phosphorylated_ip3_akt',
     'c112': 'phosphorylated_akt',
     'c495': 'phosphorylated_ip3_akt_p',
     'c109': 'source_defined_pdk1_state',
     'c496': 'phosphorylated_ip3_akt_p_pdk1',
     'c110': 'phosphorylated_ip3_akt_pdk1',
     'c111': 'phosphorylated_ip3_pdk1',
     'c497': 'akt_p_p',
     'c113': 'source_defined_pase4_state',
     'c498': 'akt_p_p_pase4',
     'c114': 'akt_p_pase4',
     'c280': 'rtk_pase',
     'c281': 'erb_b1_erb_b3_p_rtk_pase',
     'c282': 'erb_b1_erb_b4_p_rtk_pase',
     'c415': 'source_2_egf_erb_b1_p_rtk_pase',
     'c283': 'source_2_erb_b2_p_rtk_pase',
     'c417': 'erb_b2_erb_b3_p_rtk_pase',
     'c418': 'erb_b2_erb_b4_p_rtk_pase',
     'c416': 'erb_b1_erb_b2_p_rtk_pase',
     'c87': 'erb_b2_p',
     'c531': 'source_defined_erbb1_state',
     'c285': 'source_defined_inh_state',
     'c330': 'egf_erb_b1_p',
     'c331': 'erb_b3_p',
     'c332': 'erb_b4_p',
     'c509': 'erb_b2_erb_b2_inh',
     'c510': 'erb_b3_erb_b2_inh',
     'c511': 'erb_b4_erb_b2_inh',
     'c513': 'erb_b4_inh_erb_b2',
     'c461': 'source_defined_shp_state',
     'c444': 'source_defined_pip2_state',
     'c462': 'phosphorylated_ip3_shp',
     'c279': 'source_defined_pten_state',
     'c482': 'phosphorylated_ip3_pten',
     'c426': 'source_defined_gab1_state',
     'c455': 'pi3k_2',
     'c463': 'source_defined_shp2_state',
     'c464': 'erb_b1_erb_b2_p_gap_grb2_adapter_protein_gab1_p_shp2',
     'c465': 'erb_b1_erb_b3_p_gap_grb2_adapter_protein_gab1_p_shp2',
     'c466': 'erb_b1_erb_b4_p_gap_grb2_adapter_protein_gab1_p_shp2',
     'c473': 'source_2_erb_b2_p_gap_grb2_adapter_protein_gab1_p_shp2',
     'c476': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein_gab1_p_shp2',
     'c479': 'erb_b4_erb_b2_p_gap_grb2_adapter_protein_gab1_p_shp2',
     'c489': 'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_gab1_p_shp2',
     'c431': 'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_gab1_p_erk_pp',
     'c432': 'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_gab1_p_erk_pp_i',
     'c433': 'erb_b1_erb_b2_p_gap_grb2_adapter_protein_gab1_p_erk_pp',
     'c434': 'erb_b1_erb_b2_p_gap_grb2_adapter_protein_gab1_p_erk_pp_i',
     'c435': 'erb_b1_erb_b3_p_gap_grb2_adapter_protein_gab1_p_erk_pp',
     'c437': 'erb_b1_erb_b3_p_gap_grb2_adapter_protein_gab1_p_erk_pp_i',
     'c438': 'erb_b1_erb_b4_p_gap_grb2_adapter_protein_gab1_p_erk_pp',
     'c440': 'erb_b1_erb_b4_p_gap_grb2_adapter_protein_gab1_p_erk_pp_i',
     'c474': 'source_2_erb_b2_p_gap_grb2_adapter_protein_gab1_p_erk_pp',
     'c475': 'source_2_erb_b2_p_gap_grb2_adapter_protein_gab1_p_erk_pp_i',
     'c477': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein_gab1_p_erk_pp',
     'c478': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein_gab1_p_erk_pp_i',
     'c480': 'erb_b4_erb_b2_p_gap_grb2_adapter_protein_gab1_p_erk_pp',
     'c481': 'erb_b4_erb_b2_p_gap_grb2_adapter_protein_gab1_p_erk_pp_i',
     'c491': 'erb_b3_4_erb_b2_gab1_p',
     'c490': 'source_2_erb_b2_2_gab1_p',
     'c410': 'erb_b1_erb_b4_p_gap_grb2_adapter_protein_gab1_p_2',
     'c409': 'erb_b1_erb_b3_p_gap_grb2_adapter_protein_gab1_p_2',
     'c430': 'erb_b1_erb_b_gab1_p',
     'c488': 'source_2_egf_erb_b1_gab1_p',
     'c487': 'erb_b4_erb_b2_p_gap_grb2_adapter_protein_gab1_pp',
     'c264': 'source_2_egf_erb_b1_p_gap_grb2_adapter_protein_gab1_p_pi3k_ras_gdp',
     'c265': 'erb_b1_erb_b2_p_gap_grb2_adapter_protein_gab1_p_pi3k_ras_gdp',
     'c266': 'erb_b1_erb_b3_p_gap_grb2_adapter_protein_gab1_p_pi3k_ras_gdp',
     'c267': 'erb_b1_erb_b4_p_gap_grb2_adapter_protein_gab1_p_pi3k_ras_gdp',
     'c268': 'source_2_erb_b2_p_gap_grb2_adapter_protein_gab1_p_pi3k_ras_gdp',
     'c269': 'erb_b3_erb_b2_p_gap_grb2_adapter_protein_gab1_p_pi3k_ras_gdp',
     'c325': 'erb_b4_erb_b2_p_gap_grb2_adapter_protein_gab1_p_pi3k_ras_gdp',
     'c472': 'akt_p_p_raf_p_ser',
     'c484': 'akt_p_p_raf_p_ser_i',
     'c485': 'raf_p_ser',
     'c520': 'mkp_deg',
     'c521': 'pase9t',
     'c522': 'source_2_egf_erb_b1_gab1_p_pase9t',
     'c523': 'source_2_erb_b2_2_gab1_p_pase9t',
     'c411': 'erb_b1_erb_b3_p_gap_grb2_adapter_protein_gab1_p_pase9t',
     'c412': 'erb_b1_erb_b4_p_gap_grb2_adapter_protein_gab1_p_pase9t',
     'c456': 'erb_b3_4_erb_b2_gab1_p_pase9t',
     'c424': 'erb_b1_erb_b_gab1_p_pase9t',
     'c407': 'erb_b4_erb_b2_p_gap_grb2_adapter_protein_gab1_pp_pase9t',
     'c514': 'heregulin_2',
     'c142': 'heregulin_erb_b3_2',
     'c144': 'heregulin_erb_b4',
     'c158': 'heregulin_erb_b4_2',
     'c532': 'erb_b1_h',
     'c525': 'erb_b1_h_inh',
     'c526': 'egf_erb_b1_h_inh',
     'c527': 'egf_erb_b1_atp_egf_erb_b1_h_inh',
     'c528': 'source_2_egf_erb_b1_h_inh',
     'c524': 'erb_b1_h_atp',
     'c529': 'egf_erb_b1_h_atp',
     'c530': 'erb_b1_h_atp_2',
     'c115': 'egf_erb_b1_atp_egf_erb_b1_inh_half_active',
     'c121': 'egf_erb_b1_atp_egf_erb_b1_h_inh_half_active',
     'c550': 'egf_erb_b1_atp_egf_erb_b1_h_atp',
     'c551': 'egf_erb_b1_inh_egf_erb_b1_h_atp',
     'c552': 'source_2_egf_erb_b1_h_atp_full_active',
     'c553': 'egf_erb_b1_atp_egf_erb_b1_h_inh_2',
     'c554': 'egf_erb_b1_inh_egf_erb_b1_h_inh',
     'c555': 'egf_erb_b1_atp_egf_erb_b1_h_atp_full_active',
     'c556': 'egf_erb_b1_inh_egf_erb_b1_h_atp_half_active',
     'c557': 'source_2_egf_erb_b1_h_atp_full_active_2',
     'c558': 'egf_erb_b1_atp_egf_erb_b1_h_inh_half_active_2'}

    def __init__(self, model_path: str = 'data/BIOMD0000000255.xml', integration_step: float = 0.01) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


Chen2009ErbbSignalingBiomd0000000255Model = Chen2009ErbbSignalingModel
