# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML wrapper for Caruso2020 - Activation of the alternative complement pathway and effects on hemolysis."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Caruso2020ActivationOfTheAlternativeComplemModel(TelluriumSBMLBioModule):
    """Faithful Tellurium execution of the bundled SBML source model."""

    _SBML_ID = 'MODEL2109110001'
    _TITLE = 'Caruso2020 - Activation of the alternative complement pathway and effects on hemolysis'
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _HEADLINE_OUTPUTS = {'nf_complement_c3b': ('nfC3b',
                           'native SBML value',
                           'Nf complement C3b. Maps to SBML symbol `nfC3b` and is emitted in native '
                           'SBML units.'),
     'complement_c3_h2o_fluid': ('C3_H2O__fluid',
                                 'native SBML value',
                                 'complement C3 H2O Fluid. Maps to SBML symbol `C3_H2O__fluid` and is '
                                 'emitted in native SBML units.'),
     'complement_c3_h2o_b_fluid': ('C3_H2O_B_fluid',
                                   'native SBML value',
                                   'complement C3 H2O B Fluid. Maps to SBML symbol `C3_H2O_B_fluid` '
                                   'and is emitted in native SBML units.')}
    _INITIAL_CONDITION_INPUTS = {'initial_complement_c3': ('C3',
                               0.0,
                               'native SBML value',
                               'Initial level of complement C3. Maps to SBML symbol `C3`; exposed as a '
                               'traceable initial-condition perturbation.')}
    _PARAMETER_INPUTS = {}
    _SPECIES_LABELS = {'C3': 'complement C3',
     'C3_H2O__fluid': 'complement C3 H2O Fluid',
     'B': 'source-defined B state',
     'C3_H2O_B_fluid': 'complement C3 H2O B Fluid',
     'C3_H2O_H_fluid': 'complement C3 H2O H Fluid',
     'H': 'source-defined H state',
     'C3_H2O_CR1_fluid': 'complement C3 H2O CR1 Fluid',
     'CR1': 'source-defined CR1 state',
     'Bb': 'complement factor Bb',
     'C3_H2O_Bb_fluid': 'complement C3 H2O complement factor Bb Fluid',
     'C3_H2O_BbH_fluid': 'complement C3 H2O complement factor Bb H Fluid',
     'Ba': 'source-defined BA state',
     'D': 'source-defined D state',
     'C3b_fluid': 'complement C3b Fluid',
     'H2O': 'H2O',
     'nfC3b': 'Nf complement C3b',
     'nhC3b': 'Nh complement C3b',
     'C3bB_fluid': 'complement C3b B Fluid',
     'C3bH_fluid': 'complement C3b H Fluid',
     'C3bCR1_fluid': 'complement C3b CR1 Fluid',
     'C3bBb_fluid': 'complement C3b complement factor Bb Fluid',
     'C3bBbH_fluid': 'complement C3b complement factor Bb H Fluid',
     'C3bBbCR1_fluid': 'complement C3b complement factor Bb CR1 Fluid',
     'C3a': 'C3a',
     'I': 'source-defined I state',
     'iC3b_fluid': 'I complement C3b Fluid',
     'iC3bCR1_fluid': 'I complement C3b CR1 Fluid',
     'C3dg_fluid': 'C3dg Fluid',
     'C5b7_micelle': 'C5b7 Micelle',
     'hC5b7_fluid': 'H C5b7 Fluid',
     'C5b8_fluid': 'C5b8 Fluid',
     'C8': 'source-defined C8 state',
     'Cn': 'source-defined CN state',
     'CnC5b7_fluid': 'Cn C5b7 Fluid',
     'Vn': 'source-defined VN state',
     'VnC5b7_fluid': 'Vn C5b7 Fluid',
     'C9': 'source-defined C9 state',
     'VnC5b8_fluid': 'Vn C5b8 Fluid',
     'VnC5b9_1_fluid': 'Vn C5b9 1 Fluid',
     'CnC5b8_fluid': 'Cn C5b8 Fluid',
     'CnC5b9_1_fluid': 'Cn C5b9 1 Fluid',
     'C5b9_1_fluid': 'C5b9 1 Fluid',
     'C3bBbC3b_host': 'complement C3b complement factor Bb complement C3b Host',
     'C3bBb_host': 'complement C3b complement factor Bb Host',
     'C3bBbC3bCR1_host': 'complement C3b complement factor Bb complement C3b CR1 Host',
     'C3b_host': 'complement C3b Host',
     'C3bBbC3bDAF_host': 'complement C3b complement factor Bb complement C3b DAF Host',
     'DAF': 'source-defined DAF state',
     'C3bBbC3bH_host': 'complement C3b complement factor Bb complement C3b H Host',
     'Surface_host': 'Surface Host',
     'C3bBbP_host': 'complement C3b complement factor Bb P Host',
     'P': 'source-defined P state',
     'C3bBbC3bP_host': 'complement C3b complement factor Bb complement C3b P Host',
     'C3bBP_host': 'complement C3b BP Host',
     'iC3bP_host': 'I complement C3b P Host',
     'iC3b_host': 'I complement C3b Host',
     'C3bBbC3bC5_host': 'complement C3b complement factor Bb complement C3b C5 Host',
     'C3bBbC3bPC5_host': 'complement C3b complement factor Bb complement C3b PC5 Host',
     'C3bBbC3bC5b_host': 'complement C3b complement factor Bb complement C3b C5b Host',
     'C3bBbC3bC5bC6_host': 'complement C3b complement factor Bb complement C3b C5b C6 Host',
     'C3bBbC3bPC5bC6_host': 'complement C3b complement factor Bb complement C3b Pc5b C6 Host',
     'C7': 'source-defined C7 state',
     'C3bBbC3bPC5b_host': 'complement C3b complement factor Bb complement C3b Pc5b Host',
     'C5b': 'C5b',
     'C5': 'source-defined C5 state',
     'C5a': 'C5a',
     'C6': 'source-defined C6 state',
     'C5b7_host': 'C5b7 Host',
     'C3bCR1_host': 'complement C3b CR1 Host',
     'C3bH_host': 'complement C3b H Host',
     'C3bB_host': 'complement C3b B Host',
     'C3bBbH_host': 'complement C3b complement factor Bb H Host',
     'C3bBbCR1_host': 'complement C3b complement factor Bb CR1 Host',
     'C3bBbDAF_host': 'complement C3b complement factor Bb DAF Host',
     'iC3bCR1_host': 'I complement C3b CR1 Host',
     'C3dg_host': 'C3dg Host',
     'C5b8_host': 'C5b8 Host',
     'C5b9_1_host': 'C5b9 1 Host',
     'C5b9_2_host': 'C5b9 2 Host',
     'C5b9_3_host': 'C5b9 3 Host',
     'C5b9_4_host': 'C5b9 4 Host',
     'C5b9_5_host': 'C5b9 5 Host',
     'C5b9_6_host': 'C5b9 6 Host',
     'C5b9_7_host': 'C5b9 7 Host',
     'C5b9_8_host': 'C5b9 8 Host',
     'C5b9_9_host': 'C5b9 9 Host',
     'C5b9_10_host': 'C5b9 10 Host',
     'C5b9_1__host': 'C5b9 1 Host',
     'C5b9_11_host': 'C5b9 11 Host',
     'C5b9_12_host': 'C5b9 12 Host',
     'C5b9_13_host': 'C5b9 13 Host',
     'C5b9_14_host': 'C5b9 14 Host',
     'C5b9_15_host': 'C5b9 15 Host',
     'C5b9_16_host': 'C5b9 16 Host',
     'C5b9_17_host': 'C5b9 17 Host',
     'MAC_host': 'MAC Host',
     'CD59': 'CD59',
     'CD59C5b9_1_host': 'Cd59c5b9 1 Host',
     'VnC5b7': 'Vn C5b7',
     'eculizumab': 'Eculizumab',
     'eculizumab_C5': 'Eculizumab C5'}
    _STATE_OUTPUT_ALIASES = {'C3': 'complement_c3',
     'C3_H2O__fluid': 'complement_c3_h2o_fluid',
     'B': 'source_defined_b_state',
     'C3_H2O_B_fluid': 'complement_c3_h2o_b_fluid',
     'C3_H2O_H_fluid': 'complement_c3_h2o_h_fluid',
     'H': 'source_defined_h_state',
     'C3_H2O_CR1_fluid': 'complement_c3_h2o_cr1_fluid',
     'CR1': 'source_defined_cr1_state',
     'Bb': 'complement_factor_bb',
     'C3_H2O_Bb_fluid': 'complement_c3_h2o_complement_factor_bb_fluid',
     'C3_H2O_BbH_fluid': 'complement_c3_h2o_complement_factor_bb_h_fluid',
     'Ba': 'source_defined_ba_state',
     'D': 'source_defined_d_state',
     'C3b_fluid': 'complement_c3b_fluid',
     'H2O': 'h2o',
     'nfC3b': 'nf_complement_c3b',
     'nhC3b': 'nh_complement_c3b',
     'C3bB_fluid': 'complement_c3b_b_fluid',
     'C3bH_fluid': 'complement_c3b_h_fluid',
     'C3bCR1_fluid': 'complement_c3b_cr1_fluid',
     'C3bBb_fluid': 'complement_c3b_complement_factor_bb_fluid',
     'C3bBbH_fluid': 'complement_c3b_complement_factor_bb_h_fluid',
     'C3bBbCR1_fluid': 'complement_c3b_complement_factor_bb_cr1_fluid',
     'C3a': 'c3a',
     'I': 'source_defined_i_state',
     'iC3b_fluid': 'i_complement_c3b_fluid',
     'iC3bCR1_fluid': 'i_complement_c3b_cr1_fluid',
     'C3dg_fluid': 'c3dg_fluid',
     'C5b7_micelle': 'c5b7_micelle',
     'hC5b7_fluid': 'h_c5b7_fluid',
     'C5b8_fluid': 'c5b8_fluid',
     'C8': 'source_defined_c8_state',
     'Cn': 'source_defined_cn_state',
     'CnC5b7_fluid': 'cn_c5b7_fluid',
     'Vn': 'source_defined_vn_state',
     'VnC5b7_fluid': 'vn_c5b7_fluid',
     'C9': 'source_defined_c9_state',
     'VnC5b8_fluid': 'vn_c5b8_fluid',
     'VnC5b9_1_fluid': 'vn_c5b9_1_fluid',
     'CnC5b8_fluid': 'cn_c5b8_fluid',
     'CnC5b9_1_fluid': 'cn_c5b9_1_fluid',
     'C5b9_1_fluid': 'c5b9_1_fluid',
     'C3bBbC3b_host': 'complement_c3b_complement_factor_bb_complement_c3b_host',
     'C3bBb_host': 'complement_c3b_complement_factor_bb_host',
     'C3bBbC3bCR1_host': 'complement_c3b_complement_factor_bb_complement_c3b_cr1_host',
     'C3b_host': 'complement_c3b_host',
     'C3bBbC3bDAF_host': 'complement_c3b_complement_factor_bb_complement_c3b_daf_host',
     'DAF': 'source_defined_daf_state',
     'C3bBbC3bH_host': 'complement_c3b_complement_factor_bb_complement_c3b_h_host',
     'Surface_host': 'surface_host',
     'C3bBbP_host': 'complement_c3b_complement_factor_bb_p_host',
     'P': 'source_defined_p_state',
     'C3bBbC3bP_host': 'complement_c3b_complement_factor_bb_complement_c3b_p_host',
     'C3bBP_host': 'complement_c3b_bp_host',
     'iC3bP_host': 'i_complement_c3b_p_host',
     'iC3b_host': 'i_complement_c3b_host',
     'C3bBbC3bC5_host': 'complement_c3b_complement_factor_bb_complement_c3b_c5_host',
     'C3bBbC3bPC5_host': 'complement_c3b_complement_factor_bb_complement_c3b_pc5_host',
     'C3bBbC3bC5b_host': 'complement_c3b_complement_factor_bb_complement_c3b_c5b_host',
     'C3bBbC3bC5bC6_host': 'complement_c3b_complement_factor_bb_complement_c3b_c5b_c6_host',
     'C3bBbC3bPC5bC6_host': 'complement_c3b_complement_factor_bb_complement_c3b_pc5b_c6_host',
     'C7': 'source_defined_c7_state',
     'C3bBbC3bPC5b_host': 'complement_c3b_complement_factor_bb_complement_c3b_pc5b_host',
     'C5b': 'c5b',
     'C5': 'source_defined_c5_state',
     'C5a': 'c5a',
     'C6': 'source_defined_c6_state',
     'C5b7_host': 'c5b7_host',
     'C3bCR1_host': 'complement_c3b_cr1_host',
     'C3bH_host': 'complement_c3b_h_host',
     'C3bB_host': 'complement_c3b_b_host',
     'C3bBbH_host': 'complement_c3b_complement_factor_bb_h_host',
     'C3bBbCR1_host': 'complement_c3b_complement_factor_bb_cr1_host',
     'C3bBbDAF_host': 'complement_c3b_complement_factor_bb_daf_host',
     'iC3bCR1_host': 'i_complement_c3b_cr1_host',
     'C3dg_host': 'c3dg_host',
     'C5b8_host': 'c5b8_host',
     'C5b9_1_host': 'c5b9_1_host',
     'C5b9_2_host': 'c5b9_2_host',
     'C5b9_3_host': 'c5b9_3_host',
     'C5b9_4_host': 'c5b9_4_host',
     'C5b9_5_host': 'c5b9_5_host',
     'C5b9_6_host': 'c5b9_6_host',
     'C5b9_7_host': 'c5b9_7_host',
     'C5b9_8_host': 'c5b9_8_host',
     'C5b9_9_host': 'c5b9_9_host',
     'C5b9_10_host': 'c5b9_10_host',
     'C5b9_1__host': 'c5b9_1_host_2',
     'C5b9_11_host': 'c5b9_11_host',
     'C5b9_12_host': 'c5b9_12_host',
     'C5b9_13_host': 'c5b9_13_host',
     'C5b9_14_host': 'c5b9_14_host',
     'C5b9_15_host': 'c5b9_15_host',
     'C5b9_16_host': 'c5b9_16_host',
     'C5b9_17_host': 'c5b9_17_host',
     'MAC_host': 'mac_host',
     'CD59': 'cd59',
     'CD59C5b9_1_host': 'cd59c5b9_1_host',
     'VnC5b7': 'vn_c5b7',
     'eculizumab': 'eculizumab',
     'eculizumab_C5': 'eculizumab_c5'}

    def __init__(self, model_path: str = 'data/MODEL2109110001.xml', integration_step: float = 0.01) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


Caruso2020ActivationOfTheAlternativeComplemModel2109110001Model = Caruso2020ActivationOfTheAlternativeComplemModel
