# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML wrapper for Wei2011_MLCactivationPathway_EndothelialPermeability."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Wei2011MlcactivationpathwayEndothelialpermeabiModel(TelluriumSBMLBioModule):
    """Faithful Tellurium execution of the bundled SBML source model."""

    _SBML_ID = 'MODEL1102210000'
    _TITLE = 'Wei2011_MLCactivationPathway_EndothelialPermeability'
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _HEADLINE_OUTPUTS = {'ca2plus_1': ('Ca2plus_1',
                   'native SBML value',
                   'Ca2plus 1. Maps to SBML symbol `Ca2plus_1` and is emitted in native SBML units.'),
     'ca2plus_2': ('Ca2plus_2',
                   'native SBML value',
                   'Ca2plus 2. Maps to SBML symbol `Ca2plus_2` and is emitted in native SBML units.'),
     'ca2plus_3': ('Ca2plus_3',
                   'native SBML value',
                   'Ca2plus 3. Maps to SBML symbol `Ca2plus_3` and is emitted in native SBML units.')}
    _INITIAL_CONDITION_INPUTS = {'initial_ca2plus_1': ('Ca2plus_1',
                           0.0,
                           'native SBML value',
                           'Initial level of Ca2plus 1. Maps to SBML symbol `Ca2plus_1`; exposed as a '
                           'traceable initial-condition perturbation.'),
     'initial_thrombin': ('thrombin',
                          0.0,
                          'native SBML value',
                          'Initial level of Thrombin. Maps to SBML symbol `thrombin`; exposed as a '
                          'traceable initial-condition perturbation.'),
     'initial_ca2plus': ('Ca2plus',
                         0.0083,
                         'native SBML value',
                         'Initial level of Ca2plus. Maps to SBML symbol `Ca2plus`; exposed as a '
                         'traceable initial-condition perturbation.')}
    _PARAMETER_INPUTS = {}
    _SPECIES_LABELS = {'thrombin': 'Thrombin',
     'Ca2plus_1': 'Ca2plus 1',
     'Hisatamine': 'Hisatamine',
     'Ca2plus_2': 'Ca2plus 2',
     'Ca2plus_3': 'Ca2plus 3',
     'Ca2plus_4': 'Ca2plus 4',
     'Ca2plus_5': 'Ca2plus 5',
     'Ca2plus_6': 'Ca2plus 6',
     'thrombin_R': 'Thrombin R',
     'pro_thrombinR': 'Pro Thrombin R',
     'thrombinR_active': 'Thrombin R active',
     'RGS': 'source-defined RGS state',
     'Inositol': 'Inositol',
     'degradation': 'Degradation',
     'RGSGq_alpha_GTP': 'RGS Gq Alpha GTP',
     'GTP': 'GTP',
     'Gq_alpha_GTP': 'Gq Alpha GTP',
     'GDP': 'GDP',
     'IP3R': 'IP3R',
     'IP3IP3R': 'IP3 IP3R',
     'p115RhoGEF': 'P115rho GEF',
     'RhoGAP': 'Rho GAP',
     'DAG': 'DAG',
     'IP3': 'IP3',
     'RhoGTP': 'Rho GTP',
     'PIP2': 'source-defined PIP2 state',
     'PC': 'source-defined PC state',
     'RhoGDP': 'Rho GDP',
     'Ca2plus_CaM': 'Ca2plus calcium M',
     'CaM2Ca2plus': 'calcium M 2ca2plus',
     'CaM3Ca2plus': 'calcium M 3ca2plus',
     'CaM4Ca2plus': 'calcium M 4ca2plus',
     'MLCK': 'source-defined MLCK state',
     'MLCK_Ca2plus_CaM': 'MLCK Ca2plus calcium M',
     'MLCK_3Ca2plus_CaM': 'MLCK 3ca2plus calcium M',
     'MLCK_4Ca2plus_CaM': 'MLCK 4ca2plus calcium M',
     'PKC': 'PKC',
     'PKC_active_3': 'PKC active 3',
     'PKC_active_3CPI17': 'PKC active 3 CPI 17',
     'CPI17MYPT1_PPase': 'CPI 17 MYPT1 Ppase',
     'pCPI17MYPT1_PPasep': 'P CPI 17 MYPT1 Ppasep',
     'CPI17': 'CPI 17',
     'MLC': 'source-defined MLC state',
     'pMLC': 'source-defined PMLC state',
     'pCPI17': 'P CPI 17',
     'Ca2plus': 'Ca2plus',
     'CaM': 'calmodulin',
     'G_beta_gamma_2': 'G beta response parameter Gamma 2',
     'PLC_beta': 'PLC beta response parameter',
     'Ca2plus_trunsp': 'Ca2plus Trunsp',
     'Ca2plus_pump': 'Ca2plus Pump',
     'G12_alpha_GDP': 'G12 Alpha GDP',
     'G12_alpha_GTP': 'G12 Alpha GTP',
     'Gq_alpha_GDP': 'Gq Alpha GDP',
     'PLC_beta_Gq_alpha_GTP': 'PLC beta response parameter Gq Alpha GTP',
     'Ca2plus_trunsp_2Ca2plus': 'Ca2plus Trunsp 2ca2plus',
     'Ca2plus_pump_Ca2plus': 'Ca2plus Pump Ca2plus',
     'ppMLC': 'Pp MLC',
     'MYPT1_PPasepMLC': 'MYPT1 Ppase P MLC',
     'MYPT1_PPaseppMLC': 'MYPT1 Ppase Pp MLC',
     'MLCKMLC': 'MLCK MLC',
     'MLCKpMLC': 'MLCK P MLC',
     'MLCK_4Ca2plus_CaM_MLC': 'MLCK 4ca2plus calcium M MLC',
     'MLCK_3Ca2plus_CaM_MLC': 'MLCK 3ca2plus calcium M MLC',
     'MLCK_4Ca2plus_CaM_pMLC': 'MLCK 4ca2plus calcium M P MLC',
     'MLCK_3Ca2plus_CaM_pMLC': 'MLCK 3ca2plus calcium M P MLC',
     'MLCK_2Ca2plus_CaMMLC': 'MLCK 2ca2plus calcium M MLC',
     'MLCK_2Ca2plus_CaM_pMLC': 'MLCK 2ca2plus calcium M P MLC',
     'MLCK_Ca2plus_CaM_MLC': 'MLCK Ca2plus calcium M MLC',
     'MLCK_Ca2plus_CaM_pMLC': 'MLCK Ca2plus calcium M P MLC',
     'PLC_beta_Gq_alpha_GTP_Ca2plus': 'PLC beta response parameter Gq Alpha GTP Ca2plus',
     'PKCCa2plus_DAG': 'PKC Ca2plus DAG',
     'PKCCa2plus': 'PKC Ca2plus',
     'PLC_beta_Ca2plus': 'PLC beta response parameter Ca2plus',
     'MYPT1_PPase': 'MYPT1 Ppase',
     'pMYPT1_PPase': 'P MYPT1 Ppase',
     'thrombin_pro_thrombinR': 'Thrombin Pro Thrombin R',
     'G12_alpha_beta_gamma_1_GDP': 'G12 Alpha beta response parameter Gamma 1 GDP',
     'G12_alpha_beta_gamma_1_GDPthrombinR_active': 'G12 Alpha beta response parameter Gamma 1 GDP '
                                                   'Thrombin R active',
     'G_beta_gamma_1': 'G beta response parameter Gamma 1',
     'Gq_alpha_beta_gamma_2_GDP': 'Gq Alpha beta response parameter Gamma 2 GDP',
     'Gq_alpha_beta_gamma_2_GDPthrombinR_active': 'Gq Alpha beta response parameter Gamma 2 GDP '
                                                  'Thrombin R active',
     'p115RhoGEFG12_alpha_GTP': 'P115rho GEF G12 Alpha GTP',
     'p115RhoGEFG12_alpha_GTPRhoGDP': 'P115rho GEF G12 Alpha GTP Rho GDP',
     'RhoGTPRhoGAP': 'Rho GTP Rho GAP',
     'PLC_beta_Ca2plus_PIP2': 'PLC beta response parameter Ca2plus PIP2',
     'PLC_beta_Gq_alpha_GTPCa2plus_PIP2': 'PLC beta response parameter Gq Alpha GTP Ca2plus PIP2',
     'MLCK2Ca2plus_CaM': 'MLCK 2ca2plus calcium M',
     'pMYPT1_PPaseppMLC': 'P MYPT1 Ppase Pp MLC',
     'pMYPT1_PPasepMLC': 'P MYPT1 Ppase P MLC',
     'Ca2plus_extleak': 'Ca2plus Extleak',
     'Ca2plus_IP3_IP3R': 'Ca2plus IP3 IP3R',
     'Ca2plus_ext1': 'Ca2plus Ext1',
     'Ca2plus_intleak': 'Ca2plus Intleak',
     'Ca2plus_int1': 'Ca2plus Int1',
     'RhoGDI': 'Rho GDI',
     'RhoGDPRhoGDI': 'Rho GDP Rho GDI',
     'pROCK': 'P ROCK',
     'ROCK': 'source-defined ROCK state',
     'RhoGTPROCK': 'Rho GTP ROCK',
     'pROCKMLC': 'P ROCK MLC',
     'pROCKpMLC': 'P ROCK P MLC',
     'RhoGTPROCKMLC': 'Rho GTP ROCK MLC',
     'RhoGTPROCKpMLC': 'Rho GTP ROCK P MLC',
     'pROCKMYPT1_PPase': 'P ROCK MYPT1 Ppase',
     'RhoGTPROCKMYPT1_PPase': 'Rho GTP ROCK MYPT1 Ppase',
     'VEGF': 'source-defined VEGF state',
     'VEGFR2': 'VEGFR2',
     'VEGFVEGFR2': 'VEGF VEGFR2',
     'VEGFVEGFR22': 'VEGF VEGFR2 2',
     'VEGFpVEGFR22': 'VEGF P VEGFR2 2',
     'VEGFpVEGFR22Shc': 'VEGF P VEGFR2 2 Shc adapter protein',
     'VEGFpVEGFR22pShc': 'VEGF P VEGFR2 2 P Shc adapter protein',
     'pShc': 'source-defined PSHC state',
     'pShcSHP': 'P Shc adapter protein SHP',
     'SHP': 'source-defined SHP state',
     'Grb2': 'Grb2 adapter protein',
     'VEGFpVEGFR22pShcGrb2': 'VEGF P VEGFR2 2 P Shc adapter protein Grb2 adapter protein',
     'Sos': 'SOS guanine-nucleotide exchange factor',
     'VEGFpVEGFR22pShcGrb2SOS': 'VEGF P VEGFR2 2 P Shc adapter protein Grb2 adapter protein SOS '
                                'guanine-nucleotide exchange factor',
     'Grb2Sos': 'Grb2 adapter protein SOS guanine-nucleotide exchange factor',
     'RasGDP': 'RAS GDP',
     'VEGFpVEGFR22pShcGrb2SOSRasGDP': 'VEGF P VEGFR2 2 P Shc adapter protein Grb2 adapter protein SOS '
                                      'guanine-nucleotide exchange factor RAS GDP',
     'VEGFpVEGFR22Grb2': 'VEGF P VEGFR2 2 Grb2 adapter protein',
     'VEGFpVEGFR22Grb2SOS': 'VEGF P VEGFR2 2 Grb2 adapter protein SOS guanine-nucleotide exchange '
                            'factor',
     'VEGFpVEGFR22Grb2SOSRasGDP': 'VEGF P VEGFR2 2 Grb2 adapter protein SOS guanine-nucleotide '
                                  'exchange factor RAS GDP',
     'Shc': 'Shc adapter protein',
     'RasGTP': 'RAS GTP',
     'Raf': 'RAF',
     'RasGTPRaf': 'RAS GTP RAF',
     'pRaf': 'source-defined PRAF state',
     'MEK': 'MEK',
     'pRafMEK': 'P RAF MEK',
     'pMEK': 'source-defined PMEK state',
     'pRafpMEK': 'P RAF P MEK',
     'ppMEK': 'Pp MEK',
     'ERK': 'ERK',
     'ppMEKERK': 'Pp MEK ERK',
     'pERK': 'PERK kinase',
     'ppMEKpERK': 'Pp MEK P ERK',
     'ppERK': 'Pp ERK',
     'Pase': 'source-defined PASE state',
     'pRafPase': 'P RAF Pase',
     'PP2A': 'PP2A',
     'ppMEKPP2A': 'Pp MEK PP2A',
     'pMEKPP2A': 'P MEK PP2A',
     'MKP3': 'source-defined MKP3 state',
     'ppERKMKP3': 'Pp ERK MKP3',
     'pERKMKP3': 'P ERK MKP3',
     'ppERKMLCK': 'Pp ERK MLCK',
     'RasGAP': 'RAS GAP',
     'RasGTPRasGAP': 'RAS GTP RAS GAP',
     'pMLCK': 'P MLCK',
     'ppERKpMLCK': 'Pp ERK P MLCK',
     'ppMLCK': 'Pp MLCK',
     'ppMLCKMLC': 'Pp MLCK MLC',
     'ppMLCKpMLC': 'Pp MLCK P MLC',
     'PLC_gamma': 'PLC Gamma',
     'PLC_gammaCa2plus': 'PLC Gamma Ca2plus',
     'PLC_gammaCa2plus_PIP2': 'PLC Gamma Ca2plus PIP2',
     'VEGFpVEGFR22PLC_gammaCa2plus': 'VEGF P VEGFR2 2 PLC Gamma Ca2plus',
     'VEGFpVEGFR22PLC_gammaCa2plus_PIP2': 'VEGF P VEGFR2 2 PLC Gamma Ca2plus PIP2',
     'VEGFpVEGFR22PLC_gamma': 'VEGF P VEGFR2 2 PLC Gamma',
     'eNOS': 'source-defined ENOS state',
     'PKCCa2plus_eNOS': 'PKC Ca2plus E NOS',
     'eNOSactive': 'E NOS active',
     'NO': 'source-defined NO state',
     'GC': 'source-defined GC state',
     'NOGC': 'source-defined NO-GC state',
     'NOGCGTP': 'NO GC GTP',
     'cGMP': 'source-defined CGMP state',
     'PKG': 'source-defined PKG state',
     'cGMPPKG': 'C GMP PKG',
     'PKGactive': 'PKG active',
     'PKGRaf': 'PKG RAF',
     'LArg': 'source-defined L-ARG state',
     'eNOSactiveLArg': 'E NOS active L Arg',
     'LCit': 'source-defined L-CIT state',
     'NO1': 'source-defined NO1 state',
     'NO2': 'source-defined NO2 state',
     'NO3': 'source-defined NO3 state',
     'ppERKpMLCKMLC': 'Pp ERK P MLCK MLC',
     'ppERKpMLCKpMLC': 'Pp ERK P MLCK P MLC',
     'ppERKVEGFpVEGFR22pShcGrb2SOS': 'Pp ERK VEGF P VEGFR2 2 P Shc adapter protein Grb2 adapter '
                                     'protein SOS guanine-nucleotide exchange factor',
     'pSOS': 'source-defined PSOS state',
     'ppERKVEGFpVEGFR22Grb2SOS': 'Pp ERK VEGF P VEGFR2 2 Grb2 adapter protein SOS guanine-nucleotide '
                                 'exchange factor',
     'H1R': 'H1R',
     'HistamineH1R': 'Histamine H1R',
     'H1Ractive': 'H1R active',
     'G_sub_q_endsub_alpha_beta_gamma_2_GDPH1Ractive': 'G Sub Q Endsub Alpha beta response parameter '
                                                       'Gamma 2 GDP H1R active',
     'PKGROCK': 'PKG ROCK',
     'Ca2plus_store': 'Ca2plus Store'}
    _STATE_OUTPUT_ALIASES = {'thrombin': 'thrombin',
     'Ca2plus_1': 'ca2plus_1',
     'Hisatamine': 'hisatamine',
     'Ca2plus_2': 'ca2plus_2',
     'Ca2plus_3': 'ca2plus_3',
     'Ca2plus_4': 'ca2plus_4',
     'Ca2plus_5': 'ca2plus_5',
     'Ca2plus_6': 'ca2plus_6',
     'thrombin_R': 'thrombin_r',
     'pro_thrombinR': 'pro_thrombin_r',
     'thrombinR_active': 'thrombin_r_active',
     'RGS': 'source_defined_rgs_state',
     'Inositol': 'inositol',
     'degradation': 'degradation',
     'RGSGq_alpha_GTP': 'rgs_gq_alpha_gtp',
     'GTP': 'gtp',
     'Gq_alpha_GTP': 'gq_alpha_gtp',
     'GDP': 'gdp',
     'IP3R': 'ip3r',
     'IP3IP3R': 'ip3_ip3r',
     'p115RhoGEF': 'p115rho_gef',
     'RhoGAP': 'rho_gap',
     'DAG': 'dag',
     'IP3': 'ip3',
     'RhoGTP': 'rho_gtp',
     'PIP2': 'source_defined_pip2_state',
     'PC': 'source_defined_pc_state',
     'RhoGDP': 'rho_gdp',
     'Ca2plus_CaM': 'ca2plus_calcium_m',
     'CaM2Ca2plus': 'calcium_m_2ca2plus',
     'CaM3Ca2plus': 'calcium_m_3ca2plus',
     'CaM4Ca2plus': 'calcium_m_4ca2plus',
     'MLCK': 'source_defined_mlck_state',
     'MLCK_Ca2plus_CaM': 'mlck_ca2plus_calcium_m',
     'MLCK_3Ca2plus_CaM': 'mlck_3ca2plus_calcium_m',
     'MLCK_4Ca2plus_CaM': 'mlck_4ca2plus_calcium_m',
     'PKC': 'pkc',
     'PKC_active_3': 'pkc_active_3',
     'PKC_active_3CPI17': 'pkc_active_3_cpi_17',
     'CPI17MYPT1_PPase': 'cpi_17_mypt1_ppase',
     'pCPI17MYPT1_PPasep': 'p_cpi_17_mypt1_ppasep',
     'CPI17': 'cpi_17',
     'MLC': 'source_defined_mlc_state',
     'pMLC': 'source_defined_pmlc_state',
     'pCPI17': 'p_cpi_17',
     'Ca2plus': 'ca2plus',
     'CaM': 'calmodulin',
     'G_beta_gamma_2': 'g_beta_response_parameter_gamma_2',
     'PLC_beta': 'plc_beta_response_parameter',
     'Ca2plus_trunsp': 'ca2plus_trunsp',
     'Ca2plus_pump': 'ca2plus_pump',
     'G12_alpha_GDP': 'g12_alpha_gdp',
     'G12_alpha_GTP': 'g12_alpha_gtp',
     'Gq_alpha_GDP': 'gq_alpha_gdp',
     'PLC_beta_Gq_alpha_GTP': 'plc_beta_response_parameter_gq_alpha_gtp',
     'Ca2plus_trunsp_2Ca2plus': 'ca2plus_trunsp_2ca2plus',
     'Ca2plus_pump_Ca2plus': 'ca2plus_pump_ca2plus',
     'ppMLC': 'pp_mlc',
     'MYPT1_PPasepMLC': 'mypt1_ppase_p_mlc',
     'MYPT1_PPaseppMLC': 'mypt1_ppase_pp_mlc',
     'MLCKMLC': 'mlck_mlc',
     'MLCKpMLC': 'mlck_p_mlc',
     'MLCK_4Ca2plus_CaM_MLC': 'mlck_4ca2plus_calcium_m_mlc',
     'MLCK_3Ca2plus_CaM_MLC': 'mlck_3ca2plus_calcium_m_mlc',
     'MLCK_4Ca2plus_CaM_pMLC': 'mlck_4ca2plus_calcium_m_p_mlc',
     'MLCK_3Ca2plus_CaM_pMLC': 'mlck_3ca2plus_calcium_m_p_mlc',
     'MLCK_2Ca2plus_CaMMLC': 'mlck_2ca2plus_calcium_m_mlc',
     'MLCK_2Ca2plus_CaM_pMLC': 'mlck_2ca2plus_calcium_m_p_mlc',
     'MLCK_Ca2plus_CaM_MLC': 'mlck_ca2plus_calcium_m_mlc',
     'MLCK_Ca2plus_CaM_pMLC': 'mlck_ca2plus_calcium_m_p_mlc',
     'PLC_beta_Gq_alpha_GTP_Ca2plus': 'plc_beta_response_parameter_gq_alpha_gtp_ca2plus',
     'PKCCa2plus_DAG': 'pkc_ca2plus_dag',
     'PKCCa2plus': 'pkc_ca2plus',
     'PLC_beta_Ca2plus': 'plc_beta_response_parameter_ca2plus',
     'MYPT1_PPase': 'mypt1_ppase',
     'pMYPT1_PPase': 'p_mypt1_ppase',
     'thrombin_pro_thrombinR': 'thrombin_pro_thrombin_r',
     'G12_alpha_beta_gamma_1_GDP': 'g12_alpha_beta_response_parameter_gamma_1_gdp',
     'G12_alpha_beta_gamma_1_GDPthrombinR_active': 'g12_alpha_beta_response_parameter_gamma_1_gdp_thrombin_r_active',
     'G_beta_gamma_1': 'g_beta_response_parameter_gamma_1',
     'Gq_alpha_beta_gamma_2_GDP': 'gq_alpha_beta_response_parameter_gamma_2_gdp',
     'Gq_alpha_beta_gamma_2_GDPthrombinR_active': 'gq_alpha_beta_response_parameter_gamma_2_gdp_thrombin_r_active',
     'p115RhoGEFG12_alpha_GTP': 'p115rho_gef_g12_alpha_gtp',
     'p115RhoGEFG12_alpha_GTPRhoGDP': 'p115rho_gef_g12_alpha_gtp_rho_gdp',
     'RhoGTPRhoGAP': 'rho_gtp_rho_gap',
     'PLC_beta_Ca2plus_PIP2': 'plc_beta_response_parameter_ca2plus_pip2',
     'PLC_beta_Gq_alpha_GTPCa2plus_PIP2': 'plc_beta_response_parameter_gq_alpha_gtp_ca2plus_pip2',
     'MLCK2Ca2plus_CaM': 'mlck_2ca2plus_calcium_m',
     'pMYPT1_PPaseppMLC': 'p_mypt1_ppase_pp_mlc',
     'pMYPT1_PPasepMLC': 'p_mypt1_ppase_p_mlc',
     'Ca2plus_extleak': 'ca2plus_extleak',
     'Ca2plus_IP3_IP3R': 'ca2plus_ip3_ip3r',
     'Ca2plus_ext1': 'ca2plus_ext1',
     'Ca2plus_intleak': 'ca2plus_intleak',
     'Ca2plus_int1': 'ca2plus_int1',
     'RhoGDI': 'rho_gdi',
     'RhoGDPRhoGDI': 'rho_gdp_rho_gdi',
     'pROCK': 'p_rock',
     'ROCK': 'source_defined_rock_state',
     'RhoGTPROCK': 'rho_gtp_rock',
     'pROCKMLC': 'p_rock_mlc',
     'pROCKpMLC': 'p_rock_p_mlc',
     'RhoGTPROCKMLC': 'rho_gtp_rock_mlc',
     'RhoGTPROCKpMLC': 'rho_gtp_rock_p_mlc',
     'pROCKMYPT1_PPase': 'p_rock_mypt1_ppase',
     'RhoGTPROCKMYPT1_PPase': 'rho_gtp_rock_mypt1_ppase',
     'VEGF': 'source_defined_vegf_state',
     'VEGFR2': 'vegfr2',
     'VEGFVEGFR2': 'vegf_vegfr2',
     'VEGFVEGFR22': 'vegf_vegfr2_2',
     'VEGFpVEGFR22': 'vegf_p_vegfr2_2',
     'VEGFpVEGFR22Shc': 'vegf_p_vegfr2_2_shc_adapter_protein',
     'VEGFpVEGFR22pShc': 'vegf_p_vegfr2_2_p_shc_adapter_protein',
     'pShc': 'source_defined_pshc_state',
     'pShcSHP': 'p_shc_adapter_protein_shp',
     'SHP': 'source_defined_shp_state',
     'Grb2': 'grb2_adapter_protein',
     'VEGFpVEGFR22pShcGrb2': 'vegf_p_vegfr2_2_p_shc_adapter_protein_grb2_adapter_protein',
     'Sos': 'sos_guanine_nucleotide_exchange_factor',
     'VEGFpVEGFR22pShcGrb2SOS': 'vegf_p_vegfr2_2_p_shc_adapter_protein_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor',
     'Grb2Sos': 'grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor',
     'RasGDP': 'ras_gdp',
     'VEGFpVEGFR22pShcGrb2SOSRasGDP': 'vegf_p_vegfr2_2_p_shc_adapter_protein_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp',
     'VEGFpVEGFR22Grb2': 'vegf_p_vegfr2_2_grb2_adapter_protein',
     'VEGFpVEGFR22Grb2SOS': 'vegf_p_vegfr2_2_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor',
     'VEGFpVEGFR22Grb2SOSRasGDP': 'vegf_p_vegfr2_2_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor_ras_gdp',
     'Shc': 'shc_adapter_protein',
     'RasGTP': 'ras_gtp',
     'Raf': 'raf',
     'RasGTPRaf': 'ras_gtp_raf',
     'pRaf': 'source_defined_praf_state',
     'MEK': 'mek',
     'pRafMEK': 'p_raf_mek',
     'pMEK': 'source_defined_pmek_state',
     'pRafpMEK': 'p_raf_p_mek',
     'ppMEK': 'pp_mek',
     'ERK': 'erk',
     'ppMEKERK': 'pp_mek_erk',
     'pERK': 'perk_kinase',
     'ppMEKpERK': 'pp_mek_p_erk',
     'ppERK': 'pp_erk',
     'Pase': 'source_defined_pase_state',
     'pRafPase': 'p_raf_pase',
     'PP2A': 'pp2a',
     'ppMEKPP2A': 'pp_mek_pp2a',
     'pMEKPP2A': 'p_mek_pp2a',
     'MKP3': 'source_defined_mkp3_state',
     'ppERKMKP3': 'pp_erk_mkp3',
     'pERKMKP3': 'p_erk_mkp3',
     'ppERKMLCK': 'pp_erk_mlck',
     'RasGAP': 'ras_gap',
     'RasGTPRasGAP': 'ras_gtp_ras_gap',
     'pMLCK': 'p_mlck',
     'ppERKpMLCK': 'pp_erk_p_mlck',
     'ppMLCK': 'pp_mlck',
     'ppMLCKMLC': 'pp_mlck_mlc',
     'ppMLCKpMLC': 'pp_mlck_p_mlc',
     'PLC_gamma': 'plc_gamma',
     'PLC_gammaCa2plus': 'plc_gamma_ca2plus',
     'PLC_gammaCa2plus_PIP2': 'plc_gamma_ca2plus_pip2',
     'VEGFpVEGFR22PLC_gammaCa2plus': 'vegf_p_vegfr2_2_plc_gamma_ca2plus',
     'VEGFpVEGFR22PLC_gammaCa2plus_PIP2': 'vegf_p_vegfr2_2_plc_gamma_ca2plus_pip2',
     'VEGFpVEGFR22PLC_gamma': 'vegf_p_vegfr2_2_plc_gamma',
     'eNOS': 'source_defined_enos_state',
     'PKCCa2plus_eNOS': 'pkc_ca2plus_e_nos',
     'eNOSactive': 'e_nos_active',
     'NO': 'source_defined_no_state',
     'GC': 'source_defined_gc_state',
     'NOGC': 'source_defined_no_gc_state',
     'NOGCGTP': 'no_gc_gtp',
     'cGMP': 'source_defined_cgmp_state',
     'PKG': 'source_defined_pkg_state',
     'cGMPPKG': 'c_gmp_pkg',
     'PKGactive': 'pkg_active',
     'PKGRaf': 'pkg_raf',
     'LArg': 'source_defined_l_arg_state',
     'eNOSactiveLArg': 'e_nos_active_l_arg',
     'LCit': 'source_defined_l_cit_state',
     'NO1': 'source_defined_no1_state',
     'NO2': 'source_defined_no2_state',
     'NO3': 'source_defined_no3_state',
     'ppERKpMLCKMLC': 'pp_erk_p_mlck_mlc',
     'ppERKpMLCKpMLC': 'pp_erk_p_mlck_p_mlc',
     'ppERKVEGFpVEGFR22pShcGrb2SOS': 'pp_erk_vegf_p_vegfr2_2_p_shc_adapter_protein_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor',
     'pSOS': 'source_defined_psos_state',
     'ppERKVEGFpVEGFR22Grb2SOS': 'pp_erk_vegf_p_vegfr2_2_grb2_adapter_protein_sos_guanine_nucleotide_exchange_factor',
     'H1R': 'h1r',
     'HistamineH1R': 'histamine_h1r',
     'H1Ractive': 'h1r_active',
     'G_sub_q_endsub_alpha_beta_gamma_2_GDPH1Ractive': 'g_sub_q_endsub_alpha_beta_response_parameter_gamma_2_gdp_h1r_active',
     'PKGROCK': 'pkg_rock',
     'Ca2plus_store': 'ca2plus_store'}

    def __init__(self, model_path: str = 'data/MODEL1102210000.xml', integration_step: float = 0.01) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


Wei2011MlcactivationpathwayEndothelialpermeabiModel1102210000Model = Wei2011MlcactivationpathwayEndothelialpermeabiModel
